### ISSUE TITLE
Comments about standalone notes

### ISSUE THREAD

**Issue by The-Compiler** [cmcaine/tridactyl#1]
As the developer of qutebrowser, some comments about the standalone document :wink:

> Two notable examples even have vim-like interfaces: qutebrowser and jumanji.

There are [many more](https://github.com/qutebrowser/qutebrowser#thanks--similar-projects), the most notable (because they're still somewhat active) are [uzbl](https://github.com/uzbl/uzbl/tree/next) and [vimb](https://github.com/fanglingsu/vimb).

Jumanji is a bad example really - it's [abandoned](https://git.pwmt.org/pwmt/jumanji) and hasn't seen activity in over a year (it also uses WebKit1 which has been removed from WebKitGTK almost 3 years ago and deprecated for longer).

> * Kerning/font presentation code? (text in qutebrowser looks bad on Windows, don't know why)

The windows build is on a rather old Qt version and still using the QtWebKit backend, which is generally handling those kinds of things in a worse way. It should improve (read: look like in Chromium) once I manage to build a Windows build with the QtWebEngine backend, but there are some difficulties there (I managed to do so for OS X a few days ago).

> * Cross-platform OS shit

qutebrowser is using Python and Qt, so most stuff is taken care of. Deployment (see above) is probably the most annoying thing.

> * safebrowsing?

As in private browsing / icognito mode?

> * how much security stuff in engine/vs browser?

A lot of it is in the engine. With QtWebEngine, qutebrowser does really no network stuff at all (except blocking some requests) - with QtWebKit it's a little bit more, but by no means something low-level.

There were some embarassing bugs (the worst of them being passwords being logged in the debug log because it logged the element with keyboard focus, and the debug representation of it included its value), but those kinds of things can happen in a complex extension as well I'd imagine.

> * webm, webgl and similar? Presumably handled either by the engine or externally, but maybe picking and maintaining link to external thing is expensive.
> * flash handling?

Entirely handled by the engine. It's literally one line each in qutebrowser to map the setting to a qutebrowser one (to disable those).

> * developer tools (neat, but no reason for us to re-implement).

Implemented by the respective engine, i.e. you get WebKit or Chromium development tools, essentially for free (though using them with QtWebEngine is a bit cumbersome at the moment, still waiting for a better Qt API for that)

> * Firefox sync is neat and would be missed.
> We also lose access to the existing addon/extension repos. Maybe if we implemented webextension support in our own browser we'd get them back? Don't know how difficult that is.

qutebrowser has plans for a (Python, at first) plugin API. I'll look at WebExtensions some time after that, but it's definitely some more effort to implement all those APIs.

> ### A life without the addon store:
> 
> * site blocker --> /etc/hosts

Also built in in qutebrowser (with /etc/hosts-like blocking lists), as there are reasons you can't use /etc/hosts easily (like on a machine without root, and not sure how things look on Windows/OS X)

> * noscript is shit anyway

Those kinds of things can be done with a concept of just having per-domain settings, which is the next big thing I plan working on.

> * hide fedora is neat, but maybe just an element hiding list? Maybe it does have to parse differently.
>     * example of neat addon that a smaller browser wouldn't have available, anyway.

But it'd probably be trivially portable when said smaller browser has a plugin API :wink:

---

If you want to know more about some subject, ask away!

**Comment by cmcaine** [comment]
Hi, and thanks for commenting and for clearing this stuff up for us. We didn't expect our repo to attract so much interest :)

By safebrowsing I meant Google's safebrowsing API, or similar efforts. Which is probably easy to implement, if desired.

>If you want to know more about some subject, ask away!

As you've so kindly offered, what does Qutebrowser actually have to do itself (What's the non-WebEngine bit of a browser?)? My guesses:

* Tabs
* Catching user input for its own UI
* Maybe catching user input to feed into WebEngine?
* UI (commands, maps, autocompletions, statusline, downloads, etc)
* Bookmarks
* Aggregated history (assuming WebEngine handles history for individual tabs)

Thanks again :)

**Comment by The-Compiler** [comment]
Roughly speaking:

- Generally, some lightweight integration everywhere with the respective backends for things like the inspector, showing error pages, etc.
- Downloads (things like asking for a filename, showing the UI, calculating stats etc. - but not low-level netwokring stuff)
- Adblocking (reading adblock lists, telling the engine which requests to block)
- Commandline / completion
- Hinting of links (getting elements which need a hint, drawing the labels, etc.)
- Configuration
- Spawning of external processes (to edit website forms with an external editor, or for [userscripts](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc)
- Saving/restoring sessions (which tabs are open in which windows)
