### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by benfitzg** [cmcaine/tridactyl#106]
Apologies for what may be an npm issue. I get the following mess:

```
$ npm install
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/jest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'tridactyl'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /data/buildsrc/tridactyl
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
```

Would love to contribute once I can get past this.

**Comment by cmcaine** [comment]
Did you edit any files before you tried to build?

I can't reproduce this. Could you try again? Maybe it's a transient network issue.

**Comment by benfitzg** [comment]
Nope, git clone, cd into the dir then npm install. Also tried `rm -rf ~/.npm`. Maybe it's the version of npm I have. Or that I'm running on debian. npm 1.4.21 fyi.

**Comment by bovine3dom** [comment]
I think the version of npm is too old. We're all on v5 ish. Someone else had a similar issue and I believe updating fixed it.

**Comment by benfitzg** [comment]
Yep, built node v8.0.0 then latest npm and then used this, npm install passes.

Thanks for the advice!
