### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by jinankjain** [cmcaine/tridactyl#11]
On running `./make`

```sh
cp: cannot stat 'commandline': No such file or directory
```

**Comment by bovine3dom** [comment]
We're moving to a new build system - some of the old files weren't deleted. The new method is `npm run build`.

I'll re-open this to remind us to document it.

**Comment by cmcaine** [comment]
Sorry about that: it was a big commit and I missed that I hadn't removed make and package.json. I've removed them now and updated the docs, including instructions on how to run a command to migrate from the old build system.

https://github.com/cmcaine/tridactyl/#user-content-building-and-installing

**Comment by jinankjain** [comment]
Thanks a lot for such a speedy response. Man you can't  imagine how happy I am getting vimperator back on FF57. You are doing an awesome job. :+1:
