### ISSUE TITLE
Add `:version` excmd with git commit hash included(was:  Add git commit hash to beta version number)

### ISSUE THREAD

**Issue by azuwis** [cmcaine/tridactyl#117]
Current beta version number, like `1.5.1pre409`, only contain info from `git rev-list --count HEAD`, make it hard to find exact corresponding git commit.

Adding commit hash to version number like from `git rev-parse --short HEAD` should make it better.

Or with proper git tags, use `git describe --tags` as beta version number:

    1.4.3-52-g94d08f1

which contains most recent tag, commit count from most recent tag to HEAD, and commit hash of HEAD.

**Comment by bovine3dom** [comment]
This is a limitation of the AMO: https://developer.mozilla.org/en-US/Add-ons/Distribution (scroll down to "Beta versions").

We could potentially store the version number somewhere when pushing to master, e.g. "version.txt" in the root directory.

**Comment by azuwis** [comment]
Thanks for the explanation.

Found another limit from [here](https://developer.mozilla.org/en-US/docs/Toolkit_version_format):

> A version string consists of one or more version parts, separated with dots.
> Each version part is itself parsed as a sequence of four parts: \<number-a>\<string-b>\<number-c>\<string-d>.

So git commit hash can not be matched as version part most of the time.

**Comment by cmcaine** [comment]
Chrome has a version_name key that would be suitable. We can set it, but firefox ignores it.

You can get the hash of a numbered commit with: `git rev-list origin/master|sed -n '422p'` where 422 is the commit number you want.

I think we'll just include the hash in the future `:version` excmd.

**Comment by azuwis** [comment]
A `:version` excmd with git commit hash included sounds great :)

I've updated the title as a reminder.

**Comment by bovine3dom** [comment]
Fixed as of `1.5.1-35-gd65acf9`.
