### ISSUE TITLE
Use rel=prev, rel=next hints for the 'clicknext' excmd

### ISSUE THREAD

**Issue by johnbeard** [cmcaine/tridactyl#118]
The `clicknext` excmd currently uses regexes on the inner text of links, looking for likely candidates.

Some sites use the `rel` attribute to make this more explicit. An example is http://wondermark.com, which also happens to use a Unicode triangle (◄) that's not in the current regex, so `clicknext` fails.

Although `rel` attributes are not always used (Amazon, EBay, Wikipedia and Google do not seem to use them, but Github's search does), they should be a pretty sure thing if present.

**Comment by chocolateboy** [comment]
See #120.

**Comment by bovine3dom** [comment]
Fixed in 949b384.
