### ISSUE TITLE
`f` Hinting doesn't work on some articles on PCGamer

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#127]
http://www.pcgamer.com/

Articles down the right hand side get no hints.

**Comment by gsbabil** [comment]
This is most likely a duplicate of #136

**Comment by bovine3dom** [comment]
Maybe? PCGamer has definite <a> tags, whereas instagram seems to listen to "click" events.

As a side note, someone is having too much fun making the PCGamer website: https://i.imgur.com/kjs5jVd.png

**Comment by bovine3dom** [comment]
Fixed in #164. Thanks @glacambre!
