### ISSUE TITLE
History completions - known issues

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#128]
1.5.1pre431 has completion on *open from history.

- shift tab doesn't loop
- tab loops but only because of a bug
- tab can tab past options that are in the viewport
- only the most recent 50 items of history are included (any more and it becomes unbearably slow)
- input is blocked by the search
- the input jumps around a lot
- first open of completions takes a short while - maybe we should preload it in background of each page
- search uses a lot more CPU than the omnibar and is generally a bit worse
- sorting of results is pretty useless; perhaps worth sorting / weighting by frecency
- sometimes duplicates appear

NB: command-line-history completion still exists but it is only bound to ctrl+f.

**Comment by caputchinefrobles** [comment]
From the last pull (last commit made "commit c66ca2ab62"...), commands "o" and "t" only show History Completion header div, being necessary typing "o" or "t" one more time to actually show history table and completions div.

**Comment by bovine3dom** [comment]
@caputchinefrobles. Thanks, I have undone the offending change and I think it is fixed now.

**Comment by caputchinefrobles** [comment]
Yes, it is fixed indeed. And thank you for the awesome job you've been doing so far. I'm still trying to grasp the code in order to contribute more than simply spotting bugs, which is quite important at this point anyway.

**Comment by kleschenko** [comment]
@bovine3dom have you tried to use `browser.history.search` for history completion? Seems like it allows fuzzy-search, works through all history and is very fast, at least the way it works in [vim-vixen](https://github.com/ueokande/vim-vixen/blob/master/src/background/histories.js#L64).

**Comment by bovine3dom** [comment]
No, we haven't, thanks for the information. We tried disabling fuse completely and it was still unbearably slow. I think the problem lies in the way we are redrawing the HTML. @cmcaine is thinking about using a react-a-like to make it easier.

**Comment by robsmith11** [comment]
While the interface is nice, the `open` and `tabopen` completions are big step back from the omnibar IMO, especially when typing just the first letter of a frequently visited domain name, where the omnibar will almost always select the appropriate URL.

I'm assuming there is no way to just capture the results from the omnibar algo, is there?  If not, do you expect to be able to improve tridactyl completion to get close to omnibar results?  Or will there be a way to continue using the omnibar for `tabopen`?

**Comment by bovine3dom** [comment]
@robsmith11 `bind t tabopen` will do what you want.

We can't use the omnibar results ourselves. We should get close to the omnibar level of usefulness soon... the main blocking issue is the terrible performance of building the HTML, so we can't add more history results / search completions / bookmarks.

I'd really hoped to have had sorted it out before it was released properly, sorry!
