### ISSUE TITLE
Instead of multi-letter hints have all but one as single letter 

### ISSUE THREAD

**Issue by miallo** [cmcaine/tridactyl#129]
Is there a way of having all but one hints as multi-letters when having many links in the window? Now you always have to make two keystrokes when you could have 25 single letter hints and for the bottom links have a single starting letter and then a varying second one. In many cases this would reduce the amount of required keystrokes. (Did I mention I am lazy?)

If that isn't enough than a second two-letter starting letter can be added (and so on, although I doubt that any website would be crazy enough for a need of that...).

**Comment by McSinyx** [comment]
> If that isn't enough than a second two-letter starting letter can be added (and so on, although I doubt that any website would be crazy enough for a need of that...).

Social media, e.g. Facebook, Reddit.

**Comment by stevenbell** [comment]
I think this is (sort of) implemented already.  If there are <= 26 links, then you get only single-letter hints.  If there are 27, then you get 26 hints which end in the H (AH through ZH), and then one that ends with a new second letter, "HJ".  At this point, if I type anything other than "H" (which could correspond to "HH" or "HJ", Tridactl takes me directly to the link, no second key required.  This does a pretty good job of minimizing keystrokes without having to make guesses about the page content or the users behavior.

**Comment by miallo** [comment]
You are correct. I also have JJ and JH as additional hints which fooled me into beliving that it wasn't the case.

But then I will 'correct' my question to: Can we scrap the final H of the hints? It is just not a clean UI and especially with many links it gets hard to see what you actually have to type and what you can ignore...

**Comment by cmcaine** [comment]
See #28.

Hints are as they are so that users don't need to type enter or space to select a hint. I think this is overall less confusing.

Further improvements are possible and discussion (in #28) and PRs are welcome.
