### ISSUE TITLE
Sanitize vimperator command

### ISSUE THREAD

**Issue by lassiewoof** [cmcaine/tridactyl#132]
Hi,
I really miss vimperator's `sanitize` command. It would be awesome to add it in tridactyl.

**Comment by bovine3dom** [comment]
https://github.com/vimperator/vimperator-labs/blob/71e029e4ef323448ff04d21ea49e5b19f90bbbf0/common/locale/en-US/various.xml#L69 - sanitise deletes cookies, etc. (I had no idea it existed).
