### ISSUE TITLE
[n]gt should go to the nth tab

### ISSUE THREAD

**Issue by larsks** [cmcaine/tridactyl#134]
A neat `vi` feature that was supported by vimperator was the ability to prefix an action with a numeric argument.  This often but not always was used for repetition; that is, if `j` is bound to `scroll down one screen`, then `4j` would scroll down four screens.  With the `gt` action it can be used to select a specific tab (`1gt` to go to the first tab, etc).

It would be neat to see this in tridactyl.

**Comment by bovine3dom** [comment]
Counts are already implemented for some commands, but there is bug where if a command has a count attached to it, e.g. `scrollline 10` (bound to j), we don't multiply the numbers together.

`[n]gt` currently goes to the nth next tab. I'm happy to change the behaviour to instead go to the nth tab, if that's how it was in Vimperator.

**Comment by larsks** [comment]
I think I was caught by both of the issues you mentioned.

While I don't have a vimperator-enabled Firefox handy, the behavior of `<n>gt` in Vim itself is as I described (goes to the `<n>th` tab).

**Comment by jstetten** [comment]
Given that there's already a quick way to jump to arbitrary buffer numbers, I would ask that `[n]gt` preserve the behavior of going to the nth next tab since there's no other way to accomplish this. (Similarly, `[n]gT` should select the nth previous tab.)

**Comment by larsks** [comment]
I would argue that "make it behave like vim" is more important, but since the original request here was less "bug" and more "not behaving like I expect" I'm just going to close the request.

**Comment by bovine3dom** [comment]
I was actually about to change the behaviour to make it like you asked. Does anyone have a compelling reason why they would want to navigate `n` tabs at once?

**Comment by bovine3dom** [comment]
@jstetten you can revert to the old behaviour with `bind gt tabnext` and `bind gT tabprev`.

**Comment by larsks** [comment]
Nice, thanks!  My vim-trained fingers are happy.

**Comment by cmcaine** [comment]
tabchoose replaced with `tabnext_gt` in e933c100d3fc2b446481c55b3649c63e90c1f9f9 because `gt` and `gT` aren't symmetric.

tabnext_gt gives vim semantics when mapped to `gt` (default).

**Comment by jstetten** [comment]
> Does anyone have a compelling reason why they would want to navigate n tabs at once?

Speed? The other answer is that some of us  with many tabs style unread tab titles differently (with CSS) so they stand out until attended to. If I am currently to the left of several such unread tabs and issue `4tabnext`, will tridactyl activate the appropriate tab while leaving all the intervening tabs in unread state? If so, great. If not, do any other options exist?

**Comment by bovine3dom** [comment]
Yes, `tabnext` jumps to the nth next tab directly as you desire.
