### ISSUE TITLE
Visual cue when yanking

### ISSUE THREAD

**Issue by yegle** [cmcaine/tridactyl#138]
In vimperator/pentadactyl I usually rely on the message to confirm that I did yank the URL. But right now there's no visual cue in tridactyl when yanking a page.

**Comment by bovine3dom** [comment]
Blocked by feedback to users #90.

We could potentially display a message in the command line with `fillcmdline` but I think that might be more confusing.

**Comment by yegle** [comment]
Currently pentadacyl show the yanked link in status line which is good enough for me.

**Comment by jcrowgey** [comment]
the 'user feedback' box in #90 now checked.  Is this unblocked?
