### ISSUE TITLE
Yank shortlink by default

### ISSUE THREAD

**Issue by yegle** [cmcaine/tridactyl#141]
It would be great if `yy` will yank `<link rel="shortlink">` instead of the full URL.

If `<link rel="shortlink">` is not available, use `<link rel="canonical">` as fallback.

E.g. for a Youtube link `https://www.youtube.com/watch?v=RcOD-1-0css&feature=youtu.be&t=19`:
- shortlink: `https://youtu.be/RcOD-1-0css`
- canonical link: `https://www.youtube.com/watch?v=RcOD-1-0css`

Reference to the standard: 
- http://microformats.org/wiki/rel-shortlink
- http://microformats.org/wiki/rel-canonical

**Comment by johnbeard** [comment]
I think this should at least be a different modes available on the excmd (e.g. `clipboard yank -s|-c`, or `clipboard yankshort|yankcanonical`) and those can be bound to `yy` either by default or by the user.

I'm not sure defaulting to the shortlink is intuitive to me. From the standard, too:
>  by adding rel="shortlink" to a [hyper]link, a page indicates that the hyperlink may be used for space constrained and/or manual entry

C.f the rel="canonical" standard:
>By adding rel="canonical" to a hyperlink, a page indicates that the destination of that hyperlink SHOULD be considered the preferred or definitive version of the current page.

I think there should still be a way to yank the "real" URL too, analogous to Ctrl-C'ing the address bar contents.

**Comment by bovine3dom** [comment]
I agree with John - I would be confused if `yy` didn't just copy the exact URL that I saw in the address bar.

I'm happy for `ys` and `yc` binds to be added for the shortlink and canonical versions.

**Comment by yegle** [comment]
One feature that drove me from vimperator to pentadactyl is that yanking in pentadactyl default to short link. But I can live with `ys` and `yc`.

Re @johnbeard you can search `canonical` and `shortlink` in the source code of the page to find the link.

**Comment by bovine3dom** [comment]
@yegle you can always do `bind yy yankshort` once we have it

**Comment by bovine3dom** [comment]
`ys` and `yc` added in 8ef19cb (thanks @glacambre).

YouTube does not seem to offer canonical or short links.
