### ISSUE TITLE
Ctrl+^ support

### ISSUE THREAD

**Issue by osleg** [cmcaine/tridactyl#145]
Offtopic:
First of all thanks for Tridactyl! 
Had a hard times finding something that could swap the pentadactyl, you guys rock! (Hope one day to join development with you ;) )

Ontopic:
Is Ctrl+^ support planned/possible? Jumping between last tabs without C-^ is quite painful :)

**Comment by bovine3dom** [comment]
You can bind e.g. `bind ^ buffer #`. Modifiers aren't supported yet, as per #41.

**Comment by osleg** [comment]
Aye I tried to bind like:
`bind ^ buffer #` and `bind ^ buffer #<CR>` (not sure whether <CR> is required/supported but anyway I did try it) and expected it to work when I press `^` eg `shift+6` but no luck :(

**Comment by osleg** [comment]
Hm on other hand `bind q buffer #` did work, it seems like binding `^` doesn't work

**Comment by johnbeard** [comment]
The former works for me (also Shift-6 on my keyboard)

**Comment by osleg** [comment]
Weird, after restarting the browser it did work for me as well

**Comment by bovine3dom** [comment]
The `<CR>` is definitely not required or supported. Glad it fixed itself.

**Comment by chaoyi** [comment]
If buffer command without parameter can default to #, then we don't need another binding for "buffer #".  type 'b' 'enter' twice will get back to the original.  That'll be quite useful.

**Comment by johnbeard** [comment]
I guess desire for `Ctrl-^` is born from familiarity with the Vim bindings for (nth) alternate buffer (`:help CTRL-^`)

It would make sense to me (as a user of LeaderF) to have the alt buffer pre-focussed in the buffer list when "b" is pressed. This could be a setting when we have config (start at top, start at alt, etc)?

**Comment by osleg** [comment]
Yes, that's basic VIM command to switch to last (nth) buffer, so as soon as Ctrl modifiers will be supported (i hope they will) that imho should be default for tridactyl as it mimics vim :)

**Comment by azuwis** [comment]
Agree with @chaoyi. In fact Vimium has a similar [feather](https://github.com/philc/vimium/wiki/Tips-and-Tricks#recently-visited-tabs):

    Recently-Visited Tabs

    When the Vomnibar is in tabs mode (bound to T by default), tabs are initially ordered by recency. So:

    T<Enter> takes you to the most recently visited tab.

    T<Tab><Enter> takes you to the second most recently visited tab.

    And so on.

**Comment by osleg** [comment]
Since {penta/tri}dactyl/vimperator/vimium and so on basically follow VI design it would be wise to stick to vim decisions as
```
CTRL-^			Edit the alternate file.  Mostly the alternate file is
			the previously edited file.  This is a quick way to
			toggle between two files.  It is equivalent to ":e #",
			except that it also works when there is no file name.

			If the 'autowrite' or 'autowriteall' option is on and
			the buffer was changed, write it.
			Mostly the ^ character is positioned on the 6 key,
			pressing CTRL and 6 then gets you what we call CTRL-^.
			But on some non-US keyboards CTRL-^ is produced in
			another way.
```

**Comment by bovine3dom** [comment]
Bound to `<C-6>` a while ago.
