### ISSUE TITLE
Hitting ESC while in some input boxes - clears the input 

### ISSUE THREAD

**Issue by osleg** [cmcaine/tridactyl#146]
For example if I go into github.com without being logged in and click on Sign In it opens the page with uname and password fields.
Those fields are auto prefilled with auto-complete and the focus is inside the username by default.
Hitting ESC to bail out from the focus to further `f` and login - clears the username input and bails out.

**Comment by cmcaine** [comment]
We don't deliberately mess with any inputs except the tridactyl commandline.

Can you confirm that this does not occur with stock firefox?

**Comment by osleg** [comment]
With stock firefox there is a slight difference. When you hit ESC on auto prefilled input it clears the input indeed but the input is not losing focus. So basically you are able to remove prefilled data and type whatever required.
With tridactyl tho input losing the focus as expected since ESC should cancel focus of anything to move to normal mode. But it should not clear the input

**Comment by cmcaine** [comment]
I'm not able to reproduce this issue: when I press escape on a pre-filled input I just deselect the input.

You may have some luck editing line ~70 of keydown_content to call preventDefault() on escape keyevents.

**Comment by glacambre** [comment]
I can reproduce this issue. Adding preventDefault to keydown_content doesn't seem to change a thing. A possible workaround could be to change `browser.autofocus` to `false` in `about:config`. I didn't see any about:flag that could let Firefox know it shouldn't clear input fields on escape.

**Comment by Koushien** [comment]
> I didn't see any about:flag that could let Firefox know it shouldn't clear input fields on escape.

But that's a Firefox _feature_! https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIAutoCompleteController#handleEscape()
If my memory serves, @cmcaine even went to Mozilla a while back to address this not responding to preventDefault(). Our first workaround is 735c56a151f9510c640467789a1747ea4971584c and I believe is still why the blur listener is necessary in [commandline_frame.ts](https://github.com/cmcaine/tridactyl/blob/7574146e653894fe9765ac7a3e46fa474c0fd2ac/src/commandline_frame.ts#53).

If you want to fall down the Mozilla-Central rabbit hole, this should be the relevant section.
https://searchfox.org/mozilla-central/rev/7f45cb7cc0229398fc99849bdc150cb6462d6966/toolkit/components/autocomplete/nsAutoCompleteController.cpp#384

**Comment by bovine3dom** [comment]
@Koushien the blur listener stops you clicking outside the commandline and losing focus. That's just so you can always hit escape to close it.

**Comment by bovine3dom** [comment]
Is this issue still prevalent? I haven't noticed it.

**Comment by osleg** [comment]
This seems to be not an issue anymore, closing.
