### ISSUE TITLE
Support for Vim's dot (`.`) single-repeat command

### ISSUE THREAD

**Issue by gsbabil** [cmcaine/tridactyl#147]
Vimperator supported Vim's dot (`.`) command for single-repeat of the last executed action. 

From Vim's help page:

```
.			Repeat last change, with count replaced with [count].
			Also repeat a yank command, when the 'y' flag is
			included in 'cpoptions'.  Does not repeat a
			command-line command.

Simple changes can be repeated with the "." command.  Without a count, the
count of the last change is used.  If you enter a count, it will replace the
last one.  |v:count| and |v:count1| will be set.
```

It would be great to have a `repeat` command in Tridactyl to repeat the last action on the current page `1` or `N` times. Thank you.

**Comment by gsbabil** [comment]
@cmcaine 

The `:buffer #` command currently isn't repeatable with the newly
added `.` command. I'm on verion `1.7.0-36-g91d8bd1`.

Thank you.

**Comment by cmcaine** [comment]
Fixed :)
