### ISSUE TITLE
tabnext/tabprev do not wrap

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#150]
When using a Tridactyl version (currently Version 1.6.0pre469 on Firefox 57) downloaded from AMO, tabprev and tabnext do not wrap.
If you have 4 tabs, and you're on tab 1, tabprev -1 will not bring you to tab 4.
If you're on tab 1, tabprev -2 will bring you to tab 3.
No matter what you try, if you're on tab 4, tabnext will not bring you to another tab.

Everything works when using Tridactyl's last version in debugging mode.

**Comment by bovine3dom** [comment]
I have no idea how the debugger made the code work for you, it was definitely broken.
