### ISSUE TITLE
Version 1.6.0 not showing right version on :version

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#151]
Strangely, I updated the to the last release (1.6.0) and just to check if it updated correctly I ran ":version" which showed 1.5.1-59-g0743933. Is that right? Perhaps release build was not using scripts/git_version.sh...

**Comment by bovine3dom** [comment]
cmcaine forgot to push the tags. Maybe we should get the version number from manifest.json instead.
