### ISSUE TITLE
tabopen/tabprev behavior

### ISSUE THREAD

**Issue by thmsaurel** [cmcaine/tridactyl#152]
It is possible to create a loop with tab (it seems to me that it was a pentadactyl's functionality) ?

- Once you reach the first tab, call `:tabprev()` (or type `gT`) shall return the last tab.
- Once you reach the last tab, call `:tabnext()` (or type `gt`) shall return the first tab.

Anyway, thanks guys for your works on this add-on.

**Comment by bovine3dom** [comment]
It was previously, but a bug was introduced recently (see #150) that broke it. It has just been fixed and should appear in the beta builds soon.

**Comment by thmsaurel** [comment]
ok thanks for your quick answer
