### ISSUE TITLE
open bookmark

### ISSUE THREAD

**Issue by haoyangnz** [cmcaine/tridactyl#156]
Prior to #105 t is bound to `:tabopen` which we can then use * to search for bookmarks in the firefox awesome bar.

Now that we have completion on `:tabopen`, we should implement a feature similar to `:buffer` to open a bookmark in a new tab. This could be part of `:tabopen` or it could be a new command.

Meanwhile the workaround would be to use t, then enter to continue to use the awesome bar, or pin all bookmarks to tabs and use `:buffer @`

**Comment by cmcaine** [comment]
You can just `bind t tabopen` to get the old behaviour.

Would adding bookmarks to the completion engine for `:open` solve your issue? That's planned, anyway :)

**Comment by haoyangnz** [comment]
@cmcaine Yes it would. I opened this request because I didn't see #90 mentioning about the completion to include bookmarks and wasn't sure if I was meant to comment on #90 directly.

Would you like me to close this issue?

**Comment by cmcaine** [comment]
Yep, let's close it. Completions aren't in properly yet because of performance issues. It's what I'm working on next.
