### ISSUE TITLE
Open and tapOpen to follow bookmarks with keyword

### ISSUE THREAD

**Issue by LeonKowalski** [cmcaine/tridactyl#160]
Is it possible to access bookmarked pages with keyword shortcut using 'open' or 'tabOpen' ?
examble ':open r' (will open my wwww.reddit.com bookmark which has 'r' as 'keyword')

**Comment by glacambre** [comment]
Unfortunately Mozilla plans on [killing the keyword feature](https://bugzil.la/1276817#c25). I guess Tridactyl could use the bookmark's title though, since it's already available in the webextension API.

**Comment by bovine3dom** [comment]
I was planning on doing bookmark title and URL matches, but we need to fix the performance problems first, really.

**Comment by bovine3dom** [comment]
Closing as duplicate of #90
