### ISSUE TITLE
tridactyl doesn't work on icinga monitoring page

### ISSUE THREAD

**Issue by FriendlyTroll** [cmcaine/tridactyl#163]
We use Icinga Classic UI 1.11.6 (Backend 1.11.6) for monitoring our servers. Pressing "f" to display hints does nothing, neither does pressing "o".

**Comment by ocharles** [comment]
This is likely fairly inactionable for the devs, as they likely don't have Icinga installed, nor will they install it just to fix a bug. Could you perhaps save a page as HTML and host it somewhere, assuming the bug continues to happen there?

**Comment by FriendlyTroll** [comment]
That's okay, i just wanted to report a bug that happens in my case. It would be great if someone else can confirm this.

If I catch some time I will try to install Icinga on some server, so that the devs can test it.

**Comment by cmcaine** [comment]
@FriendlyTroll Could you test with the latest beta and test if #164 works?

**Comment by FriendlyTroll** [comment]
Still not working with 1.6.1pre501
