### ISSUE TITLE
Allow Modification of Tridactly New Tab Page

### ISSUE THREAD

**Issue by R030t1** [cmcaine/tridactyl#165]
Hello,

My apologies for opening an issue if this is covered elsewhere, but I couldn't find anything. I would like my new tabs to be blank. Has a bug report been filed on the Mozilla tracker about the inability to load Tridactyl on `about:newtab`?

Cheers,
     R0b0t1

**Comment by Koushien** [comment]
I'm not too aware of any recent developments, but https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 tracks the inclusion of an API that will allow WebExtensions, e.g., Tridactyl, to work on about:* pages. Notice it is blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1403295 which was last updated over a month ago.
I'm not the best person to ask regarding Tridactyl's config implementation, but modifying Tridactyl's new tab page sounds sensible enough and I'd wager if someone is going to write it at all it will likely happen before the introduction of a new API from Mozilla.

**Comment by cmcaine** [comment]
Hiding everything with CSS is totally doable.

**Comment by R030t1** [comment]
@cmcaine: I do not have an idea of where to start, unfortunately.

    self-evident
        adj. Evident to one’s self and to nobody else.

@Koushien: Thank you for the information, I requested clarification on why extensions should never be able to trigger UI actions. Unfortunately my experience with asking developers to explain their choices is that the questions will be ignored or the developers will write the asker off as annoying. Already, it looks like @cmcaine's initial question about a threat model went unanswered.

**Comment by bovine3dom** [comment]
`set newtab data:text/html <html style="background:black"></html>`
or
`set newtab data:text/html <html style="background:white"></html>`

Probably solves this issue, @R030t1.
