### ISSUE TITLE
Help needed - Messed up binding :

### ISSUE THREAD

**Issue by bobf32** [cmcaine/tridactyl#180]
So I was trying to bind ; to : to ease entering command mode, and I've kind of messed something up as I can no longer enter this mode. 

Is there alternative way to enter command mode, or maybe to clear all bindings?

**Comment by bovine3dom** [comment]
Sure. Go to `about:debugging`, tick enable add-on debugging, scroll down to Tridactyl, click "debug". A window should appear.

Click the console tab if it isn't selected already.

Then type `browser.storage.sync.set({userconfig: "",nmaps:{}})` and that should reset everything to default.

We've been meaning to add a reset button for a while... sorry this caught you out.

**Comment by bovine3dom** [comment]
Small typo in previous message - should probably be `userconfig: {}` instead of ""

**Comment by bobf32** [comment]
That's great, thanks.

**Comment by bovine3dom** [comment]
Did it work?

**Comment by bobf32** [comment]
I'm not sure. I think I had found an alternate way before trying - I pressed s which autofilled the command line with "open google", which I replaced with "help". I then found the reset command and used "reset :" and "reset ;".

**Comment by bovine3dom** [comment]
Ah, that's a much more sensible way of doing it. Thanks for sharing.
