### ISSUE TITLE
Tridactyl conflicts with Vim Vixen (was: find mode covers whole page)

### ISSUE THREAD

**Issue by pholat** [cmcaine/tridactyl#182]
Might be duplicate of #170 if so - please remove.

When pressing `f` with newest beta whole screen is set to yellow as in attachment:
![obraz](https://user-images.githubusercontent.com/6411862/33477783-44bc7bf0-d687-11e7-93f5-db8fadc2f269.png)

**Comment by bovine3dom** [comment]
I can't reproduce this on version 1.6.1-36-g1747ad4.

**Comment by pholat** [comment]
Reproduced on versions:
1.6.1-34-g7574146
1.6.1-36-g1747ad4

![obraz](https://user-images.githubusercontent.com/6411862/33481807-5d23c5a4-d696-11e7-985d-fa6c4354a99a.png)

Additionally to noscript I use two plugins:  addblock+ and noscript 
I can add log from `shitf+ctrl+j`

**Comment by bovine3dom** [comment]
Are you blocking the header? Does that image cover the entirety of the page, or did you scroll down a bit / crop it?

**Comment by pholat** [comment]
It was cropped, now it's whole screen:
![obraz](https://user-images.githubusercontent.com/6411862/33483003-f1dd8126-d69b-11e7-98ab-355f98f8f800.png)

What's more when i `esc` ot of it, I still have notifiers sticked, but there is no yellow foreground. Like this:
![obraz](https://user-images.githubusercontent.com/6411862/33483046-220f1f76-d69c-11e7-9493-05b697c21a17.png)

I have none hints when I second press `esc`. Here is console log:
`Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83
Object { shiftKey: false, metaKey: false, altKey: false, ctrlKey: false, repeat: false, key: "f", bubbles: true, composed: true, defaultPrevented: true, eventPhase: 1, 4 więcej… } normal  background.js:1266
Array [ "f" ] Object { ex_str: "hint" }  background.js:1284
hint Array [  ]  background.js:2734
Message: <unavailable>  content.js:83
State changed! mode hint  content.js:272
<unavailable> content.js:2708
HINTS <unavailable>  content.js:2713
Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83
Object { shiftKey: false, metaKey: false, altKey: false, ctrlKey: false, repeat: false, key: "Escape", bubbles: true, composed: true, defaultPrevented: true, eventPhase: 1, 4 więcej… } hint  background.js:1266
hintparser Array [ Object ]  background.js:1453
Array [ "Escape" ] Object { keys: Array[0], ex_str: "" }  background.js:1284
Message: <unavailable>  content.js:83
State changed! mode normal  content.js:272
Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83
Object { shiftKey: false, metaKey: false, altKey: false, ctrlKey: false, repeat: false, key: "Escape", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 więcej… } normal  background.js:1266`

**Comment by pholat** [comment]
I'm terribly sorry, Firefox synchronized Vim Vixen after I logged in and both plugins were working at once providing such confusing output.

**Comment by bovine3dom** [comment]
In all seriousness, we could potentially mitigate this with https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management, and if people install Vim Vixen we could have a prompt that asks them to choose between us and them, and then uninstall ourselves or the other one.

**Comment by Koushien** [comment]
Maybe go ahead and declare conflicts with all the other similar extensions? You can potentially rebind to escape conflicts, but I don't know how true that is now or in the future.

**Comment by guyzmo** [comment]
(@bovine3dom  disable would be smarter, not uninstall)

**Comment by bovine3dom** [comment]
I don't think this is common enough to worry about.
