### ISSUE TITLE
Vimperator Like Hint Mode

### ISSUE THREAD

**Issue by clov0** [cmcaine/tridactyl#183]
Is there a way for a Vimperator-like hint mode to be available as an alternative to the Vimium approach?
I mean for the hint mode labeling to be done using some -maybe prefixed- numbers, rather than text labels, and instead using text content of the element as a hidden tag for filtering and narrowing down while typing.

**Comment by bovine3dom** [comment]
I'd be overjoyed if someone would make a PR for this. We can have a `set hintmode vimperator | vimium`. Otherwise, it's reasonably far down my todo list.

**Comment by johnbeard** [comment]
You could also keep the current alphabetic hints, and have some sort of "escape" to enter the hinted element text, which will narrow down from whatever hints are left. Perhaps `:`? Would need to be able to get back to hint-label mode in case there are multiple elements with identical text.

**Comment by cmcaine** [comment]
Someone else suggested capital letters for the hints, lower case for searching text. I think vimperator just uses any key that doesn't match a hint label to search the hinted element text and link. That seems fine to me. There's some potential for confusion, but maybe we just show the current value of the search and hint select strings?

A bind to switch between searching hinted element text and hint label seems like a pretty good option for people who don't like to search often.

**Comment by jstetten** [comment]
>You could also keep the current alphabetic hints, and have some sort of "escape" to enter the hinted element text, which will narrow down from whatever hints are left. Perhaps :? Would need to be able to get back to hint-label mode in case there are multiple elements with identical text.

Vimperator used `mapleader` to toggle from hint-matching to text-matching and back again (if needed). `;` is handy and rarely appears in links, so worked well for me. For those using alphabetic hints, it was a simple solution.

**Comment by cmcaine** [comment]
@saulrh said on Riot that they'd have a go at this.

Circa here: https://matrix.to/#/!xmubtggllUtLrQiGyn:matrix.org/$15129502964031442GlZXO:matrix.org
