### ISSUE TITLE
Bind to fillcmdline tabopen loses focus on current tab

### ISSUE THREAD

**Issue by slackhead** [cmcaine/tridactyl#185]
I have a bind: 'fillcmdline tabopen' but when I use it I lose focus in the launching tab.

That is I cannot use arrow keys to scroll anymore, unless I click on the page or hit tab a few times.
Other commands like j and k will still scroll, and I can open a command line. If I do any of those then focus returns.

**Comment by bovine3dom** [comment]
@slackhead do you mean when you open a new tab, you do not get focus in the new tab? I cannot reproduce that.

Otherwise, the lack of focus on the page while typing into the command line is intended behaviour.

**Comment by slackhead** [comment]
Focus in the new tab is ok, but if I do a tabprev to the opening tab then I have lost focus in it.

**Comment by slackhead** [comment]
I've just updated to the latest beta and while on duckduckgo the links are still traversed after opening a tab from there, it seems ok on other pages.
