### ISSUE TITLE
[Feature request] `Tab` to cycle through available inputs after `gi` to focus input

### ISSUE THREAD

**Issue by azuwis** [cmcaine/tridactyl#191]
This is a feature from Vimium, which I find is really convenient to input something in web pages(for searching, login, etc.).

It highlights all inputs, make them easy to find. See in action:

![output](https://user-images.githubusercontent.com/9315/33516467-2644b476-d7ae-11e7-83db-cd3f334bcfe9.gif)

**Comment by Koushien** [comment]
I think a hint mode that only highlights input fields would be a better solution.

**Comment by azuwis** [comment]
Fixed by #192
