### ISSUE TITLE
Using Search Engines by Keyword?

### ISSUE THREAD

**Issue by georgewsinger** [cmcaine/tridactyl#194]
If vimperator, if you have -- i.e. -- a YouTube search engine with keyword `yt`, you can type

    :open yt <search term>

To open a youtube page with your search results. This doesn't seem to work with tridactyl; is it possible?

**Comment by bovine3dom** [comment]
Bookmark keywords aren't supported.

We have our own, though. There's a big list in src/excmds.ts / the help page (`open youtube` works, for example).

If you have a sensible request that isn't on there, let us know. In the meantime, you could make do with, e.g., `bind s fillcmdline_notrail open www.searchengine.com/&q=`

**Comment by FrancoCortesi** [comment]
Vim Vixem let's the user define associative arrays/dictionaries with keywords and urls. Could this be implemented in Tridactyl? I'd like to switch to Tridactyl but without user-configurable search engines I cant.

There is also this extension:
https://github.com/NumeriusNegidius/Context-Search/issues
Which reads search engines from bookmarks. I'm not a developer buy maybe there is some way of doing the same thing in Tridactyl?

PD: Thank you for this extension. I have some time without programming anything but I'd like to look at the code and if possible, to contribute some lines.

**Comment by bovine3dom** [comment]
The hold up is really that I haven't worked out a good way of letting people set 2D data via the command line. I could just add another command like I did for binds, say, `searchadd [keyword] [searchurl]`, if you're really desperate.

Thanks for the link, I'll look into it.

**Comment by bovine3dom** [comment]
They just look for %s in the URL https://github.com/NumeriusNegidius/Context-Search/blob/master/background.js#L65 which we could probably do too.

They also have a neat way of getting favicons.

Thanks!

**Comment by bovine3dom** [comment]
The trouble with way that they are doing it is that there is no way of getting the keyword that was set.

We could use the bookmark title but I don't think that's very intuitive, as lots of people will just have left that as the page title.

I think we will just add our own setting for now.

**Comment by cortesifranco3** [comment]
Thank you very much, now I'm using Tridactyl. I had to switch to FF Developer Edition as to be able to edit content.js for tweaking those search engines. It is the right way of doing/using it?

I'll be wasting my time if I try to compile on windows?

**Comment by cortesifranco3** [comment]
Sorry. FF Dev Ed breaks some functionality of Tridactyl (`tabopen` and `clipboard tabopen` are not working with single words instead of urls)

In Windows I can't see any way of firing FF (Quantum) with web-ext without having to keep that cmd window.

**Comment by cmcaine** [comment]
There's no good reason for tabopen or clipboard to be broken on dev edition. I suspect a bad build or some other local issue.

If you want to develop tridactyl, I encourage you to install the windows subsystem for linux so that you don't need to re-write our build scripts.

Configuration of search engines will come along soonish.

**Comment by bovine3dom** [comment]
@cortesifranco3 the latest betas from the AMO should have `searchsetkeyword [keyword] [URL]`, introduced in commit 11b208c.

**Comment by cortesifranco3** [comment]
Nice! Thank you.
