### ISSUE TITLE
Scrolling down on GitHub is really annoying

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#20]
h/j are nicked for going up and down on files.

**Comment by Koushien** [comment]
Cannot replicate. Are you still having this issue?
On raws I can scroll up/down just fine. On the other hand, `scrollx` doesn't exist anymore but the parser wasn't updated to reflect that. Pressing the L key opens a `Jump to line` prompt on blob pages, but I'm experiencing no other problems in Github with Tridactyl.

**Comment by cmcaine** [comment]
J and K go up and down the file list, if it's on screen.

This is just that we need to preventDefault/stopPropagation before github does its thing.

**Comment by Koushien** [comment]
Ah, I see I read "files" wrong there. I spoke too soon there. Should I hack in preventDefault/stopPropagation by default and a heavy-handed IGNORE ALL mode?

**Comment by cmcaine** [comment]
That seems sensible. There's already a message listener in keydown_content. keydown_background just needs to have some function to turn suppression on and off.

**Comment by Koushien** [comment]
Not sure if you saw [my messages on #tridactyl][ref], but I was hardcoding preventDefault(), stopPropagation() and even stopImmediatePropagation() in keyeventHandler and I could not stop GitHub scripts from also receiving the key. Should I be trying it somewhere else?

[ref]: https://matrix.to/#/!xmubtggllUtLrQiGyn:matrix.org/$15085540342278543lPBEe:matrix.org

**Comment by cmcaine** [comment]
Ah, I missed those.

I'll look into it in a few hours. I'm sure there's some way of doing it. Possibly by registering a listener for descending rather than ascending events?

**Comment by bovine3dom** [comment]
Fixed in https://github.com/cmcaine/tridactyl/commit/8d53fd60eb17f7a33c9b72af60981ea1ab7edb8c
