### ISSUE TITLE
Multi-letter hints not handled properly when first letter is unique

### ISSUE THREAD

**Issue by terminalmage** [cmcaine/tridactyl#201]
When using hints to navigate, and there are enough hint-able elements for the hints to be two letters, there are certain edge cases in which some of the hints are unique with just a single letter. For example, there would be a `PH` hint but that is the only hint which starts with the letter `P`. In these cases, the hint is followed after the `P` is pressed, and does not wait for the `H`.

This doesn't make tridactyl unusable by any means, but it can be confusing.

**Comment by cmcaine** [comment]
This should be fixed in #171. Try a more recent beta?

**Comment by terminalmage** [comment]
I thought I had the latest beta, but I was on `pre526`, not `pre536`. Upgrading to 536 changed it so that on the same page which had the double-letter hints, the hints are now all single-letter.

Since the hint behavior has definitely changed, it look slike it is indeed resolved. I'll comment if I see it pop up again.

Thanks!

**Comment by cmcaine** [comment]
Thanks to @orangenschalen!

Re-open if the issue re-occurs :)
