### ISSUE TITLE
hinting on myanimelist.net hover drop down menu

### ISSUE THREAD

**Issue by Bazalia** [cmcaine/tridactyl#204]
The https://myanimelist.net/ website has drop down menus that appear when the mouse hovers over them. Hinting captures the menu headings but selecting the hint does not drop down that menu.

Note: If the mouse hovers on at least one of the headings then hinting starts working.

**Comment by bovine3dom** [comment]
Using FF find mode to focus the text on the drop down and then pressing enter doesn't work either, so this is probably a poorly designed website.

We'll still look into supporting it.

**Comment by glacambre** [comment]
These dropdown menus appear because of a javascript MouseOver event. As far as I know there is no way to get existing event listeners for an HTML element, however, depending on when Tridactyl is loaded (before the loading page's JS starts executing?) we might be able to replace the browser's addEventListener function (we would need to do that for all prototypes of all HTML elements though) with our own, which would let us keep track of elements that have an interesting event (e.g. MouseOver, Click...) and know whether they need hints in hint mode or not. 
If this is possible, it doesn't mean it's a good idea to implement it, there might be severe performance issues to doing such a thing.

**Comment by johnbeard** [comment]
Adding a fake hover before out fake click seems to work: `hinting.ts:simulateClick/308`:

    DOM.mouseEvent(target, "hover")

I guess that's fairly innocuous, as a mouse user would struggle to click without a hover happening?

PS: Dear me that site doesn't work well without an adblocker.

**Comment by cmcaine** [comment]
@johnbeard They must be listening for mouseenter or mousemove. We can just add those to the list of events to send for a click.

```ts
/**
 * Dispatch a mouse event to the target element
 * based on cVim's implementation
 * @param {HTMLElement} element
 * @param {'hover' | 'unhover' | 'click'} type
 * @param {{ ctrlKey, shiftKey, altKey, metaKey }} modifierKeys
 */
export function mouseEvent (element: Element, type: 'hover'|'unhover'|'click', modifierKeys = {}) {
    let events
    switch (type) {
        case 'hover':
            events = ['mouseover', 'mouseenter', 'mousemove']
            break
        case 'unhover':
            events = ['mousemove', 'mouseout', 'mouseleave']
            break
        case 'click':
            events = ['mouseover', 'mousedown', 'mouseup', 'click']
            break
    }
    events.forEach(type => {
        const event = new MouseEvent(type, {
            bubbles: true,
            cancelable: true,
            view: window,
            detail: 1, // usually the click count
            ...modifierKeys
        })
        element.dispatchEvent(event)
    })
}
```

**Comment by cmcaine** [comment]
@glacambre I'm not against modifying the addEventListener prototype, and I don't know if we're guaranteed to run before page content (we might be, page to check is the content scripts key section in the manifest.json article on mdn).

**Comment by glacambre** [comment]
@cmcaine From what I understand Tridactyl runs before a `load` event is triggered ([https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extensionTypes/RunAt](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extensionTypes/RunAt)) which should in theory be enough to follow the procedure I described, however I haven't managed to do anything by adding the following piece of code to contents.js.
```javascript
let replaceEventListener = (x) => {
    x.addEventListener = (function (realAddEvent) {
        return function (...args) {
            console.log("Proxy addEventListener called.", args)
            realAddEvent.apply(this, args)
        }
    })(x.addEventListener).bind(x)
}
replaceEventListener(EventTarget.prototype);
replaceEventListener(EventTarget);
replaceEventListener(Window.prototype);
replaceEventListener(window);
replaceEventListener(Document.prototype);
replaceEventListener(document);
```
While calling `document.addEventListener()` from content.js works, calling it from the HTML document after the `load` event is triggered doesn't do anything. I don't know what I could be doing wrong.

**Comment by cmcaine** [comment]
The window object exposed in the content script is not the one exposed to the web content (that would be a security risk).

You probably need window.exportFunction or to use window.eval:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Accessing_page_script_objects_from_content_scripts

**Comment by cmcaine** [comment]
We obviously need to be very careful about overriding page content stuff to avoid introducing vulnerabilities.
