### ISSUE TITLE
Use Firefox Search Engine List

### ISSUE THREAD

**Issue by thmsaurel** [cmcaine/tridactyl#208]
Hi, 

Instead of use a predefined search engines list, why don't use directly the search engine list in Firefox ? It's modifiable by user so everybody will be able to add his favorite search-engine (imdb, quora, reddit, twitter, qwant, …). 

About the same subject, it's possible to show available search-engines when you use `:[tab|win]open` (like pentadactyl use to do, maybe vimperator did the same but I didn't use it) ?

Thanks in advance for yours answers and for your work on this awesome project,

**Comment by bovine3dom** [comment]
The first one is a limitation of web extensions (see issues about bookmark keywords).

You can already add a search engine in the beta versions with `searchsetkeyword keyword url`.

The second is possible but we currently only allow one completion category. We would probably generalise it to "command options" to show `-private`, and things you can set with `set`.
