### ISSUE TITLE
^C hide_and_clear

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#213]
I don't know it could actually be called an issue (probably not), but definitely a point for thought...

Even though there are ways of yanking/copying URLs within the context of tridactyl UI, the one that is very natural or intuitive to the new user would be ^C, which in commandline mode, is behaving like it would in bash vi mode. 

Considering that ^V works as paste from clipboard in command line, wouldn't it be correct to suppose ^C as copy instead of hide_and_clear? (text selection inside command line, of course)

**Comment by bovine3dom** [comment]
You raise a good point. I'd like to hear what other people think.

**Comment by jstetten** [comment]
It would be nice to have a setting that emulated the mappings found in `mswin.vim`. Perhaps even have it as the default for users on Windows...?

**Comment by Koushien** [comment]
Bias: I don't use ^C in cmdline.
To add to the top post, as long as ^A selects all in the cmdline, ^A^C is all too intuitive. That said, it's not very Vim-like and is a bad habit to form for Vim. You can observe from the results in #203 that being very close to Vim is highly regarded by ex-Vimperators. Yank should be one of the first things a user gets comfortable with after `hjkl`. Tridactyl already supports cmdline history and cmdline history search (to some degree at least, I haven't been keeping up) - to complete the whole shebang we just need to support goto-[start|end] and [forward|backward]-word and their variants.

**Comment by caputchinefrobles** [comment]
@Koushien you're completely right. My point with this issue is why ^A ^V and all other ^... are working as expected and ^C not, even though not being vim-like.

I understand that when you "set -o vi" on bash, ^C should take precedence and, as usually, interrupt  or skip the actual command line and start a new one (which is an usable function). But the way ^C is set in the context of tridactyl will only duplicate \<ESC\>, except for preventDefault:

```
        case "Escape":                                                                                                                                                                                                           
            keyevent.preventDefault()
            hide_and_clear()
            break
```
```
        case "c":
            if (keyevent.ctrlKey) hide_and_clear()
            break

```
This way is just one less key combination to use...

**Comment by Koushien** [comment]
Oh, I understand that ^A and ^V working as they normally would in any other input field in the browser while ^C is suppressed is strange. I feel by default ^C should behave as ^A does. Unless I'm mistaken, ^V to paste in Vimperator's commandline is supported by default, but both ^A and ^C are vim-like. If that is so, I'm of the mind to leave ^V untouched like Vimperator.

In Tridactyl, ^A currently selects all in the commandline so ^C performing a copy and not `hide_and_clear()` makes sense. However, I am in favor of having ^A move to the start of the commandline and letting ^C `hide_and_clear()`. In other words,

Now: ^A exhibiting normal Firefox behavior, ^C behaving vim-like ~> confusing
Improvement A: Both ^A and ^C behaving vim-like
Improvement B: Both ^A and ^C exhibiting normal Firefox behavior

And out of those option A is the more desirable for reasons I outlined in my previous post: being Vim-like is expected and people using Tridactyl for the first time who have never heard of Vim should understand it is different from stock Firefox and *not* come to rely on their usual shortcuts. Please let me know if I'm misunderstanding the conversation. 

The only other shortcut with a Ctrl-modifier I personally make use of is ^U which behaves natively in Firefox the way it would in Vim so I can't comment on the others.

**Comment by Koushien** [comment]
Some amendments to my posts.
Where I said vim-like, _vimperator_-like was more apt since ^A is more of an emacs binding. I don't use `set -o vi` for bash so I'm missing those pieces to the puzzle.

> The only other shortcut with a Ctrl-modifier I personally make use of is ^U which behaves natively in Firefox the way it would in Vim so I can't comment on the others.

Another lie that I've also spread on gitter. ^U actually clears the entire input and not just text before the cursor.
Vimperator supports, by default, emacs-style ^A, ^E, ^U, ^K. I've started work on these - would there be any objections to supporting them by default in the commandline?

Vimperator does not support emacs-style Alt+F, Alt+B in the commandline, but these are also something I'd like to see in Tridactyl. Early testing shows Alt to toggle the window menu can be suppressed so the most interesting part of implementing these appears to be defining the word boundaries.

If the above are implemented, when a `set -o vi` option is ready, it should be trivial to reuse the implementation in the given emacs-style bindings.

**Comment by cmcaine** [comment]
I personally don't use the Emacs binds much except c-n, c-p, c-r for history and c-u, but I know some people really love 'em.

Happy to accept PR for more Emacs binds for command line.

We'll provide some mechanism for picking between Firefox and Emacs.
