### ISSUE TITLE
Hinting doesn't detect duckduckgo's word pronouncer button

### ISSUE THREAD

**Issue by Bazalia** [cmcaine/tridactyl#215]
When displaying word definition, duckduckgo provides a button to play the pronunciation of the word. For example on the page https://duckduckgo.com/?q=define+deluxe&ia=definition you can click on the play button next to the word "deluxe" to listen to its pronunciation. Hinting does not capture this button.

**Comment by cmcaine** [comment]
This is a recurring issue with working out if a given element has event listeners. We might hijack the addEventListener function to try and deal with it.

See #212

**Comment by johnbeard** [comment]
FWIW, Vimperator doesn't consider this element hintable either.

**Comment by bovine3dom** [comment]
We could potentially "fix it" by having a setting for extra selectors that become hintable in all clicky hint modes, then people can add their own.
