### ISSUE TITLE
Scrolling doesn't work on Twitch

### ISSUE THREAD

**Issue by Bazalia** [cmcaine/tridactyl#218]
Scrolling up and down using j and k doesn't seem to work on twitch.com

**Comment by cmcaine** [comment]
Thanks for this bug report. We can't scroll because document.body is styled to 0 height and a reactroot div takes the place of the body.

Our code scrolls document.scrollingElement or something.

Anyway, we'll use twitch as a test case for the new scrolling logic.

**Comment by bovine3dom** [comment]
Fixed in dc65437. Thanks @glacambre!
