### ISSUE TITLE
Tridactyl does not work with owncloud market place

### ISSUE THREAD

**Issue by FardaleM** [cmcaine/tridactyl#220]
With tridactyl enable I can do nothing on the [onwcloud market place](https://marketplace.owncloud.com/).

**Comment by bovine3dom** [comment]
It sort of works for me. The CSS is a bit ruined - hints appear in the wrong place, and the commandline appears near the top of the page.

Does nothing work for you at all? not even, e.g. `gt`?

**Comment by FardaleM** [comment]
Tridactyl work on this page, but I can not interact with the webpage the mouse.

**Comment by cmcaine** [comment]
Their CSS forces iframes to be height: 100%; width: 100% and that makes our injected cover up the page.

Their CSS is presumably also messing with our hints.

Slapping !important on everything and optionally using cleanslate.css should fix it.

**Comment by cmcaine** [comment]
Metabug: #27

**Comment by FardaleM** [comment]
Thanks for the answer, what is cleanslate.css ?

**Comment by cmcaine** [comment]
http://cleanslatecss.com/

A CSS file that provides a class that you apply to an element to get browser default styles (or close approximations of).
