### ISSUE TITLE
Add an easy way to list current keybindings

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#222]
It would be nice if there were an easy way to show the current keybindings, i.e. not the default, but the user configured ones as well.

**Comment by glacambre** [comment]
This is a duplicate of https://github.com/cmcaine/tridactyl/issues/98 . This issue has been open for a while because there's no way to give users feedback yet (but it's planned in https://github.com/cmcaine/tridactyl/issues/90 ).

**Comment by behrmann** [comment]
Oh, I'm sorry, I missed that #98's title is not quite clear.
