### ISSUE TITLE
Improve modifier support on buffer command

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#223]
In pentadactyl pressing `b` would show the list of buffer, as it does in tridactyl. Pressing `<num>b` would jump directly to tab `<num>`. In tridactyl it prefills the commandline with `buffer <num>`. This is sufficiently similar, but has its own bugs. On my current window with 19 tabs pressing `6b` fills the commandline with `buffer 6`, but highlights tab 16 and pressing enter jumps to tab 16.

Directly jumping to tab `<num>` when pressing `<num>b` would be a nice addition.

**Comment by behrmann** [comment]
Thanks for the quick reaction. This is mostly fixed on `master` now, the only missing part, that pressing `2b` should not only prepopulate the commandline with a jump to buffer 2, but also do it right away.

**Comment by bovine3dom** [comment]
I think we should just make counts automatically execute commands.

**Comment by cmcaine** [comment]
@Koushien you were doing something to do with this, did you get anywhere?

**Comment by Koushien** [comment]
Huh, I thought you were talking about the options refactor, then I realized I did say I was to take a look at this specifically. Here's a naive implementation: https://github.com/Koushien/tridactyl/commit/3b899b552b7d0936586751601f861d1fa13334fe. It works as you'd expect with the default binds, but `fillcmdline (tab|win)?open #count` makes even less sense. Sorry for blocking.

**Comment by bovine3dom** [comment]
Described behaviour - `6b` filling the command line with `buffer 6` no longer happens.

Did it get broken in keyseq, @cmcaine?

**Comment by bovine3dom** [comment]
Closing in favour of #466.
