### ISSUE TITLE
Support modifying the website on open and tabopen

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#224]
In pentadactyl when using `open` or `tabopen` typing something would offer completion from the history, that could be tabbed through with `<tab>`. Tridactyl implements this as well. In pentadactyl though, pressing `<space>` would then paste the URL, so that it could be modified and further completions on the modified URL would be offered. This is a piece of functionality, that I do miss.

**Comment by cmcaine** [comment]
Would you prefer this to `<tab>` filling the commandline on every press (and you have to cycle through all the options to get your original input back)?

**Comment by behrmann** [comment]
> Would you prefer this to `<tab>` filling the commandline on every press (and you have to cycle through all the options to get your original input back)?
> 

Yes, that's what I'd prefer. (It's the default behaviour in pentadactyl)

**Comment by igoralmeida** [comment]
> Would you prefer this to <tab> filling the commandline on every press (and you have to cycle through all the options to get your original input back)?

I don't see this happening now, though. That's how vimperator used to work. Am I missing some kind of configuration or update?

**Comment by behrmann** [comment]
Excellent work, thanks!
