### ISSUE TITLE
`urlparent` should accept a count

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#231]
e.g. `2gu`: long.domain/with/many/slashes -> long.domain/with

**Comment by johnbeard** [comment]
What happens in a case like this: `2gu` on `http://sub.sub.domain.com/with` - does it give `http://sub.domain.com (i.e. strip one level of path and then one level of subdomain)? That would be an easy change: just repeated application of `getUrlParent()`.

**Comment by bovine3dom** [comment]
Yeah, I think it's an easy change, I just wanted to make sure that I didn't forget about it.

**Comment by bovine3dom** [comment]
Fixed in 022f4623965f27b7386f3f9837810a2a07a08de4
