### ISSUE TITLE
:set newtab foo.bar/page.html to also change other newtab actions

### ISSUE THREAD

**Issue by epheo** [cmcaine/tridactyl#235]
When setting newtab parameter to foo.bar/page.html I observe the following behavior:
- [ :tabopen ] + [ enter ] open the correct foo.bar/page.html
- [ :open ] + [ enter ] open foo.bar/undefined.html
- [ clic on newtab ] still open the Tridactyl new tab page

I confirm that my main firefox newpage setting is set to foo.bar/page.html

Is this the expected behavior ?
If not, how complex are the required changes ?

Many thanks, Thibaut.

**Comment by bovine3dom** [comment]
It's expected: we can't change the new tab page without changing the manifest and rebuilding the add-on, so we cheat and whenever a new tab page would be opened from Tridactyl, we open your new tab page instead.

We could cheat harder and have our new tab page run some JavaScript that would redirect to your chosen page, but it might look a bit janky.
