### ISSUE TITLE
Add aliases for common commands

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#236]
`:o` for open, t for tabopen, w for winopen etc.

**Comment by IsaacKhor** [comment]
Any suggestions for what commands should be aliased? This is what I have so far:

```
" These are the same commands as normal-mode aliased as ex commands
o => open
t => tabopen
w => winopen
H => back
L => forward
b => buffer
" include other normal-mode commands...
```

I don't really see the point, however, seeing as the normal-mode command is faster and does the exact same thing. Why type `:o search me` when you can do away with the `:`? Implementing it should be just adding several lines to `excmds`, but I still don't see the point.

**Comment by bovine3dom** [comment]
@IsaacKhor it was asked for - https://github.com/cmcaine/tridactyl/issues/154#issuecomment-351753434 - I also don't quite understand the desire for it, but I am quite happy for them to be there.

I'm not sure I agree with `H` and `L`. Did Vimperator do that?

The aliases will also need to be added to any relevant completions.

Thanks for looking into this.

**Comment by IsaacKhor** [comment]
I'm working on this right now; any other suggestions for completions? @bovine3dom, `H` and `L` comes from `config.ts` `nmap`; I'm not sure if vimperator did that. I've always used the builtin `cmd+[` and `cmd+]` bindings.

**Comment by IsaacKhor** [comment]
I've submitted a PR for a few commands; suggestions for more are welcome.

**Comment by Koushien** [comment]
Can confirm `:H` and `:L` weren't in Vimperator.
Re: The desire for these, I'd say it's pretty Vim-y to minimize keystrokes (say you already committed to opening the commandline) and could be helpful if you don't have those excmds bound to a key for whatever reason.

I'll also add that the aliasing for Vimperator was reasonably powerful, `:o`, `:op`, `:ope` all alias to `:open` with proper completions being shown. Ditto for the `:winopen` equivalents. Actually, what seems to be occurring is that if there is only one possible native excmd completion the alias is already applied.

**Comment by IsaacKhor** [comment]
I would say that the 'default to only available command' functionality should be implemented as part of autocompletion, which we need anyways. Vimperator's autocompletion has always been good, and I'll like to see that replicated here.

**Comment by cmcaine** [comment]
To match Vim, abbreviated excmds would work in maps, etc as well, not just on the command line.

If we wanted to match that behaviour it would mean changes to parsers/exmode as well as completions.

I don't support maps for e.g. `:H`. They don't match what I expect from vimperator or vim, I don't think they add much utility and they break the expectation that excmds starting with capital letters are user-defined rather than built-in.

Abbreviations of actual excmds are fine and can be manually added for now.

**Comment by IsaacKhor** [comment]
Feature implemented; issue should be closed.
