### ISSUE TITLE
Make buffer list scrollable

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#237]
I usually have more than 19 tabs open at a time. When pressing `b` I get a list of buffers 1 through 19 which I can tab through, unfortunately the tabbing wraps at 19 and goes back to tab 1. The list of course be moved to the actual tabs one wishes to see by typing keywords, but a nicer solution would be to scroll the list further when tabbing beyond the bottom entry and only wrap at the last tab.

**Comment by cmcaine** [comment]
Closing for metabug: #27
