### ISSUE TITLE
Preferred configured search engine not used

### ISSUE THREAD

**Issue by jsimonet** [cmcaine/tridactyl#240]
It seems the preferred search engine (qwant.com in my case) configured in FF is not used when I search with tridactyl (key o or s).

Environment : 
- Firefox 57.0.1 (64 bits) on Fedora 27
- Tridactyl 1.7.0

Steps to reproduce : 
- open a new tab, search something with the "address bar", qwant is used ;
- search something using key o or s, google is used.

**Comment by cmcaine** [comment]
Firefox doesn't let us know what your provider is.

You can set your default provider with `set searchengine bing` and add new providers with another command documented in :help.

This is a duplicate issue. Closing.
