### ISSUE TITLE
keybindings disabled after browsing to raw source on Github

### ISSUE THREAD

**Issue by holtzermann17** [cmcaine/tridactyl#243]
I visit a link like this one:

- https://github.com/cmcaine/tridactyl/blob/master/src/static/userChrome-minimal.css

I hit "`f hw`" to open the "raw" file

- https://raw.githubusercontent.com/cmcaine/tridactyl/master/src/static/userChrome-minimal.css

Now when I hit "`H`" nothing happens.

# Expected behavior 

Visit 

- https://en.wikipedia.org/wiki/Dactyly

Hit "`f p H`" and I am right back on the same page.

**Comment by bovine3dom** [comment]
Could be CSP as in #109 and #113.

**Comment by antonva** [comment]
This is definitely a CSP issue.

**Comment by cmcaine** [comment]
@antonva and I agreed on Riot to offer a config option to list sites where CSP willl be bypassed more aggressively. They're working on it.

**Comment by cmcaine** [comment]
WIP: #245

**Comment by holtzermann17** [comment]
It's not fixed but I guess this is a WONTFIX?

**Comment by bovine3dom** [comment]
No, it's a duplicate of issue #109, which we do intend to fix (unless Mozilla beat us to it).
