### ISSUE TITLE
Hints are positioned incorrectly on sites with an absolutely positioned body

### ISSUE THREAD

**Issue by Ssamm45** [cmcaine/tridactyl#244]
I first noticed this on [https://xkcd.com](https://xkcd.com). When you bring up the hints on a site with the body absolutly positioned and either with a percentage or a pixel value the hint letter is not positioned above the link

Here is an example(github would not let me upload html files)
[test.html.txt](https://github.com/cmcaine/tridactyl/files/1577728/test.html.txt)

I am running firefox 57.0.2 on 64 bit Arch Linux.

**Comment by bovine3dom** [comment]
Probably related to #112. Thanks for reporting!

**Comment by gsbabil** [comment]
Hi @Ssamm45, @bovine3dom,

I would like to add that this behaviour extends to other hints like
`hint -A`, `hint -s` etc. as well. Thanks.

**Comment by cmcaine** [comment]
Fixed in 5937ee2
