### ISSUE TITLE
gu not working on directories

### ISSUE THREAD

**Issue by plague-spreader** [cmcaine/tridactyl#256]
When visiting URLs like http://ftp.debian.org/debian/dists/ and pressing "gu" for going to the upper directory Tridactyl actually goes to http://ftp.debian.org/debian/dists (it just removes the trailing backslash) which obviously redirects to same URL as before (which is http://ftp.debian.org/debian/dists/ ).

The expected behavior should be going to http://ftp.debian.org/debian/

**Comment by cmcaine** [comment]
Thanks!

**Comment by cmcaine** [comment]
5fe6068b4ab38a3cdf26a5f0a0d4f516e9029828 Fixes your use case, the other one doesn't leave trailing slashes.
