### ISSUE TITLE
Keybindings in Help page

### ISSUE THREAD

**Issue by Klesus** [cmcaine/tridactyl#257]
The link on the help page that are supposed to show you the default keybindings does not show you the default keybindings. Instead I'm taken to something that looks like an API reference, titled "External module "parsers/normalmode" ". 

:help is the only documentation I know of, and the "Highlighted features" does not cover how to fully utilize the addon. If the addon is meant to be used it also has to be learnt, and there's no realistic way of learning it's usage as of writing.

**Comment by bovine3dom** [comment]
This should have been fixed in https://github.com/cmcaine/tridactyl/commit/8bc423913818ccfa2abbcac02d7810ec93227885.

What `:version` are you using? We recommend the beta builds: https://addons.mozilla.org/en-GB/firefox/addon/tridactyl-vim/versions/beta
Please confirm if updating fixes the issue so we can close this issue (or fix it).

**Comment by IsaacKhor** [comment]
The formatting could use some work; on my screen, its an unformatted JSON blob of the default config which, while an accurate reflection of the normal mode commands, is not exactly user-friendly. Maybe we should dynamically generate a page based on the normal-mode mappings (with tags to the docs for the commands, just like `:help` in vim), or at least a static one based on the default config?

At least add `white-space: pre` for now -- its currently unreadable.
![image](https://user-images.githubusercontent.com/30614624/34385045-f15efc24-eb5a-11e7-8c04-b2a26c6eed29.png)

**Comment by bovine3dom** [comment]
Yes, I agree it is bad. Issue #23 includes "improve help theme".

Issues #98 and #123 track progress towards better keybind help in general.

I believe the help page also links to the source on GitHub which is the nicest display of binds we currently have.

**Comment by Klesus** [comment]
@bovine3dom Ah yes that's been fixed. I was using the stable (?) version.
