### ISSUE TITLE
Migration between Tridactyl versions

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#260]
Particularly, documented ways to deprecate commands / configuration options (blocked by user feedback probably).

Also, we want a way to move a user from some old configuration scheme to another - for example, if a string configuration option becomes an object.

**Comment by cmcaine** [comment]
We could add a version number to the saved config and then apply appropriate transformations at load time if the stored version differs from the current version.

Transformations can be functions stored along with the version range they should be applied to. If current version is in that range, apply the transformation, else skip.

All this logic can be stored in a separate file used only by the background script on startup.

**Comment by cmcaine** [comment]
Config version would be independent of tridactyl version number.

**Comment by IsaacKhor** [comment]
In other words, treat config migration like database migrations.
