### ISSUE TITLE
Default xx binding

### ISSUE THREAD

**Issue by SevereOverfl0w** [cmcaine/tridactyl#262]
I saw this referred to "something", I think this might be a mistake.

**Comment by bovine3dom** [comment]
https://github.com/cmcaine/tridactyl/blob/master/src/config.ts#L69

Good spot. We just need to delete the offending line (I'll resist the temptation to add an extra x and make it go to a video of Anne Widdecome dancing): https://github.com/cmcaine/tridactyl/blob/master/src/config.ts#L69
