### ISSUE TITLE
Hold down first key to repeat command

### ISSUE THREAD

**Issue by Ssamm45** [cmcaine/tridactyl#263]
One thing I find annoying is when I want to cycle through open tabs is I try to press 'g' and then press 't' multiple times. However this opens the new tab command when I press the 't' key a second time. To make it work I have to release both 'g' and 't' and then press them both again.

**Comment by Minoru** [comment]
In Vim, commands are repeated with a dot; and Tridactyl implements the same. So you press `gt` once, and then you just keep pressing `.` until you've arrived at the tab you want.

If you've got only a handful of tabs and can count quickly, you can also try adding counts, like `2gt` or `5gt`. Hope this helps!
