### ISSUE TITLE
typedoc-webpack-plugin@1.1.4 requires a peer of typedoc@^0.5.0 but none was installed

### ISSUE THREAD

**Issue by Minoru** [cmcaine/tridactyl#268]
(Node.js newbie here, might just be doing something wrong.)

When I do `npm install` in my clone, I get the following error:

```
npm WARN typedoc-webpack-plugin@1.1.4 requires a peer of typedoc@^0.5.0 but none was installed.
```

[Due to caret](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), I can only install 0.5.*, but Tridactyl itself requires ^0.9.0. How can I resolve this?

**Comment by cmcaine** [comment]
This doesn't prevent the install or build from working correctly - we don't
use the typedoc-webpack plugin.

We should remove it from the requirements, I just haven't thought about it
till now because I either didn't add it or I added it so long ago I forgot.

Thanks for your interest!

**Comment by Minoru** [comment]
Ah, I see. Pull request incoming!
