### ISSUE TITLE
Scrolling doesn't work on gatesnotes.com

### ISSUE THREAD

**Issue by Minoru** [cmcaine/tridactyl#273]
Firefox 57.0.2, Vimperator 1.7.3-29-g25baa7a, NixOS (Linux)

If I open the front page of https://gatesnotes.com, or any other page on that site, I can't scroll the content with `j`, `k`, `gg` and `G`. `:scrollline 10` doesn't work either.

Space doesn't work at first, but if I click somewhere other than black header (at the top), space starts to scroll as it should. Same for Page Up and Page Down. Instead of clicking, I can press Tab three times (presumably to focus an element somewhere outside the header).

**Comment by Koushien** [comment]
CSS related. This occurs in ESR 52 with Vimperator as well.
It's sufficient to block https://www.gatesnotes.com/TGN/css/tgn50.min.css to reenable Tridactyl scrolling but this basically makes the page unusable.

**Comment by bovine3dom** [comment]
Fixed in 15c8c47, ta @glacambre!
