### ISSUE TITLE
searchsetkeyword does not function

### ISSUE THREAD

**Issue by alexwh** [cmcaine/tridactyl#275]
Tested on version 1.7.3 and 1.7.3pre598, when running `:searchsetkeyword wi https://www.wiktionary.org/search-redirect.php?family=wiktionary&language=en&search=`, then attempting to open a tab with `:tabopen wi test`, it simply uses the default search engine. Using default keywords like "mdn" work fine, and searchsetkeyword shows up under `:help`

**Comment by bovine3dom** [comment]
Probably introduced by #254 (if real - unconfirmed)

**Comment by Koushien** [comment]
Does this behavior still persist for you @alexwh? I ran exactly your commands in `1.7.3-31-g728c96f` and wiktionary is searched as expected.

**Comment by cmcaine** [comment]
The line Koushien provides is the output of :version. The bit after the g
is the short commit hash.

When investigating this I found that my sync storage repo had some kind of
error. Could you try running the following in the webconsole on a newtab
page:

tri.l(browser.storage.sync.get())

And if you don't use sync, replace sync with local. See if you get any
error messages. Intended result is quite a large object getting
console.log'd.

**Comment by alexwh** [comment]
Ah, my bad. Yes, that's the output of :version for me too.
I don't get any errors, but I get a small object:
```
 tri.l(browser.storage.sync.get())
Promise { <state>: "pending" }
{…}
userconfig: {…}
searchurls: "https://www.google.com/search?q=undefined"
__proto__: Object { … }
__proto__: Object { … }
```

**Comment by Koushien** [comment]
As opposed to a string, my `searchurls` in the profile I used to test this is an object containing the property `wi: "https://www.wiktionary.org/search-redirect.php?family=wiktionary&language=en&search="`

Can you try the excmd `:unset searchurls`? It should clear that property and you should be free to try setting it again. If that fails, a last resort to consider is `tri.l(browser.storage.sync.clear())` which will clear all your Tridactyl configurations and you may need to enable/disable or install/uninstall Tridactyl again.

**Comment by alexwh** [comment]
Yep, `:unset searchurls` seems to have fixed the issue.
Thanks for the help!
