### ISSUE TITLE
ServiceNow web application does not display when Tridactyl is enabled

### ISSUE THREAD

**Issue by rpmohn** [cmcaine/tridactyl#279]
My company uses ServiceNow (in the cloud) and when I have Tridactyl enabled the site does not display properly. It does display and work properly with Vim-Vixen, but I prefer Tridactyl. I also tried it on Chrome with cVim, and that add-on causes the same bad behavior there. 

I will certainly try to figure out exactly what in the code is causing this, but if anyone has experienced similar problems and knows more details already, please share them with me. 

Thanks! -Ross

**Comment by Koushien** [comment]
Would you be able to describe the sort of visual error occuring or provide comparison (expected vs actual) screenshots?

**Comment by rpmohn** [comment]
Using Tridactyl 1.7.3pre598. First shot is how it should look, second is all that happens with Tridactyl, and the circle next to Loading... just keeps spinning. 

![image](https://user-images.githubusercontent.com/4296967/34952754-ccced4c8-f9e8-11e7-86c6-663dc65efc1e.png)

![image](https://user-images.githubusercontent.com/4296967/34952780-e3b71650-f9e8-11e7-8851-53db9bc2b316.png)

**Comment by gardar** [comment]
I can confirm I have this issue as well with ServiceNow and Tridactyl enabled.

Could this possibly be related to #122 ?

**Comment by cmcaine** [comment]
Tridactyl shouldn't interfere with the host site like this. Until you issue a command, the only thing we do on content pages is insert an iframe element (as far as I recall).

Could be a CSS issue (long shot)? Could you have a look to see if the tridactyl iframe is covering up other elements of the page? It should be a zero height element at the bottom of the viewport.

Could you also have a look at the web console (F12) and copy any logged messages out of there? And also check the page to see how many iframes there are. Maybe their code relies on there being exactly one iframe on the page or something.

**Comment by mmarvo** [comment]
I see problems with service now also. Most of it loads ok but the side navigation frame just hangs with a loading animation. 
A quick look at the console shows a bunch of "Error: Permission denied to access property "nodeType" on cross-origin object" and "SecurityError: Permission denied to access property "document" on cross-origin object".
I suspected noscript and adblock but the errors persist after disabling them and restarting FF. Historically when I used pentadactyl ServiceNow always had some cross site scripts blocked by noscript but it did not seem to affect functionality. I think there were some calls between the company specific site and the generic service now domain.
For completeness I did disable Tridactyl and the side nav bar loads fine.

**Comment by cmcaine** [comment]
This is a proprietary site that we can't get at, right?

Can you provide a screenshot or other complete log with filenames and line
numbers of each error?

If permitted, please also send us the offending JS code if it is not our
own.

The JS may have a license at the top of the file or the license may be in
your agreement with service now or whatever.

**Comment by mmarvo** [comment]
Hi, yes its a proprietary site. My organisation is too big for me to get anywhere near licensing / permissions and sanitising screenshots might take me a while, I will look into it. I appreciate that this is not paid for support so I was just adding comments without really expecting an in depth analysis :)
The scripts it chokes on is angular_includes_1.4.jsx:109:210 which is google Angular stuff, no idea if its a pristine angular script or modified.

**Comment by rpmohn** [comment]
I'm going to post a bunch of screenshots from the web console now. Here's the first one of the console output when I reload our SNOW home page without Tridactyl or Vim Vixen enabled.

![image](https://user-images.githubusercontent.com/4296967/35742159-a2ccf5ce-0807-11e8-8475-694a2eec465d.png)

**Comment by rpmohn** [comment]
Here's with Vim Vixen loaded, for comparison. Same as with nothing except that a few seconds after the page completes loading, it spits out one cross-origin SecurityError. 

![image](https://user-images.githubusercontent.com/4296967/35742317-11acf6c4-0808-11e8-84aa-c2c5a3973860.png)

**Comment by rpmohn** [comment]
Now here are a few screenshots showing the errors when I reload with Tridactyl enabled. None of the initial successful console message appear at all. Does this help? I can grab more stuff if needed! 

![image](https://user-images.githubusercontent.com/4296967/35742748-746065ca-0809-11e8-9dd8-44abd89acd16.png)

![image](https://user-images.githubusercontent.com/4296967/35742767-82a1dc22-0809-11e8-81d9-abd71fd6831b.png)

![image](https://user-images.githubusercontent.com/4296967/35742787-9122caae-0809-11e8-9706-eb85eab54b79.png)

**Comment by cmcaine** [comment]
Thank you very much for these screenshots. I'd tweeted at the ServiceNow people asking for a demo account but haven't got any response yet.

Looks like their code is trying to access our iframe and doesn't catch the exception generated by the cross origin request. Presumably they're iterating over all iframes or elements or something in their setup.

Vim Vixen loads later than tridactyl (document_end rather than document_start) and that's plausibly why it doesn't interfere with the initial JS execution. Presumably ServiceNow listens to mutation events or something and that's why an error is emitted later with Vim Vixen.

We can delay creating the tridactyl iframe until we actually need it and that will probably let ServiceNow work as well as it does with Vim Vixen. Though there is a chance that our hints will confuse it (Tridactyl hint elements are added in the main document, Vixen's hints are in the iframe, as I recall), but hopefully not.

I'm at a hackathon this weekend, but this is a quick fix and I'll probably do it before Monday. Thanks for the detailed bug report!

**Comment by cmcaine** [comment]
I didn't implement the fix I suggested above, but I tried something else. Could someone check with beta >= 1.7.3pre670 ?

**Comment by nipsy** [comment]
I'm running 1.7.3pre677 on Firefox 58.0.1 64-bit under Linux and it still breaks things.  The behavior is slightly different than before.  In the past, the sidebar would show a spinning loading logo like it was still trying to do something.  Now, the background colors are properly set for the left and right frame, and the top menu frame has what look like the basic elements for logging out and a settings gear, but otherwise, the two main frames are totally blank.  The error from the console still mentions cross-origin issues:

SecurityError: Permission denied to access property "document" on cross-origin object

specifically at "js_includes_navpage15.jsx:50" which is this massive blob of Javascript:

```
(function(e,t){if(typeof define==="function"&&define.amd){define(t)}else{var n=e.parent!=null?e.parent:e;n.k=n.KeyboardJS=t}})(this,function(e,t,n){function r(e,t,n){if(e.addEventListener){e.addEventListener(t,n,false)}else{e.attachEvent("on"+t,function(t){return n.call(e,t)})}}function f(){var e=[];for(var t=a.length;t>-1;t-=1){if(a[t]){var n=a[t];for(var r=0;r<n.length;r+=1){var i=n[r],s=true;for(var u=0;u<i.keys.length;u+=1){var f=i.keys[u];if(o.indexOf(f)<0){s=false}}if(s){e.push(i)}}}}return e}function l(e){if(o<1){return true}var t=f(),n=[],r;for(var i=0;i<t.length;i+=1){var s=t[i],a=false;for(var l=0;l<s.keys.length;l+=1){var c=s.keys[l];if(n.indexOf(c)>-1){break}}if(!a){if(typeof s.callback==="function"){if(!s.callback(e,s.keys,s.keyCombo)){r=false}}if(!u[s.keyCombo]){u[s.keyCombo]=[s]}else{u[s.keyCombo].push(s)}for(var l=0;l<s.keys.length;l+=1){var c=s.keys[l];if(n.indexOf(c)<0){n.push(c)}}}}return r}function c(e){var t=f();var n;for(var r in u){if(u.hasOwnProperty(r)){var i=u[r],s=false;for(var o=0;o<t.length;o+=1){var a=t[o].keyCombo;if(a===r){s=true;break}}if(!s){var l=i!=null?i.length:0;for(var c=0;c<l;c++){if(typeof i[c].endCallback==="function"){if(!i[c].endCallback(e,i[c].keys,i[c].keyCombo)){n=false}}}delete u[r]}}}return n}function h(e,t,n){function r(){if(o&&o.length){var e=a[o.length];if(e.indexOf(u)>-1){var t=a[o.length].indexOf(u);a[o.length].splice(t,1)}}return a}var i=e.toLowerCase().replace(/\s/g,"").split(",");for(var s=0;s<i.length;s+=1){var o=i[s].split("+");if(o.length){if(!a[o.length]){a[o.length]=[]}var u={callback:t,endCallback:n,keyCombo:i[s],keys:o};a[o.length].push(u)}}return{clear:r}}function p(e,t,n,r,i){function s(){if(typeof u==="function"){u()}if(typeof a==="function"){a()}if(typeof f==="function"){f()}if(typeof l==="function"){l()}if(typeof c==="function"){clearInterval(c)}}var o=[0,0];if(typeof i!=="function"){return false}var u=h(e,function(){if(o[0]===0){o[0]=-1}},function(){o[0]=0}).clear;var a=h(t,function(){if(o[0]===0){o[0]=1}},function(){o[0]=0}).clear;var f=h(n,function(){if(o[1]===0){o[1]=-1}},function(){o[1]=0}).clear;var l=h(r,function(){if(o[1]===0){o[1]=1}},function(){o[1]=0}).clear;var c=setInterval(function(){if(o[0]===0&&o[1]===0){return}i(o)},1);return{clear:s}}function d(e){if(e==="all"){a=[];return}e=e.replace(/\s/g,"").split(",");for(var t=a.length;t>-1;t-=1){if(a[t]){var n=a[t];for(var r=0;r<n.length;r+=1){var i=n[r],s=false;for(var o=0;o<i.keys.length;o+=1){var u=i.keys[o];for(var f=0;f<e.length;f+=1){var l=e[f];if(l===u){s=true;break}}if(s){break}}if(s){a[t].splice(r,1);r-=1;if(a[t].length<1){delete a[t]}}}}}}function v(){return o}function m(e,t){i[e]=t}function g(e){if(i[e]){s=i[e]}}[].indexOf||(Array.prototype.indexOf=function(e,t,n){for(n=this.length,t=(n+~~t)%n;t<n&&(!(t in this)||this[t]!==e);t++);return t^n?t:-1});var i={us:{backspace:8,tab:9,enter:13,shift:16,ctrl:17,alt:18,pause:19,"break":19,capslock:20,escape:27,esc:27,space:32,spacebar:32,pageup:33,pagedown:34,end:35,home:36,left:37,up:38,right:39,down:40,insert:45,"delete":46,0:48,1:49,2:50,3:51,4:52,5:53,6:54,7:55,8:56,9:57,a:65,b:66,c:67,d:68,e:69,f:70,g:71,h:72,i:73,j:74,k:75,l:76,m:77,n:78,o:79,p:80,q:81,r:82,s:83,t:84,u:85,v:86,w:87,x:88,y:89,z:90,meta:91,command:91,windows:91,win:91,_91:92,select:93,num0:96,num1:97,num2:98,num3:99,num4:100,num5:101,num6:102,num7:103,num8:104,num9:105,multiply:106,add:107,subtract:109,decimal:110,divide:111,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123,numlock:144,num:144,scrolllock:145,scroll:145,semicolon:186,equal:187,equalsign:187,comma:188,dash:189,period:190,slash:191,forwardslash:191,graveaccent:192,openbracket:219,backslash:220,closebracket:221,singlequote:222}};var s=i["us"],o=[],u={};var a=n!=null?n.keyBindingGroups:[];$j(e.document).bind("keydown.keyJS",function(e){for(var t in s){if(s.hasOwnProperty(t)&&e.keyCode===s[t]){if(o.indexOf(t)<0){o.push(t)}}}return l(e)});$j(e.document).bind("keyup.keyJS",function(e){for(var t in s){if(s.hasOwnProperty(t)&&e.keyCode===s[t]){var n=o.indexOf(t);if(n>-1){o.splice(n,1)}}}return c(e)});r(e,"blur",function(e){o=[];return c(e)});return{bind:{key:h,axis:p},activeKeys:v,keyBindingGroups:a,unbind:{key:d},locale:{add:m,set:g},context:e,frame:t}})
```

Not sure if that's Tridactyl injected or coming directly from our ServiceNow instance.

And in a probably unrelated note, this latest version also still causes Content Security Policy violations to be generated when "default-src 'self'" and report-uri are both set.

**Comment by rpmohn** [comment]
Yes, I also just installed 1.7.3pre677, on FF 58.0.2 (64-bit) on Windows 7 (at work). Here is the new colors without the spinning logo, as nipsy describes above, and the full extent of the console messages now.

![image](https://user-images.githubusercontent.com/4296967/36449824-fec7112e-1659-11e8-904a-d3059a7fd67f.png)

![image](https://user-images.githubusercontent.com/4296967/36449942-5c983fda-165a-11e8-9115-71b6350fdf66.png)

Thanks for working on this! -Ross

**Comment by thejukra** [comment]
Exactly the same SecurityError message as rpmohn posted above (Permission denied .... "document" ...), started to appear on webmail login page after Tridactyl was upgraded to version 1.8.2. This prevents me using webmail account at [webmail.kaisanet.net](https://webmail.kaisanet.net/). Actually, login will succeed, but after that webmail does not load message list and links do not work. Same error message is shown in console after login.

If I disable Tridactyl, webmail works as expected.

This same webmail worked without problems with Tridactyl 1.7.3. The browser is Firefox Quantum 58.0.2 (64-bit). The problem exists on Linux Mint 17.3 and Win 8.1. I have not access to other platforms right now.

Just tought to let you know about this.

**Comment by cmcaine** [comment]
Sorry about that. Olie and I are planning on working on the commandline (where this error comes from) this weekend.

**Comment by rpmohn** [comment]
Any update on this? I'm now getting similar failure, even when using Vim-Vixen, so the criticality has increased for getting this working in my preferred Tridactyl! I'm happy to try out additional changes and post whatever debugging you need, just let me know! Thanks so much -Ross

**Comment by rpmohn** [comment]
Really, this would be quite helpful! Even if I can't use Tridactyl within ServiceNow, if I could just keep Tridactyl enabled without having it crash ServiceNow, that would be huge! How can I help? Thank you -Ross

**Comment by infrascripting** [comment]
Just wanted to confirm that with using Vim-Vixen 0.12, this issue exists with ServiceNow.

**Comment by rpmohn** [comment]
Just re-checked and the issue still exists when using Vim-Vixen 0.12.

**Comment by bovine3dom** [comment]
I'm a bit confused, why are people telling us that Vixen has the same issue? Do we use the same approach?

**Comment by rpmohn** [comment]
I'm telling you that when Vim-Vixen 0.12 is enabled (Tridactyl disabled) ServiceNow websites do not load properly. See [my second post](https://github.com/cmcaine/tridactyl/issues/279#issuecomment-357734478) at the top of this issue for screenshots of what it looks like with Vim-Vixen disabled, and with it enabled. It used to work with Vim-Vixen, but stopped working sometime around Mar 26th (sorry, I didn't capture the before version). 

I'm happy to perform any additional tests and try out patches!

**Comment by cmcaine** [comment]
[tridactyl-1.9.3.zip](https://github.com/cmcaine/tridactyl/files/1929186/tridactyl-1.9.3.zip)

Try this? It's a build of the fix-servicenow branch and fixes the similar issues with #316

Sorry for the delay. I've been wanting to fix this in a more elegant way but haven't spent the time.

**Comment by thejukra** [comment]
@cmcaine  Thanks a million :) This fixed my problem accessing emails at webmail.kaisanet.net. 

Also #316 is fixed at least at winscp.net which loads now normally without endless reload loop.

This is nice!

**Comment by rpmohn** [comment]
Works better for me! Still not loading everything properly, I'll attempt to detail here. First off, I'm running 59.0.2 (64-bit) and it won't allow me to install that unsigned add-on, except I can in Debug Mode, so that seems to be OK. 

With this version, the main content window is populating, but the side navigation menu is still stuck in "Loading", seems to be waiting for an ajax response that it never gets? The error seems to be in this permission denied security error, so is this because I'm running and unsigned add-on, or is it the code? 

![2018-04-20 08_24_13-mozilla firefox](https://user-images.githubusercontent.com/4296967/39050717-5ee05654-4474-11e8-8d36-03b9680c47dc.png)

This is an exciting step forward, what else can I do to help?

![2018-04-20 08_18_35-servicenow](https://user-images.githubusercontent.com/4296967/39050928-2b82b97c-4475-11e8-8f63-6256c4021547.png)

**Comment by Bzly** [comment]
We also use ServiceNow at work, @cmcaine. Might be able to access it at home for you to test, but I'm unsure. Will see what I can do.

**Comment by cmcaine** [comment]
The security error is probably because they have some functions that iterate over all iframes inspecting their contentWindows or something. That's fine for their own iframes, but our one forbids access and they're not catching the exception (because why would there be a foreign iframe on their page).

Easy fixes are:

 - I can try loading the iframe even later at the cost of making clipboard and commandline functions fail if they're called very soon after page load on any page
 - I can add a config option that disables the iframe entirely on selected pages, again incurring a small delay

Fixes that can be done in v2 (where the commandline code will be less bad):

 - Only load the iframe on-demand when we need it

Fixes that they can do:

 - Catch the exception

@Bzly Ta. Might look into it next weekend.

**Comment by rpmohn** [comment]
Maybe begin able to set it as disabled on regexp pattern matched URLs is best for ServiceNow. I think #339 is for this?

**Comment by cmcaine** [comment]
We don't have to disable everything, so it's a bit different.

We'd just be turning off the cmdline and clipboard.

Anyway, if you want this, I'll see about writing it later today.

**Comment by rpmohn** [comment]
Maybe something to try before the weekend? :smiley:

**Comment by rpmohn** [comment]
Good to know. You're probably on their latest version, Kingston, now. We're on Jakarta right now and will upgrade to Kingston later this year.

**Comment by cmcaine** [comment]
[tridactyl-1.9.5.zip](https://github.com/cmcaine/tridactyl/files/1944188/tridactyl-1.9.5.zip)

Try this.

`set noiframeon <space separated array of strings to test for>`

Before inserting the iframe we check that array:

```
    let noiframeon = await config.getAsync("noiframeon")
    let enabled =
        noiframeon.length == 0 ||
        noiframeon.find(url => window.location.href.includes(url)) === undefined
```

If the url includes any of the strings in the array then no iframe is inserted.

**Comment by rpmohn** [comment]
Success! Thank you so much!

**Comment by thejukra** [comment]
Works for me too at webmail I was having problems with previous versions. Thanks!

**Comment by rpmohn** [comment]
More extensive testing this morning in the office. I logged out of ServiceNow, cleared all cached data, and started fresh using tridactyl-1.9.5pre875-an+fx.xpi from the betas page. Looks as if it's back to the loading order problem, even with noiframeon:"service-now.com". The SecurityError location is in the keyboardJS library part. 

![2018-04-25 08_23_34-servicenow](https://user-images.githubusercontent.com/4296967/39246022-64cdc1da-4863-11e8-9234-cff4b752e8d6.png)

![2018-04-25 08_27_55-servicenow](https://user-images.githubusercontent.com/4296967/39245990-4b5c3f24-4863-11e8-9911-b23a53a20b30.png)

**Comment by bovine3dom** [comment]
Merged and released as version 1.9.7.

If you experience this issue, simply `set noiframeon <space separated array of strings to test for>` for the sites you are struggling with.

**Comment by cmcaine** [comment]
If you're using `noiframeon` you need to use 1.9.8 or later to avoid an error reporting loop.

**Comment by cmcaine** [comment]
On Jake's servicenow account I don't need to use `noiframeon`, btw. So maybe different versions are less fussy?

**Comment by kyptin** [comment]
FYI for anybody who's interested, I asked my school's IT department to report this broken behavior to ServiceNow. It looks like they're not interested in fixing it. Here's what they said:

> Thank you again for reporting this behavior.  Unfortunately, outside of documenting the issue here, we do not troubleshoot compatibility issues with browser extensions. Our browser support is only for public releases of the browsers themselves without regard to 3rd party plugins.

Thanks, y'all, for giving me a workaround in Tridactyl.

**Comment by bovine3dom** [comment]
FWIW the recommended command is now `seturl [URL regex] noiframe true`. Means every time you have to add a new site you don't lose all the old ones.

We're still hoping to fix it eventually with lazy insertion of the iframe. #639
