### ISSUE TITLE
Mention Pentadactyl, and VimFx, etc on the AMO page

### ISSUE THREAD

**Issue by davidhedlund** [cmcaine/tridactyl#285]
For the [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/) page:
* [Vimperator](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) is not linked.
* [Pentadactyl](https://addons.mozilla.org/en-US/firefox/addon/pentadactyl/) should be mentioned -- I assume you invented the name Pentadactyl from it.
* [VimFx](https://addons.mozilla.org/en-US/firefox/addon/vimfx/) should be mentioned.
* [Firemacs](https://addons.mozilla.org/en-US/firefox/addon/firemacs/) could be mentioned.

**Comment by bovine3dom** [comment]
Related to #221 and #199

**Comment by davidhedlund** [comment]
@bovine3dom Thank you.
