### ISSUE TITLE
Default search engine set with `set searchengine foo` is ignored

### ISSUE THREAD

**Issue by morganastra** [cmcaine/tridactyl#294]
**Expected**: after doing `:set searchengine duckduckgo`, `:open whatever search query` should navigate to a duckduckgo search page for "whatever search query"

**Actual**: It worked for one search, but then reverted to using google instead.

**Additional info**
- I know this shouldn't matter, but duckduckgo is my default search provider in firefox's settings as well
- I tried rebooting the browser a few times, and doing `:set searchengine duckduckgo` a few times, but I just can't get the setting to stick
- I know this also shouldn't matter either but I've been having this issue on both linux and mac os

**Comment by Koushien** [comment]
Can you running the commands @cmcaine specified in https://github.com/cmcaine/tridactyl/issues/275#issuecomment-357542634?
Namely, `tri.l(browser.storage.sync.get())` or `tri.l(browser.storage.local.get())`? It sounds like your userconfig isn't being synced.

**Comment by bovine3dom** [comment]
You could also try `set storageloc local` in ex mode (the Tridactyl command line) and then re-running the set searchengine command to see if it's a problem with the Firefox sync storage.

**Comment by morganastra** [comment]
I'm not sure if there was a new beta release that fixed this or what, but `set searchengine` just works for me now ¯\_(ツ)_/¯

**Comment by cmcaine** [comment]
I had an issue where the sync database broke and wouldn't get or set any
values.

Eventually Firefox seemed to replace it with a new blank database on its
own. Could have happened to you too.
