### ISSUE TITLE
VIM Find no longer working on Atlassian pages

### ISSUE THREAD

**Issue by wschmrdrNS** [cmcaine/tridactyl#295]
Navigate to https://bitbucket.org/richardpenman/pywhois/overview
Attempt to use / to search

Doesn't work.

**Comment by bovine3dom** [comment]
That's quite strange. `/` isn't anything to do with us, really. There could be a problem with how we whitelist `/` to ensure that it is passed through to the page.

When I get a minute, I need to test it on a vanilla Firefox profile to see if the issue is actually anything to do with Tridactyl...

**Comment by cmcaine** [comment]
I suspect it's not us. Atlassian probably have their own find function
attached to /

**Comment by bovine3dom** [comment]
Same behaviour with Tridactyl disabled. Closing as a bona fide not-our-fault.
