### ISSUE TITLE
Should Tridactyl override new tab page?

### ISSUE THREAD

**Issue by Klesus** [cmcaine/tridactyl#297]
Or rather, should it override it in such an aggressive way?
There's no way of changing it currently. If I want new tabs to open a certain URL or if I have a separate add-on for the sake of new tab, I should be able to customize it how I like it. Customization is what Firefox is best at, Tridactyl IMO shouldn't parent the behavior of Firefox. 

Another thing is what Tridactyl features are even necessary on new tab?
Focusing the awesomebar or the searchbar I imagine provides all functions anyone would want from a new tab page that Tridactyl doesn't functionally improve. Or it could be that I'm missing something. 

I can see usefulness in providing something of a tutorial for people unfamiliar with the add-on, which the new tab page can provide, but there should also be an option to turn new tab page override off.

**Comment by bovine3dom** [comment]
We cannot run Tridactyl at all on the default new tab page.

The main feature we were trying to ensure would work was `gt`, so that if you were flicking through lots of tabs you wouldn't end up trapped on the new tab page.

You can sort of set the new tab page with `set newtab [url]`, but that doesn't work for <C-t> as per #235.

**Comment by bakkerme** [comment]
Is it possible to apply a redirect from the Tridactly new tab page to whatever is set in as the newtab url?

**Comment by Klesus** [comment]
Well, this issue is about sane defaults. Flicking through tabs is definitely a valid point, I'm just not sure how often that actually comes up. Like how many complaints do you get/can you expect from either issue?

Personally when I open a new tab I usually do something with it and not just let it float among my other tabs that actually have something on them. To me that just makes sense and so I assume that *most* other people do the same.

**Comment by cmcaine** [comment]
Would an immediate redirect to another URL satisfice, @Klesus?

We would like to make the new tab page optional so that it doesn't interfere with the default new tab page or other add-ons, but that's not an option with the current WebExtension API (though I suppose we could provide a separate add-on to replace the new-tab page...)

**Comment by bovine3dom** [comment]
Tangential to this issue: it would be nice to keep a changelog on the new tab page, so we can inform the few people who don't follow our commit history religiously of new features.

**Comment by huffstler** [comment]
@cmcaine I was using [this](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/) before it was clobbered by the Tridactyl Tab-page. Why bother reinventing the wheel, unless you have improvements in mind?

Currently I have 'T' open the webpage that the above extension was redirecting me to originally.

    :bind T open https://urlgoeshere.com

**Comment by bovine3dom** [comment]
I think most people have been placated now that #235 is fixed...

**Comment by cosmojg** [comment]
Is there any way to disable the new tab override via configuration options? Personally, I prefer the ability to use the default ```about:newtab``` over a flawless ```gt``` experience.

**Comment by glacambre** [comment]
No, there isn't (this is a webextension API limitation). There is more information about this in https://github.com/tridactyl/tridactyl/issues/384.

**Comment by huffstler** [comment]
@cosmojg this should get you mostly there: 

![image](https://user-images.githubusercontent.com/9092204/57477361-854a9900-7266-11e9-94b2-1d60f50a1bbe.png)

You'll have to hit `Ctrl+t` but it keeps your fingers on the keyboard at least.
