### ISSUE TITLE
Tridactyl do not work in Firefox reader mode

### ISSUE THREAD

**Issue by mayanksuman** [cmcaine/tridactyl#299]
Tridactyl (version 1.7.3) shortcuts do not work in reader mode in Firefox 58. I have checked movement shortcuts (h/j/k/l) and tab navigation shortcut (gt). Neither of them is working.

Operating system: Debian Testing 64 bit
Web Browser: Firefox 58
Tridactyl Version: 1.7.3

**Comment by johnbeard** [comment]
Duplicate of #102 - this is currently a limitation of the Web Extension API.
