### ISSUE TITLE
Parser discussion

### ISSUE THREAD

**Issue by cmcaine** [cmcaine/tridactyl#3]
https://github.com/cmcaine/tridactyl/commit/ceb6e32bbdc0e4122775b1b636cfc4ffa09a97d6

> > Converting keys[] to a string will produce odd results for special keys.
> >
> > the .key value of backspace is "Backspace", for example.

> It mostly works OK at the moment: the entire key is dropped if it doesn't match something, in one go.
> 
> The main problem is that it will stop people binding things to some capital letters (e.g. S for Shift).
> 
> The current method has the added bonus that you can type the key out - "B a c k s p a c e".
> 
> 
> I'm unsure how much of this should go in Tridactyl, and how much should be in the keyboard API. It might make more sense if the keyboard API sent keycodes?
> 
> Otherwise, we could fix this by prepending a special character to any .key with length greater than 1, e.g something in Unicode like 🄰.

Having "Shi" be kept because it could map to "Shift" is clearly bonkers. Prefixing with an untypeable character is OK, but should be done by API consumers, not the API.

Keyboard API will send a shallow copy of the keyboardevent, but `.code` is not appropriate for finding 'Shift' and friends: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

We'll just want to drop all the modifier keys anyway: we don't want users to map Shift or Control on their own, we just want them as modifier keys (which is detected with e.g. keyevent.ctrlKey property).

Arrow keys, backspace, etc. we will want to be mappable.

To think about:

 - prompt_toolkit has a vi mode, maybe check it out
 - How do we want to allow users to map to special keys (vim-style names and/or js `.key` names)?
 - If we want to introduce escapes for modifier keys in the mappings and keys or if we want to move away from a string based approach

**Comment by cmcaine** [comment]
> >We'll just want to drop all the modifier keys anyway: we don't want users to map Shift or Control on their own, we just want them as modifier keys (which is detected with e.g. keyevent.ctrlKey property).

> Dumb, but for me a very important question: why don't we want user to map Shift or Control on their own?
> 
> I have already come across special use cases (especially when one wants something cross platform), when exactly mapping modifiers was the only or at least the best solution.

When ctrl+s is pressed, browsers generate a ctrl keydown event, then a keydown event with `.key === 's'` and `.ctrlKey === true`, then keyup events for each.

If the user was allowed to bind ctrl with no modifier then they would face the surprising situation of Ctrl+s triggering the maps for both Ctrl and Ctrl+s.

This can be solved, but it would complicate the parser significantly by introducing a notion of timeliness.

**Comment by dumblob** [comment]
>If the user was allowed to bind ctrl with no modifier then they would face the surprising situation of Ctrl+s triggering the maps for both Ctrl and Ctrl+s.

That's totally OK to leave the responsibility up to the user. It's still highly useful. What is though not OK is to completely disable this.

>This can be solved, but it would complicate the parser significantly by introducing a notion of timeliness.

We don't need to solve it (or at least not right now). We just shall not disallow it completely.

**Comment by cmcaine** [comment]
We'll consider letting modifiers be mapped on their own but:

 1. this is not the behaviour in vim
 2. this is a niche use case, so if forbidding it makes the parsers easier to write, we'll probably forbid it. In that case, you could write a PR for the feature when the project is more mature.

Thanks for the interest.

P.S. [imperatives often sound rude in English](https://english.stackexchange.com/questions/301695/is-it-rude-to-say-commands-or-imperatives-without-saying-please#301708).

**Comment by dumblob** [comment]
> this is not the behaviour in vim

That's true and it's fine to not support it. What I meant with "shall not" was to proactively disable this use case (I have imagined a "filter" on keys, i.e. more code to write; but if it's vice versa, i.e. actually writing less code, then it's a different story).

>this is a niche use case, so if forbidding it makes the parsers easier to write, we'll probably forbid it. In that case, you could write a PR for the feature when the project is more mature.

Usually it is a niche, but where the issues pop up is e.g. a multiplatform cross-product compatibility with the settings (especially when it comes to user input). And yes, I've already got the idea to remap keys in a web browser (hint: universal web based kiosk/bank/ticket terminals running on different systems/HW where the user interface is made by a subsupplier who has a limited information about the terminal).

>P.S. imperatives often sound rude in English.

Let me apologize for anything which crossed the border. I'm always learning - could you please help me and point out the bigger picture (e.g. a cultural/territorial context) in which the statements I wrote are perceived rude? Thank you.

**Comment by cmcaine** [comment]
I don't understand your suggested use case, but we can keep your request in mind as we develop the parser :)

If it's easy to support, we'll do it.

> Let me apologize for anything which crossed the border. I'm always learning - could you please help me and point out the bigger picture (e.g. a cultural/territorial context) in which the statements I wrote are perceived rude? Thank you.

No need to apologise!

> What is though not OK is to completely disable this.

> We just shall not disallow it completely.

These are imperative and possessive statements about a project that you're not a significant contributor to. They come across as a bit bossy.

Instead you could either express your opinion ("I think it's more important that users can map Ctrl than that they might get confused by Ctrl+s triggering two maps.") or ask a question ("Surely if the user doesn't bind any Ctrl+X combinations it won't be confusing?").

**Comment by dumblob** [comment]
>a project that you're not a significant contributor to

Then I would advocate for adding this information to the `readme.md` to not confuse anyone (usually it's assumed, that the person doesn't need to be any contributor at all, much less a significant one, but rather that the person might know how to get out of a [local extremum](https://en.wikipedia.org/wiki/Maxima_and_minima ) disregarding any online footprints about her/him/it if they exist).

But back to the topic :wink:.

>If it's easy to support, we'll do it.

Sounds good to me. Thanks.

**Comment by cmcaine** [comment]
Nah, the potential problem isn't that you're not a contributor, it's that you used imperative and possessive language while not being a contributor. Your comments are very welcome and you've pointed out a requirement we were not considering.

I just wanted to point out that your choice of words was a bit unusual and could be construed as rude. I understand that lots of other languages (e.g. French) use the imperative more than English speakers tend to.
