### ISSUE TITLE
Make it possible to not URI-encode search query string?

### ISSUE THREAD

**Issue by zcesur** [cmcaine/tridactyl#300]
I would love to be able to use the Wayback Machine as one of my search keywords, but my URIs are being percent-encoded (#131) which prevents their search engine from working properly. Perhaps we could add the option to disable this?

> https://web.archive.org/web/*/https://github.com/cmcaine/tridactyl
> https://web.archive.org/web/*/https%3A%2F%2Fgithub.com%2Fcmcaine%2Ftridactyl

**Comment by bovine3dom** [comment]
This is quite a reasonable request.

I'll have to do some thinking about how to best expose it. Perhaps a flag on `searchsetkeyword`?

**Comment by cmcaine** [comment]
We might be able to work it out automatically from the location that the insertion/replacement happens.

For all of our existing defaults it's safe not percent encode if the query string isn't actually in the query part of the URL. (cnrtl and wikipedia search are the only ones that aren't queries and they both accept non-encoded strings)

cnrtl doesn't like slashes, but it doesn't like them if you encode them either.

Anyway, this is probably a good enough heuristic and it means the users don't need to think about it.

We can test with

```
if (searchURL.contains("%s") && (new URL(searchURL)).search.contains("%s") || (new URL(searchURL)).search != "") {
    query = encodeURIComponent(query)
}
// ...
```
