### ISSUE TITLE
FF59: browser shortcuts no longer work if the corresponding key is bound

### ISSUE THREAD

**Issue by wavexx** [cmcaine/tridactyl#302]
I'm trying FF59 beta. It seems now that any key which is bound by tridactyl will prevent any "Ctrl/Alt/Shift" combination to work.

For example, "Ctrl+L" does not focus the location bar any longer, because "l" is bound. By removing the mapping, the FF shortcut starts to work again. 

Maybe now the extension needs to forward manually the event to the browser somehow?
The same issue appears in Vimium-FF, so this is not something specific to tridactyl.

And since most of the letters are obviously bound, many FF shortcuts simply don't work anymore.

**Comment by cmcaine** [comment]
Cannot reproduce in Firefox 58, 59 or 60. I don't think this is tridactyl.

Furthermore, we don't interfere with any keyevent that has a non-shift modifier attached to it at the moment.

**Comment by wavexx** [comment]
On Mon, Feb 05 2018, Colin Caine wrote:
> Cannot reproduce in Firefox 58, 59 or 60. I don't think this is tridactyl.

Which platform?

I'm on linux, FF 59b4 built with GTK3.
FF58 works.

**Comment by cmcaine** [comment]
Linux. Firefox stable from arch repo, beta 59b6 and nightly 60 from Mozilla
website.

On 5 Feb 2018 16:37, "wavexx" <notifications@github.com> wrote:

On Mon, Feb 05 2018, Colin Caine wrote:
> Cannot reproduce in Firefox 58, 59 or 60. I don't think this is tridactyl.

Which platform?

I'm on linux, FF 59b4 built with GTK3.
FF58 works.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cmcaine/tridactyl/issues/302#issuecomment-363141274>,
or mute the thread

**Comment by wavexx** [comment]
On Mon, Feb 05 2018, Colin Caine wrote:
> Linux. Firefox stable from arch repo, beta 59b6 and nightly 60 from Mozilla
> website.

I'll try to fetch the nightly 60, maybe this was already fixed.

**Comment by cmcaine** [comment]
I suspect this is another addon's fault rather than Firefox or Tridactyl.

**Comment by wavexx** [comment]
I tried with FF60 nightly and I cannot reproduce the issue either. I didn't try with a new profile on FF58b4 yet as it's on another laptop I have, but either way if it's not present in the latest version there's no point in keeping this open. Profiles are synced, so at least in theory the configuration between the two systems is identical.

Sorry for the noise!
