### ISSUE TITLE
AMO removing support for beta builds

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#307]
We therefore need to have a special switch in our build system that, when making a beta build, adds an auto update URL. We will need to host the builds outside of the AMO.

We should probably link to the builds from the new tab page and help page. I'm not sure if we would be allowed to link to it from the AMO.

**Comment by cmcaine** [comment]
Need to do this in the next 48h, probably.

**Comment by IsaacKhor** [comment]
I see two solutions: 

1. Create a separate Tridactly-BETA version on AMO
2. Use the proposed `update_url` in manifest and move beta builds into a script that generates the required update manifest

**Comment by bovine3dom** [comment]
We'll go for option 2. We can't automate proper releases on the AMO (at least, not easily).

Versions on the AMO aren't allowed update URL, so the `set channel` wouldn't work on the AMO.

**Comment by bovine3dom** [comment]
The axe has now fallen, so we should look into this further.

**Comment by cmcaine** [comment]
See https://tridactyl.cmcaine.co.uk/betas/

https://developer.mozilla.org/en-US/Add-ons/Updates#Manifest_Structure describes the format of updates.json

per db5dae64cd5c365f5b4ccc9b05d2f99067ff08cc, we just need a bash script on the buildbot to cp the web-ext-artifact and sed the updates.json

ublock example: https://github.com/gorhill/uBlock/blob/master/dist/firefox/updates.json

We'll also need to sed the manifest before signing to add the update_url line (this should be done in scripts/sign)

**Comment by bovine3dom** [comment]
We should make the web server sort by date modified by default. Currently, the oldest file is shown first due to our naming convention.

https://caddyserver.com/docs/browse

Alternative proposal: change our versioning to count downwards towards zero.

**Comment by cmcaine** [comment]
Easier than finding and editing the default template is just adding a symlink to latest, so we could just do that.

**Comment by bovine3dom** [comment]
Automatic updates added in in 7d3fb87d5ea032c45b65c6f7d08595b53fad1ce7.

Script could probably be tidied up a bit.
