### ISSUE TITLE
Add excmd to switch between Vimperator and simple hinting

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#308]
Should set up hintchars sensibly.

**Comment by glacambre** [comment]
Is an excmd necessary?
I was thinking that hintchars could be automatically set to `0123456789` whenever the user does `:set hintfiltermode vimperator`. I can't think of any situation where the user might want to keep using letters for their hints while using vimperator hints.

**Comment by bovine3dom** [comment]
1) we don't want people to lose their lovingly crafted hintchar order if they change an unrelated setting

2) maybe people want hintchars to be capital letters, which would work with both modes (if we supported it - not sure we do)

3) I don't think `set blah` should change anything but blah, so I thought a helper command would be the best compromise.

I think having a separate filterchar setting for Vimperator mode would be perhaps the best solution.

**Comment by bovine3dom** [comment]
Duplicate of #265 :(
