### ISSUE TITLE
Infinite reload loop on some websites

### ISSUE THREAD

**Issue by Chouhartem** [cmcaine/tridactyl#316]
Hello there,

Some websites, like https://www.lecturel.com/clavier/mots-par-minute.php or http://www.noelshack.com/2018-08-5-1519398165-citrouille.jpg *infinitely loop* on Firefox 58.0.2 on Archlinux, kernel 4.15.3-2 (64bits) with the version of _Tridactyl_ shipped within firefox addons.

There follow logs from firefox console on some examples: https://paste.isomorphis.me/tMM&raw

And here are logs from the debbug console of tridactyl on similar examples: https://paste.isomorphis.me/weA&raw

What's weird is that the English version of Lecturel (words per minute) works perfectely fine.

This behaviour also appears in “private browsing” mode.

Regards.

**Comment by cmcaine** [comment]
The first site has some JS intended to stop it from being used in iframes or something? It's pretty daft.

Anyway, this is the problem:

```js
if (parent.frames.length!=0) 
    parent.location.href=location.href
```

As with #279 the solution is to insert the iframe a bit later.

Assuming that's the issue with example 2 as well.

Todolisted.

**Comment by Chouhartem** [comment]
Thanks :+1:

**Comment by thejukra** [comment]
This seems to be happening also at [winscp.net](http://winscp.net).

**Comment by madduck** [comment]
trademe.co.nz has the problem too.

**Comment by Chouhartem** [comment]
It works now, maybe close this too?

Thanks :-)
