### ISSUE TITLE
Open new private window command

### ISSUE THREAD

**Issue by Bazalia** [cmcaine/tridactyl#317]
I wonder if there is an open private window command similar to that to winopen. If not would it be possible to add one? Also using hinting to open a new private window would be nice too.

**Comment by bovine3dom** [comment]
`winopen -private`, which I now realise is undocumented. There isn't any hint mode for it, yet, but I don't believe anyone else has asked.

**Comment by IsaacKhor** [comment]
Should we add a `hint -P` (private) option? I don't see why we shouldn't.

**Comment by gsbabil** [comment]
@bovine3dom

> `winopen -private`, which I now realise is undocumented.

Thanks for pointing out the `winopen -private` option. Is there a
default keyboard shortcut assigned to it?

If not, may be we should assign one as default. Is patching
`config.ts` still the preferred way to adding default shortcuts?

I'm still using the `tri.config.get("nmaps")` to review the current
bindings. Is there any other way to see them?

Thank you.


@bovine3dom @IsaacKhor

> Should we add a `hint -P` (private) option, or something similar?

I think this could be very useful given that the `hint`ed link would
open in the private window.

On the same train of thoughts, it might also be useful to a
hint-mode to open targets in different Firefox context i.e. Work,
Personal etc.

Thank you.

**Comment by bovine3dom** [comment]
> Thanks for pointing out the winopen -private option. Is there a
> default keyboard shortcut assigned to it?
> 
> If not, may be we should assign one as default. Is patching
> config.ts still the preferred way to adding default shortcuts?

No, but I am not sure we need a bind. We don't have many keys left. Which keys did you have in mind? Yes, `config.ts` is still the home of the default settings.

> I'm still using the tri.config.get("nmaps") to review the current
> bindings. Is there any other way to see them?

`:get nmaps` now works in a pinch by dumping the config in the command line, but the debugging approach has a much prettier JSON formatter.

**Comment by gsbabil** [comment]
@bovine3dom

Thanks for the prompt reply.

> No, but I am not sure we need a bind. We don't have many keys
> left.

I understand. Thanks.

> Which keys did you have in mind? Yes, config.ts is still
> the home of the default settings.

I'm currently using `,w` to open a new window, and `,wp` to open a
new _private_ window, where `,` is the preferred `leader` key.

On that note, do we have any setting to set the `leader` or
`localleader` keys in Tridactyl. In Vim, this is usually achieved by
the following:

```
  let mapleader = ","
  let maplocalleader = ","

  nnoremap <localleader>l :command-name <cr>
```

> :get nmaps now works in a pinch by dumping the config in the
> command line, but the debugging approach has a much prettier JSON
> formatter.

Thanks for the `:get nmaps` hint and it works you mentioned.
However, I agree with you that the `tri.config.get("nmaps")`
approach indeed produces much more readable output.

Thank you.

**Comment by IsaacKhor** [comment]
Can you close this issue if you have no more questions? It helps to reduce the clutter.

**Comment by gsbabil** [comment]
@IsaacKhor, @bovine3dom 

> Can you close this issue if you have no more questions? It helps
> to reduce the clutter.

Thanks. I have no more questions. But I don't seem to have
permission to close the issue.

May be @Bazalia (opened the issue) would have to do it.

Thank you.

**Comment by Bazalia** [comment]
Just one last question regarding the hinting. Will the open in private window be added?

**Comment by bovine3dom** [comment]
@Bazalia I've added it to the `hintprivate` branch but can't test it right now.

**Comment by bovine3dom** [comment]
> Should we add a hint -P (private) option, or something similar?

@Bazalia, @IsaacKhor: added as `hint -w` and `hint -wp` in c042fd1 and bound to `;w` and `;W`
