### ISSUE TITLE
Opening new tab does not bring focus to search bar

### ISSUE THREAD

**Issue by nikitavoloboev** [cmcaine/tridactyl#327]
I believe that before it did but some Firefox update broke that.

**Comment by glacambre** [comment]
Hi, what Tridactyl and Firefox version are you using and how are you opening the new tab page? I can't reproduce your issue on the beta versions and Firefox 60 now matter how I open the new tab page (be it with `:tabopen`, `<C-t>` or by clicking the "+" on the right of the last tab).

**Comment by nikitavoloboev** [comment]
It is fixed now.
