### ISSUE TITLE
Display changelog on newtab page

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#331]
Probably in a little drop down box. Maybe have it change to a slightly different colour until it is read and dismissed each version? I think we communicate new features very badly right now.

**Comment by bovine3dom** [comment]
Tangentially related: add `npm run build-debug` and make it print time of build to the new tab page, or perhaps echo some random words to the console and also to the new tab page, to ensure that web-ext is running the right code.

**Comment by cmcaine** [comment]
web-ext can break in ways that that won't detect, bizarrely.

**Comment by IsaacKhor** [comment]
I think there are several solutions to this:

1. Open a new tab when a new version is detected with the changelog. The problem with that is that every time this happens with other extensions I close the tab without even thinking about it.
2. When we add the modeline, we can show a new version notification there.
3. Put changelog on newtab and highlight new versions (what you proposed)

**Comment by bovine3dom** [comment]
Drop down box added in 5ef46f1.

Highlighting it until it has been read is beyond my hacky sed skills.

Amusingly, Tridactyl doesn't provide a hint for it.

**Comment by cmcaine** [comment]
Just give it an empty onclick attribute.
