### ISSUE TITLE
How to enable hintfiltermode vimperator?

### ISSUE THREAD

**Issue by mgeier** [cmcaine/tridactyl#335]
I'm using Tridactyl 1.8.2 and I'm not able to select the "vimperator" hint mode.

I tried typing this:

    :set hintfiltermode vimperator

... but there is no visible feedback and the hinting doesn't change.

How can I select it?

**Comment by bovine3dom** [comment]
You have half of the settings needed. The other is hintchars, e.g. `set hintchars 5432167890`.

We were going to add a helper command to toggle between the two modes but forgot.

**Comment by mgeier** [comment]
Thanks @bovine3dom for the quick answer! That's it!

Thanks a lot for this feature, that's one of the most important ones for me!
