### ISSUE TITLE
 Make tab opening behaviour less consistent (revert 259e4f1...)

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#342]
I am opening an issue because I don't like the change introduced in [259e4f1...](https://github.com/cmcaine/tridactyl/commit/259e4f182fdc3ea65ef00490e3dda46e02c09a39) :) At least I think this commit is the reason, I haven't gotten around to bisecting it, and I waited a while to whether friends of mine comlained about the same behaviour.

I recently noticed that when opening tabs quickmarks they tend to open all over the place (although always as a group together), when I don't open them from the newtab page. The quickmarks are then also often opened in reversed order. Since quickmarks with multiple urls were implemented as a very thin wrapper only I can imagine that the above commit might be the reason for them to be opened not at the end of the tab list, but in my active tab and in reversed order by always being opened from the active tab.

**Comment by cmcaine** [comment]
Quality issue title :)

Quickmarks behaviour sounds like a bug, so I'll have a look at that.

Do you dislike the opening after current tab behaviour in the non-quickmarks case as well? Is it just that you prefer the new tab to go to the end of the list or is there some other issue?

**Comment by behrmann** [comment]
Well, I do tend to live a bit in the past and I have also set
`browser.tabs.insertRelatedAfterCurrent` to `False`, to always open tabs at the
right end of the tab bar.

I guess it's not possible with webext to just read the value of
`browser.tabs.insertRelatedAfterCurrent`, but if not to burdensome I'd like all
my new tabs (including quickmarks) to just always open at the end of the tab
bar and would a appreciate a config for that.

My tab bar is basically like a stack that grows to the right and that I always
try to prune to the left, so tabs opening somehwere in the middle always screws
a bit with my workflow :)

**Comment by behrmann** [comment]
Also, I just experienced this again. With the last tab active (tab 7/7)
I opened the tridactyl issue page (t, <tab>, <tab>) and it opened as the
fourth tab (tab 4/8). I guess this is also not the intended behaviour. I
am currently running the current 1.8.2pre700.
I think the new tabs might actually be gravitating towards being
inserted behind tab 4 for some reason.

If I can help debugging this, I'll gladly provide logs.

**Comment by cmcaine** [comment]
Fixed. `set tabopenpos last` and `set relatedopenpos last` are what you want, behrmann.

The bug you identified is fixed too.

**Comment by behrmann** [comment]
Thanks a lot!

**Comment by behrmann** [comment]
Did anything change about this? Suddenly my tabs from quickmarks open at seemingly random positions again.

**Comment by bovine3dom** [comment]
@behrmann yes, Mozilla killed the beta builds so you've probably been reverted to version 1.8.2, which didn't contain this fix.

You can download the beta builds from tridactyl.cmcaine.co.uk/betas but they don't auto update and don't share setting with the builds from the AMO.

**Comment by behrmann** [comment]
Ah, that explains why everything worked again once I switched to the
beta. :)

I'm currently redoing my config in the beta.
