### ISSUE TITLE
A way to use bépo layout ?

### ISSUE THREAD

**Issue by bepolymathe** [cmcaine/tridactyl#346]
Hi,

I use bépo keyboard with this Vim "adaptation" --» http://bepo.fr/wiki/Vim
Is there is a way to do the same this with tridactyl.
Thanks for your works !

**Comment by bovine3dom** [comment]
Ouais, if you are willing to put some work in; everything in normal mode can be rebound with `bind [key] [command]`.

The easiest way would be to look at the keys ("nmaps") in https://github.com/cmcaine/tridactyl/blob/master/src/config.ts, so you can see the commands used.

For example, "j": "scrollline 10", tells me that I should do `bind t scrollline 10`.

We don't have any easy way to share or import configurations yet, but once that is done, we could make a wiki or have some default layouts built in, and your bépo configuration would be most welcome.

**Comment by bepolymathe** [comment]
Oui... Thank you for the answer.
I actually asked myself the question simply for the up/down in the page. Like this :

"c" (left)
"t" (down) 
"s" (up) 
"r" (right)

the problem is that the impacted keys are a major use... but you're right, a complete remapping would be more useful...
I'm going to try to find the time for a proposed amendment... I'm also going to share the idea on the francophone "bépo" list...
I'll let you know.

**Comment by bovine3dom** [comment]
@bepolymathe we now support rc files, see `help source`, or the example tridactylrc in the root of this repository.

Unfortunately, we don't support converting your current settings to an rc file yet - that would be somewhat more work - so you'll have to do it manually.

**Comment by bovine3dom** [comment]
@bepolymathe have you seen `keymap`? I've just added a wiki page and it would be cool if you could add a section on the bepo layout :)
