### ISSUE TITLE
Key clobbering in Ff 59

### ISSUE THREAD

**Issue by polyzen** [cmcaine/tridactyl#348]
Shortcuts like `ctrl-l` (focus address bar) and zoom control generally do not work with Tridactyl (1.8.2) enabled in Ff 59. Oddly the issue is not affecting this issue tab.

The Browser Console shows `scrollpx 50 Array [ 50 ]` when entering `ctrl-l` in affected tabs.

**Comment by polyzen** [comment]
Similarly, `alt-b` no longer expands the Bookmark Menu, but shows the buffer cmdline.

**Comment by IsaacKhor** [comment]
I can't reproduce on the latest build and ff59; can you try it on a fresh profile and the steps to reproduction?

**Comment by polyzen** [comment]
No +1's, will reopen if more details can be found.
