### ISSUE TITLE
History completion source doesn't show as many options as possible

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#349]
Here's how to reproduce this issue:
- Start with a clean profile
- Load Tridactyl in about:debugging
- Open a new tab with `<C-t>`
```
:tabopen example.org
:tabopen wikipedia.com
:tabopen this is a test
:open
:tabopen mozilla
```
Now open the command line with `t`. You should have three completion options: "Example Domain", "mozilla - Google Search" and "www.wikipedia.org". Note that the "this is a test" search is missing.
Then press "e" and you'll be presented with a few more options, among which the "this is a test" search.

If you can't reproduce this issue by following these steps it might be due to Google not redirecting you to the same domain as me.

**Comment by cmcaine** [comment]
Before you type a character we just use the output of the topSites() api.

For most users I suspect that this API will give enough items. If you think it's worth fixing you could just pad it with some results from history.
