### ISSUE TITLE
"OS" key is passed through to help page

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#354]
When you press the windows/meta/mod key (the one recognized as an "OS" keydown event in JS), the help page detects it and selects the search input at the top of the page, which makes Firefox go to the top of the page.
This is annoying because in i3 you frequently press the mod key to move your windows around.

**Comment by rscircus** [comment]
This seems to be related to https://github.com/cmcaine/tridactyl/issues/162#issuecomment-360026586 @Koushien

**Comment by glacambre** [comment]
You're absolutely right, thanks for pointing that out!
