### ISSUE TITLE
`hint -c` now seems to click the first link always

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#357]
`hint -c [class*="expand"],[class="togg"]` on e.g. https://www.reddit.com/r/programmingcirclejerk/comments/6iyk80/the_main_blocking_issue_other_than_motivation_is/ now clicks the first link. It used to hint all of the comment toggle tags.

**Comment by glacambre** [comment]
Looks like my "automatically select element if they all point to the same link" PR is to blame. I'll try to find out why.

**Comment by glacambre** [comment]
It's because all the elements have the same "javascript:void(0)" href. Fixing it right now.
