### ISSUE TITLE
Unreliable shortcuts due to shortcuts not being browser-wide.

### ISSUE THREAD

**Issue by oxysoft** [cmcaine/tridactyl#359]
This extension would be absolutely amazing if only Firefox didn't shit itself with keyboard shortcuts.

From my understanding, this is most likely not a problem with the extension, but more with the fact that we currently cannot define browser-wide shortcuts with webextensions. The rendered page most likely needs to have focus in one way or another for Tridactyl shortcuts to work, and this is a major pain in the ass as 1/4 of the time, I have to wrestle with the escape key or F6 when the URL bar has focus in order to hopefully move focus back to the page. I hope the situation will change with webextensions, because it's very cumbersome as it stands.

In the time being, I think it would be productive to add a way to at least see that Tridactyl will receive shortuts if they are pressed with an indicator in the bottom-left/bottom-right corner. Wrestling would still take place, but at least we wouldn't be in the dark about it. Why not take down two birds with one stone and make that indicator display further information as well, such as the current mode (e.g. normal mode, '`g`  key mode`, hint mode, etc.) If this is to be added, it must be very non-intrusive and discreet. Perhaps a thin little bar with a few characters, and the respective character of the current mode would be lit up or something, with no character lit up meaning that NO shortcut will go through if they are pressed!

Thanks, Tridactyl is awesome by the way and I appreciate the efforts to ditch the mouse.

**Comment by IsaacKhor** [comment]
We are currently in the middle of writing said ui, and will welcome suggestions for it. The plan right now is to basically reimplement vimperator’s completion in this extension but with modern frameworks like inferno.

**Comment by bovine3dom** [comment]
I've found that I'm using the default Firefox shortcuts (^t, ^Tab) more and more because ours are not totally reliable, especially when flicking through lots of tabs which haven't loaded. That is probably a bad sign.

**Comment by bovine3dom** [comment]
#109 is somewhat related to this: if you do `set csp clobber`, you'll get slightly worse security against cross-site scripting attacks, but Tridactyl will then work on pretty much every page that Mozilla allows us to.

**Comment by bovine3dom** [comment]
Closing in favour of https://github.com/cmcaine/keyboard-api, which we haven't forgotten about.

**Comment by bovine3dom** [comment]
`fixamo` helps a bit in the latest betas : )
