### ISSUE TITLE
Unpredictable commanline history

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#362]
The behavior of the command line history is unintuitive.
Here's an example, on whatever page do this:
```
:tabopen<CR>
fh
:back<CR>
:<Up>
```
The command line will be filled with `back`, which is to be expected.

However, if you do this:
```
:tabopen<CR>
:tabprev<CR>
:<Up>
```
Then the command line will be filled with `tabopen`, which is not what I expected.

It looks like the command line history is only updated for some tab switches and some page changes events but not always.

**Comment by bovine3dom** [comment]
```:tabopen<CR>
:tabprev<CR>
:<Up>```

is not reproducible for me - I get tabprev as I would expect.

**Comment by glacambre** [comment]
Did you also do `:tabopen<CR>` before `:tabprev<CR>`?

**Comment by bovine3dom** [comment]
Yes, I did, I don't know how I didn't manage to copy and paste that bit in the message...

**Comment by glacambre** [comment]
I indeed can't reproduce this issue when using `bbc.com` as newtab page. Looks like this only happens on Tridactyl's default newtab and help pages which might be normal since Tridactyl is loaded differently on these pages.

**Comment by bovine3dom** [comment]
I was using the default new tab page and couldn't reproduce :S

**Comment by glacambre** [comment]
Weird, on another computer with a similar setup to the one I used this morning these steps:
```
:tabopen<CR>
fh
:back<CR>
:<Up>
```
Fill the command line with `tabopen`.

**Comment by glacambre** [comment]
I can't reproduce this bug anymore on latest beta.
