### ISSUE TITLE
Opening the command line scrolls the web page to the end (Bottom) 

### ISSUE THREAD

**Issue by davidsierradz** [cmcaine/tridactyl#363]
OS: Manjaro i3
Firefox: Dev-edition 60.0b4
Tridactyl: HEAD

**Comment by glacambre** [comment]
Doesn't happen on my computer. Which website does this happen on? Are you sure you don't have another addon loaded with Tridactyl that might be responsible for this?

**Comment by davidsierradz** [comment]
Yeah sorry, the offending addon is [Owl - Dark Background](http://owl.sidhant.io/) when the site is in dark mode.
