### ISSUE TITLE
Question: Custom command in command mode

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#364]
Hi. 

I would like to know if at the current stage of development there is a way of binding custom commands for use with command mode. I know we can bind custom commands in normal mode, but I was looking for a way we could emulate a most used feature (for me) in vimperator, like:

**command:** customcomm
**action:** tabopen http://myurltest.com

In vimperator rc I would just include the following line: 
_command! customcomm tabopen http://myurltest.com_

I searched for this in Issues but didnt find it. I hope you dont bother if I ask it again here. 

Thanks in advance.

**Comment by bovine3dom** [comment]
It's just called `command` :)

`help command` for more info.
