### ISSUE TITLE
Configuration does not work as expected due to Mozilla rolling version back to stable (was theme regularly reverts back)

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#368]
I've set the dark theme via `set theme dark` as documented on the main page, but i regularly reverts back and currently `set theme dark` simply does nothing. Maybe related to this, I have recently lost all my search keywords, that were not backed by builtin values in `searchurls` in `config.ts` and my values for `tabopenpos` and `relatedopenpos` don't seem to be honored. 

Is there a way to simply "factory reset" the config and start over?

**Comment by behrmann** [comment]
It does work on the beta, though.

**Comment by glacambre** [comment]
Mozilla recently decided to silently roll every beta extension back to their latest stable release. If you want to use the beta version, you'll have to get it here: https://tridactyl.cmcaine.co.uk/betas

You can factory reset tridactyl with `:sanitize commandline tridactyllocal tridactylsync`. Be warned that this is a bit strong and you'll probably need to restart the extension/firefox for it to work properly.

**Comment by behrmann** [comment]
I changed the title so that people have an easier way of finding this.

**Comment by behrmann** [comment]
Thanks a lot for the quick answer, @glacambre!

**Comment by bovine3dom** [comment]
#365 probably related.
