### ISSUE TITLE
Disable automatic focus on first input

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#369]
I tried the possible values of `gimode`, but is there a way to not automatically focus the first input field on a site? I find myself regularly type my movement into the first input field on any page and this is more of a pain as the few times, where it is useful, can offset.

**Comment by glacambre** [comment]
Tridactyl doesn't automatically focus any input - websites are responsible for this. We have a PR to fix this ( https://github.com/cmcaine/tridactyl/pull/326 ), it just needs to be merged :)

**Comment by behrmann** [comment]
Ah, I do hope your PR gets merged soon, then. :)

I just noticed, that this started after switching to tridactyl from pentadactyl. Closing since it is a duplicate of #266
