### ISSUE TITLE
Page elements are drawn overtop of Command Bar

### ISSUE THREAD

**Issue by huffstler** [cmcaine/tridactyl#375]
Picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/9092204/38620061-94c31c4e-3d6b-11e8-9450-35eaa532e013.png)

Running Firefox Nightly: 61.0a1 (2018-04-11) (64-bit)

If you hover over an element on the page that has an animation, the bar will be redrawn correctly, but once the animation stops it is "sent to the background again". I put that in quotes, because that's my description of the action. I'm not sure what exactly is happening on the page.

It's important to note, this also happened with the vimium addon as well. So it's not _only_ you guys.

Kinda seems like a Firefox bug at this point. They might have enabled a new feature with Stylo, or webrender or something on nightly. I can do some more research into that.

**Comment by glacambre** [comment]
I notice that you have a specific firefox theme. Does this also happen with the default theme? Also, do you have other addons enabled?

**Comment by huffstler** [comment]
My apologies for not including that previously.

After turning off all extensions except Tridactyl, the issue still persists.

![image](https://user-images.githubusercontent.com/9092204/38621911-f3d2c47e-3d6f-11e8-882f-1485770474d5.png)

**Comment by huffstler** [comment]
It was `z-index: 2147483647 !important;`
Changing it to `200 !important;` did indeed put it above the page elements until I typed into the text-box again.
![image](https://user-images.githubusercontent.com/9092204/38625087-b4ab47dc-3d77-11e8-9650-37fd53576ae0.png)

**Comment by cmcaine** [comment]
I guess they changed the size of the CSS integer type. That'll break a few websites.

We currently use 2**31 - 1. Maybe experiment to see what the new max size is? It'll be something like 2**24 -1 or 2**30-1, probably.

**Comment by cmcaine** [comment]
We use the maximum size because other people do that too and we share a global z space with them.

**Comment by huffstler** [comment]
I'm trying out a couple different values currently:

`2**24 - 1` (`16777215`) = Doesn't work.

`2**30 - 1` (`1073741823`) = Works while scrolling, but loses foreground when typing in the box.

`2**61 - 1` (`2305843009213694000`) = Seems like it fixed it.

**Comment by huffstler** [comment]
Some more information for you guys to help nail it down a little further.

As soon as firefox loses focus (I click on the Snipping Tool to take a screen shot) the command box regains foreground control, and keeps it until focusing on firefox again.

**Comment by huffstler** [comment]
In the process of writing up a bug report on bugzilla I also noticed that the blinking cursor in the command bar is what resets the z-index I _ think_. I don't have numbers to back it up, but every time the command bar gains focus, it loses it when the cursor changes state.

**Comment by huffstler** [comment]
Seems like it's been fixed in at least version 1.9.5

I'll be closing this issue, though would be nice to get confirmation.

**Comment by bovine3dom** [comment]
@huffstler, we haven't changed anything. It's likely that a Firefox update fixed it.

**Comment by huffstler** [comment]
That's pretty funny actually. I was told on the bugzilla issue that it was an issue with Tridactyl.

Whatever, it's fixed now. Thanks :)
