### ISSUE TITLE
Allow binding keys to run arbitrary javascript snippets

### ISSUE THREAD

**Issue by robsmith11** [cmcaine/tridactyl#376]
Not sure how feasible or useful it would be, but is it possible to let the user bind keys to run a given javascript command?

I was looking for a way to force fullscreen on Android with the keyboard and thought this might be an easy to in combination with https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by glacambre** [comment]
I think this feature is planned (this is mentioned as "JS Eval" in https://github.com/cmcaine/tridactyl/issues/24). I don't think it has been implemented yet though.

Is firefox able to go in fullscreen mode on Android? Firefox Android doesn't seem to be mentionned in the compatibility table of the page you linked.

**Comment by robsmith11** [comment]
Yes, I tried a test page and it is able to toggle fullscreen mode correctly on Nightly for Android.  It's the same way that fullscreen videos work.

**Comment by bovine3dom** [comment]
@robsmith11 does Tridactyl work on Android?

Anyway, including a command for fullscreen is something I'm quite happy to do (eval will be harder).

**Comment by bovine3dom** [comment]
I've added a `:fullscreen` command in the latest betas... via an API which is not supported on Android...

`eval` will come some day, I promise :)

**Comment by robsmith11** [comment]
@bovine3dom 
Thanks, that will be useful for making a more convenient binding than F11 on my laptop.  It's too bad Android doesn't support "native" fullscreen.

And yes, tridactyl works pretty well on Android.  The newtab page doesn't show up, but I just use the Windows/Meta key that opens a new Firefox tab with the URL bar focused (at least on LineageOS).
