### ISSUE TITLE
request: implement the "copy/select element text" feature from vimfx

### ISSUE THREAD

**Issue by emanresusername** [cmcaine/tridactyl#38]
mentioned [here](https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/defaults.coffee#L81-L82) and [here](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md#L403-L406)

those have almost single-handedly kept me on firefox (pre 57) and that extension! 

might also address some of [`caret or visual mode - I'm not good enough at vim to find these easier than selecting with the mouse...`](https://github.com/cmcaine/tridactyl/blob/master/readme.md#L66)

PS. if there's a different workflow/key combo/paradigm people were using/had in mind for that, interested to hear about that too

**Comment by bovine3dom** [comment]
Sure, it could work quite well as an "extended hint mode", and probably wouldn't be that much work.

I'll rewrite clipboard https://github.com/cmcaine/tridactyl/blob/0a0f75121f390b74428600fa1134dd5fa403f69a/src/excmds.ts#L392 to accept any string while I'm thinking about it.

The rest will have to wait for hinting to be finished, which should be soon.

**Comment by pierroweb** [comment]
This solution seems cross-browser (firefox and chrome at least) and simple enough:
- Ctrl F and type the first word you want to select
- escape
- keep Ctrl+Shift and press the right/left arrows to expend the selected text

**Comment by bovine3dom** [comment]
@emanresusername Any thoughts on a bind? I'm thinking `;p` where `;` is our prefix for the gourmet hint modes and `p` stands for prose/paragraph.

**Comment by bovine3dom** [comment]
Copying element text is bound to `;p` from ea69746.

I'm not 100% sure which kinds of element can contain text, so I've been pretty conservative. If there are some missing, let us know / make a PR.

Is there demand for "select element text"?

**Comment by emanresusername** [comment]
re: demand for "select element text": not from me 😅. but just thinking it through i could see some scenarios where maybe that might play nicely with other extensions. a couple cases come to mind
  - [ubiquity](https://bitbucket.org/satyr/ubiquity) had like a translate currently selected text
  - even more relevant with something like [autocopy](https://addons.mozilla.org/en-US/firefox/addon/autocopy-2/) installed the `select text` binding might've automatically done the yank implemented here 🤔 

re: other elements: i'd add `pre` and `code`, i think like a good 80 of the time i use that feature is copying code snippets 😀 , i can do that pr in a bit

**Comment by emanresusername** [comment]
After a note on that pr... Maybe just yanking any non empty is the way (or an additional way) to go https://github.com/cmcaine/tridactyl/pull/116#issuecomment-346972836

**Comment by bovine3dom** [comment]
Closing this as I think ;p is pretty good now. As ever, feel free to disagree and I'll reopen this.
