### ISSUE TITLE
Tridactyl is unresponsive on motherboard.vice.com

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#383]
Steps to reproduce:
```
:tabopen https://motherboard.vice.com/en_us/article/jp5g8k/spacex-is-because-elon-musk-wanted-to-grow-plants-on-mars
```
You won't be able to scroll, open the commandline or close the tab with `d`. Pressing `<Esc>` solves the issue. It's probably just an element stealing focus, might be fixed by https://github.com/cmcaine/tridactyl/pull/326 .

**Comment by bovine3dom** [comment]
Fixed in #326.
