### ISSUE TITLE
Should we make Vimperator style hinting the default for new users?

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#385]
As in the title.

I imagine most current users are content with the hinting they have, so I think it would be unfair to change it for them.

But for new users: we claim to be Vimperator re-incarnate and have the wrong hinting.

Thoughts?

**Comment by cmcaine** [comment]
We should probably have an onboarding process that helps users pick a config they like and also exposes the options.

Could just be a commented default config file that opens on first load?

**Comment by bovine3dom** [comment]
I'd rather it was a wizard that could be run later. I think showing all the configuration to a new user could be somewhat bewildering. `tutor` is bad enough.

**Comment by bovine3dom** [comment]
Closing as apparently nobody cares.
