### ISSUE TITLE
Vimperator style hinting should ignore all keys for a bit after selecting a hint

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#386]
Currently, it is too easy when following e.g, "SAD is FUD", to select the hint and then start executing commands: "S... A.. (link selected)... D (close the tab)".

**Comment by cmcaine** [comment]
Vimperator added a delay between flashing the selected hint (or something) and actually selecting it and exiting hint mode

**Comment by diabolicfutility** [comment]
Chrome's cVim does this. You can set the value with 'typelinkhintsdelay' which defaults to 300ms.

**Comment by bovine3dom** [comment]
Thanks @diabolicfutility. 300ms feels about right. Added as `hintdelay`.
