### ISSUE TITLE
gT does not work as expected

### ISSUE THREAD

**Issue by janzhen** [cmcaine/tridactyl#392]
Tridactyl: 1.9.0-1-g025c83c
Firefox: 59.0.2

Pressing gT in normal mode, expecting ":tabprev", but ":tabopen" followed by current url show in ex mode. Just like pressing T only.

`:bind gT`

shows "# gT = tabprev".

And I tested gH, which have the same issue, works like H.

And I try binding gS to :viewsource. Pressing gS, ":tabopen search" shows in ex mode.

So, I think there would be something wrong here.

**Comment by cmcaine** [comment]
Thanks, I forgot to filter out bare modifiers.
