### ISSUE TITLE
Scrolling is slow on pages with lots of elements

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#395]
Scrolling when you're at the top of http://docs.nvidia.com/cuda/parallel-thread-execution/index.html is ok but it gets slower and slower the closer you get to the bottom of the page.

Not sure how to fix this. We could implement a `scrollstrategy` setting that changes the way elements are filtered here https://github.com/cmcaine/tridactyl/blob/1afc2e1ce54cc532d59d08c6cb12da486342d245/src/excmds.ts#L267 . Combined with domain-specific settings it could work but I don't like this idea.

Maybe we should try to find another strategy that doesn't depend on recursive access to the DOM.

**Comment by glacambre** [comment]
Yeah, I vaguely looked at pentadactyl's it seemed very ingrained in its internals so I decided to reinvent the wheel instead.

I'm note sure we want to port their scrolling logic though. Pentadactyl isn't able to scroll on Gitter while Tridactyl is (between that and our eventlistener hijacking I guess we can start claiming that Tridactyl is better than pentadactyl :p ). I could certainly try to look at their code again and see if there are things I could improve in ours though.

**Comment by glacambre** [comment]
cmcaine: I took a look at your code here: https://github.com/cmcaine/tridactyl/blob/cmcainemysteryscrollcode/src/scroll.ts
It relies on Buffer.findScrollableWindow() which itself relies on APIs that I believe are unavailable to webextensions. Did you have something in mind to replace this function call?

Another website where scrolling is slow: https://bugzilla.mozilla.org/show_bug.cgi?id=215243

**Comment by bovine3dom** [comment]
Scrolling up on http://docs.nvidia.com/cuda/parallel-thread-execution/index.html now scrolls up the table of contents, the page, and then the table of contents again, which is less than ideal.

**Comment by bovine3dom** [comment]
...wrong issue...

**Comment by glacambre** [comment]
There's still a small delay when scrolling on http://diana-adrianne.com/purecss-francine/ . This might not be our fault though since scrolling with <kbd>Space</kbd> is slow too.
