### ISSUE TITLE
tabopen in background

### ISSUE THREAD

**Issue by timokau** [cmcaine/tridactyl#396]
Would it be possible to add a feature like `:tabopen -b <url>` that does the same as tabopen but does not focus the tab?

If I understand the code correctly, `openInNewTab` already supports that by setting `active: false`. However, `tabopen` doesn't expose that functionality.

https://github.com/cmcaine/tridactyl/blob/d59f890a321abb99bdd1b1baf8ebf7372e5fcb30/src/excmds.ts#L927

**Comment by cmcaine** [comment]
Sure. Done.

**Comment by cmcaine** [comment]
Can't be bothered to do a stable release, but it's in the betas and will be in the next stable release.

**Comment by timokau** [comment]
Great, thank you!
