### ISSUE TITLE
Add option to reset standard Firefox keybindings (like <c-d> for bookmarking)

### ISSUE THREAD

**Issue by WorldCodeCentral** [cmcaine/tridactyl#398]
Nice to have:
- setting page to revert overridden Firefox default hotkeys to defaults per user interface (right now there's only `:viewconfig` if I'm right where things can't be changed) for newcomers
- if unbound, use default hotkey (`:unbind <c-d>`)
- a section that explains how to revert to defaults in the tutorial.

Temporary fix:
Use Tridactyl's `A` instead (doesn't open dialogue for folder, title, etc though), press <c-d> when in input mode/ex mode, caps lock and `<c-d>`

**Comment by cmcaine** [comment]
Unbinding actually sets the property to `""`, but the keyseq code rightly doesn't know about that convention.

For now I'm putting some special casing in the normalmode parser.
