### ISSUE TITLE
Pressing "t" causes Tridactyl to not functioning

### ISSUE THREAD

**Issue by thomasyoung** [cmcaine/tridactyl#400]
![tridactyl](https://user-images.githubusercontent.com/583132/38902438-5c82ee56-4255-11e8-93d9-28cbe04db940.png)

Recently if press "t" in view mode, it would render Tridactyl to not functioning anymore. It is like Tradactyl was not installed at all.
I tried to check "viewconfig nmaps" and found weird binding linking to some wild youtube link.
Not sure if it is related. Couldn't find where to clear this binding.

**Comment by glacambre** [comment]
Hi, just to make sure I understand this issue correctly, does Tridactyl work when you restart it/restart firefox? Also, what is "t" bound to in your config?

**Comment by cmcaine** [comment]
The weird binding is an easter egg and not related.

I've fixed a few issues with binds, so please try and reproduce on the latest beta.

If you can reproduce, please paste the result of `get nmaps` to this issue.

Thanks!

**Comment by thomasyoung** [comment]
@glacambre It seems that t is bind to tabopen. I would try again on latest again.

# nmaps = {"o":"fillcmdline open","O":"current_url open","w":"fillcmdline winopen","W":"current_url winopen","t":"fillcmdline tabopen","]]":"followpage next","[[":"followpage prev","[c":"urlincrement -1","]c":"urlincrement 1","T":"current_url tabopen","yy":"clipboard yank","ys":"clipboard yankshort","yc":"clipboard yankcanon","gh":"home","gH":"home true","p":"clipboard open","P":"clipboard tabopen","j":"scrollline 10","<c-e>":"scrollline 10","k":"scrollline -10","<c-y>":"scrollline 10","h":"scrollpx -50","l":"scrollpx 50","G":"scrollto 100","gg":"scrollto 0","<c-u>":"scrollpage -0.5","<c-d>":"scrollpage 0.5","<c-b>":"scrollpage -1","$":"scrollto 100 x","^":"buffer #","<c-6>":"buffer #","H":"back","L":"forward","d":"tabclose","u":"undo","r":"reload","R":"reloadhard","gi":"focusinput -l","gt":"tabnext_gt","gT":"tabprev","g^":"tabfirst","g$":"tablast","gr":"reader","gu":"urlparent","gU":"urlroot",":":"fillcmdline","s":"fillcmdline open search","S":"fillcmdline tabopen search","M":"gobble 1 quickmark","b":"fillcmdline buffer","ZZ":"qall","f":"hint","F":"hint -b",";i":"hint -i",";I":"hint -I",";k":"hint -k",";y":"hint -y",";p":"hint -p",";r":"hint -r",";s":"hint -s",";S":"hint -S",";a":"hint -a",";A":"hint -A",";;":"hint -;",";#":"hint -#","I":"mode ignore","a":"current_url bmark","A":"bmark","zi":"zoom 0.1 true","zo":"zoom -0.1 true","zz":"zoom 1",".":"repeat","<SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba":"open https://www.youtube.com/watch?v=M3iOROuTuMA","tabprev":"J","tabnext":"K","J":"tabprev","K":"tabnext"}

**Comment by cmcaine** [comment]
You were affected by the same bug as #399 #401. Sorry about that.

You have some bad binds you might want to remove:

```
Object.entries(nmaps).filter(([k,v]) => k.startsWith('t'))
[…]
0: Array [ "t", "fillcmdline tabopen" ]
1: Array [ "tabprev", "J" ]
2: Array [ "tabnext", "K" ]
```
