### ISSUE TITLE
`hint -b` doesn't always open a new tab in the same container as current tab

### ISSUE THREAD

**Issue by WorldCodeCentral** [cmcaine/tridactyl#406]
Just realized that when hitting a hint it's not always the same as a middle click. For example I use the Firefox Multi-Accounts Containers extension and it has always worked the same for me, middle click and hint hitting, but just now I found that in the one tab I have hint -b does not open in the current container, whereas just hint works in the current container and middleclick works as well (opens in a new background tab in the same container)

It's the first time it's happened to me though and I can't reproduce it :( So it's not really annoying

**Comment by cmcaine** [comment]
Our code is not currently container aware. Your expected behaviour only occurs when the hint code successfully simulates a click on the hinted element and the firefox code handles all that jazz.

The code to change is `src/lib/webext.ts:openInNewTab()`

**Comment by WorldCodeCentral** [comment]
Was able to reproduce :-) The problem was a toplevel domain prefix that I didn't see which took me to the same site though. But my container was only set up to activate automatically for the toplevel domain without the prefix so it didn't activate.

How containers work though is that you're never leaving the container if you click any links, even in new tabs. That is where the behavior differs if you use Tridactyl.

It's just one more thing on the list that can be striked off once Tridactyl can just reproduce the browser's behavior/methods instead of use it's own/web extension specific things :-)

**Comment by antonva** [comment]
This is fixed as of (at least) 1.11.2-1.11.2.

**Comment by bovine3dom** [comment]
@antonva really? I thought I hadn't released it to stable yet. I was expecting it to appear in version 1.12.0.

**Comment by antonva** [comment]
Yeah, it's working on that version most definitely.

**Comment by bovine3dom** [comment]
There's some minor issue with beta versioning, but it's definitely not in the stable release yet.
