### ISSUE TITLE
I broke input mode

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#409]
Almost certainly in 027371029c8913f087bd7061bb14e91b08715ce6.

You fall out of input mode into insert mode as soon as you type something, breaking `Tab`.

Annoyingly, this out in the stable release of Tridactyl, so we should probably fix it as a priority.

**Comment by glacambre** [comment]
What was the annoying bug you mentioned in your commit message?

**Comment by bovine3dom** [comment]
Clicking outside of a text box would leave you in input mode until you hit escape.

**Comment by glacambre** [comment]
I see. I thought we already dealt with this situation with a listener for a `blur` event. I'll look into it.

**Comment by bovine3dom** [comment]
Probably just need to add mode!=input on this line https://github.com/cmcaine/tridactyl/commit/027371029c8913f087bd7061bb14e91b08715ce6#diff-c839743e45aff488cd4be730ac99eaddR46

**Comment by glacambre** [comment]
I'm not sure I understand this piece of code and what adding `mode != "input"` would mean logic wise. I think I would have reverted your commit and then added a `blur` listener to every input that gets focused (the listener could have been added by our focus-hijacking function). If what you suggest fixes this issue then I think your solution is better.

**Comment by bovine3dom** [comment]
Fixed in f8dfb7a, I think.
