### ISSUE TITLE
Please make the mode indicator follow the Tridactyl theme

### ISSUE THREAD

**Issue by polyzen** [cmcaine/tridactyl#415]
https://github.com/cmcaine/tridactyl/commit/c67adc44e34052217198fc7924c8f8bc88e84f8d#commitcomment-28690045

**Comment by behrmann** [comment]
I have another two options, that I'd like to put forward as well

1) an option to turn of the mode indicator completely,
2) for it to take on the background colour, because otherwise it can be really quite distracting.

**Comment by chrlsnchrg** [comment]
+1 on hiding the mode indicator please. It's very obvious (to me) which mode I'm in and this little doodley-doot is just annoying.

**Comment by bovine3dom** [comment]
Happy to make a config for toggling mode indicator on/off.

I think we should think about dark mode more seriously - to see if there is a better way we can handle it using variables - otherwise we'll just see this happen again and again.

**Comment by chrlsnchrg** [comment]
Thank you Oliver.

**Comment by bovine3dom** [comment]
@behrmann @chrlsnchrg @polyzen toggle added in the latest betas. Just `set modeindicator false`.

**Comment by behrmann** [comment]
Excellent, thanks!

For the "dark mode" of the mode indicicator maybe using the background colour at this position and for foreground colour something along the lines of [onury/invert-color](https://github.com/onury/invert-color) would be a doable solution.
