### ISSUE TITLE
Clicking in the left hand pane of gmail stops keyevents being sent to Tridactyl

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#417]

**Comment by cmcaine** [comment]
Could not reproduce. Scrolling is really weird on gmail, though: are you testing with scrolling or some other function?

I used `:`, `o`, `f`.

**Comment by bovine3dom** [comment]
I think I tried everything, and I had the debug console open and key events weren't being logged.

**Comment by bovine3dom** [comment]
Reproducible - but you have to click in the "Hangouts" bit in the bottom left half of the pane.

**Comment by cmcaine** [comment]
Cool. It's the same iframe issue. Closing as duplicate.
