### ISSUE TITLE
`go*` and `gw*` break Tridactyl unless * is a quickmark

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#418]
...which is strange because they're just "dumb" binds. Presumably this was introduced with keyseq.

Edit: credit to Zevv on Matrix for pointing this out.

**Comment by bovine3dom** [comment]
You have to have a quickmark bound for this.

I've done `git bisect` and it looks like it was introduced by keyseq:
```
2ccfdda110e144029eaa4d54eb7a83a8f82fa32d is the first bad commit
commit 2ccfdda110e144029eaa4d54eb7a83a8f82fa32d
Author: Colin Caine <cmc@cs.man.ac.uk>
Date:   Sun Apr 15 23:12:54 2018 +0100
    Use keyseq for normalmode
    Also rename ex_str to exstr in a bunch of places for no real reason.
:040000 040000 35b4ea4e1d94df7a0e38af68f0d7243c2b358481 8760b3e515e64c8cf5b15dedaf300ff16d75ffba M      src
```

**Comment by bovine3dom** [comment]
cmcaine on Riot:
> 20:28Found the bug in #418.
> 20:29It's in keyseq.ts/prefixes()
> 20:29If anyone wants to play hunt the bug

**Comment by cmcaine** [comment]
Fixed it and read through the code carefully and added some -ve tests to the keyseq suite in the hope of catching any other bugs.

Some days I think I'm not very good at programming.
