### ISSUE TITLE
Improved insert mode

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#42]
Two main ways to go about this:

1. Open in $EDITOR (via native messenger)
2. Swap text area with CodeMirror https://codemirror.net/index.html or ACE https://ace.c9.io/ (in Vim-mode, obviously); we should do some testing to see which is the most lightweight option.

We should do both.

**Comment by youngmit** [comment]
Came here hoping tridactyl would implement the behavior of pentadactyl's (RIP) external insert, essentially option 1. Pentadactyl would pop whatever text was in a text box out into the $EDITOR, extract it when the editor saves the buffer. This is obviously quite powerful, as it allows a user to leverage the full sophistication of their vim and personal config.

**Comment by mkaito** [comment]
I would like to also vote for option 1. I'm okay with it requiring an external service to be running. I can just run it via systemd. This is probably the main thing that keeps me going back to qutebrowser (until I need to use my yubikey).

**Comment by bovine3dom** [comment]
@mkaito, @youngmit, the native messenger has landed in the betas for Linux. Install it by following the instructions on `:installnative` and then access your editor with `<C-e>` in a text box.

If your favourite editor doesn't open, you can set the command used with `set editorcmd`. You need to pick something that stays in the foreground until it is exited.
