### ISSUE TITLE
'open' <empty string> results in odd behaviour and annoyances

### ISSUE THREAD

**Issue by Bzly** [cmcaine/tridactyl#421]
Steps to reproduce:

- Press `o` to bring up 'open' (current page must _not_ be the Tridactyl new tab page).
- Immediately press the `enter` key.
- Notice that the browser has opened a page belonging to Tridactyl that is called "_generated_background_page.html".
- Notice Tridactyl does not insert itself onto this page, so you become 'trapped'.
- Notice that whilst this page is left open in a (background) tab, all 'tabopen' events execute twice: opening two identical tabs.
- Post issue to GitHub.

**Comment by cmcaine** [comment]
Thanks Jake :)
