### ISSUE TITLE
Indicator's text should not be selectable

### ISSUE THREAD

**Issue by arthurmillergitmybaby** [cmcaine/tridactyl#423]
As it stands, the text for the mode indicator is user selectable. This is undesirable if copying the full text of a page. (Enter 'ignore' mode, Ctrl + A to select all text- the selection now includes the word 'ignore' from the indicator's span).

**Comment by bovine3dom** [comment]
For what it's worth, the Tridactyl way of copying page text is to enter the copy text hint mode with `;p` and then choose the element you want (although if you find the real root node, you'll end up copying the mode indicator anyway).

Thanks for the PR!

**Comment by NilsIrl** [comment]
This is also problematic when searching.

For example, when searching for visual, the indicator gets selected.
