### ISSUE TITLE
Native messenger doesn't work on OSX

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#429]
I get "Unexpected error" when doing anything that needs native, but only with the beta: locally building the extension works fine.

**Comment by cmcaine** [comment]
`env python3` doesn't work in Firefox in OSX (unless you start firefox with web-ext, presumably something about PATH?)

We have the install script put the output of `which python3` into the crunchbang.

**Comment by bovine3dom** [comment]
Fixed in 8438fc7, we think.
