### ISSUE TITLE
Tridactyl does not work well with weird keyboard layouts

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#430]
On my keyboard layout, pressing <kbd>[</kbd> and <kbd>]</kbd> requires pressing <kbd>AltGr</kbd> (also known as RightAlt or Alternative Graphics) and then <kbd>(</kbd> or <kbd>)</kbd>. If I'm slow enough between the time I press <kbd>AltGr</kbd> and <kbd>)</kbd>, firefox will send first and `AltGraph` keyevent to Tridactyl and then a `]` keyevent. This breaks using `[[` and `]]`.
While the sane thing to do would be to go on a crusade to force keyboard manufacturers and OS vendors to agree on a common protocol that would enable keyboards to directly input unicode characters to the OS, I think the easier thing to do would be to ignore the <kbd>AltGr</kbd> key event unless it is explicitly bound to an action.

**Comment by bovine3dom** [comment]
I think we just left it off the list of modifiers; we ignore all the others if they are pressed on their own.
