### ISSUE TITLE
Kill-mode on tutorial page highlights the mode-indicator

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cmcaine/tridactyl#439]
Title kinda says it all: on the tutorial-page that demonstrates kill-mode, kill-mode (#238) … doesn't actually work?

Latest nightly, Tridactyl 1.9.8-66-g24f9968. `(=`

**Comment by bovine3dom** [comment]
It works for me:

- :tutor, go to hint page
- ;k, press 5 (or whatever your first hint char is)
- mode indicator disappears.

Or are you saying we shouldn't be able to kill the mode indicator?

**Comment by ELLIOTTCABLE** [comment]
I explained a little too briefly, hah!

I mean, *only* the mode-indicator is highlighted, nothing else on the page:

<img width="904" alt="screen shot 2018-05-01 at 3 55 26 pm" src="https://user-images.githubusercontent.com/200/39493377-3e6ac2aa-4d58-11e8-99f9-649aed9d7cc4.png">

**Comment by bovine3dom** [comment]
Oh, that's just because we don't hint literally every single element, just plausibly annoying ones. If we said it was for killing floating elements, would that be better? It's not 100% true but maybe that doesn't matter...

**Comment by ELLIOTTCABLE** [comment]
Hmmm. I’m not sure, as I have yet to use it!

Maybe just add an explicitly annoying element to the tutorial page? Clearly, this is a documentation Issue, then, not a behavioral one. 🤣
