### ISSUE TITLE
zi/zo should use the PDF reader's zooming functions

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#445]
Currently, zooming with zi/zo on a PDF document will result in a blurry document. Tridactyl should instead behave as if the `+` or `-` buttons had been clicked.

**Comment by bovine3dom** [comment]
Closing because of #541. RIP :bouquet:.

**Comment by glacambre** [comment]
Should probably be reopened thanks to https://github.com/cmcaine/tridactyl/issues/541 being fixed.
