### ISSUE TITLE
Populating command line from completion with `<Space>` doesn't let you edit it

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#446]
Steps to reproduce:

1. `:open` and type some stuff.
2. `<Tab>` and press space.
3. Change the URL manually by typing.
4. Hit enter and be amazed as the original URL you pressed space on appears.

**Comment by glacambre** [comment]
I probably forgot to reset the selected completion option when the user presses space. I can look into it in a few hours.
