### ISSUE TITLE
Close all tabs to the left/right

### ISSUE THREAD

**Issue by maxigaz** [cmcaine/tridactyl#461]
I'd like to be able to close all tabs left/right of the current tab with a key combination, just like in Vimium.

(In Vimium, this feature can be accessed by pressing `gx0`, which closes all tabs to the left, and `gx$`, which closes all tabs to the right.)

**Comment by bovine3dom** [comment]
I'd be happy to help anyone work on this. It should be quite simple.

The trickiest part will be deciding which tabs are to the left, and which are to the right. I suspect that the tabs array on Window https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/Window has the tabs in order of their position, but I could be wrong.

**Comment by cmcaine** [comment]
Tab objects come with an index, so we can just sort by that. Nae bother.

**Comment by caputchinefrobles** [comment]
In vimperator rcfile I had something like:
js <<EOF

closeAllToRight = function () {
    var current = tabs.getTab();
    var currentIx = tabs.index(current);
    var nexttab = current.nextElementSibling;
    var N = tabs.count;
    var numToClose = N - (currentIx + 1);
    tabs.remove(nexttab, numToClose);
}

closeAllToLeft = function () {
    var current = tabs.getTab();
    var currentIx = tabs.index(current);
    var firsttab = tabs.getTab(0);
    var N = tabs.count;
    var numToClose = currentIx;
    tabs.remove(firsttab, numToClose);
}

EOF

command! closealltoright :js closeAllToRight()
command! closealltoleft :js closeAllToLeft()

" close tabs to left
map x. :js closeAllToRight()<Return>
" close tabs to right
map x, :js closeAllToLeft()<Return>

Maybe It could help with a future feature.

**Comment by caputchinefrobles** [comment]
Is there anyone with this already? If not I'd like to take it if possible.
