### ISSUE TITLE
YouTube search doesn't work any more

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#462]
As in, `open youtube medallion abolition: pigouvian taxis`. Since the latest redesign, it requires plusses between the search terms.

**Comment by glacambre** [comment]
I can't reproduce this issue on Tridactyl-master+Firefox 59.0.2-linux.

**Comment by bovine3dom** [comment]
... yeah, it started working again. PEBKAC I guess. Thanks for trying to reproduce it :)
