### ISSUE TITLE
Matrix IRC bridge is down

### ISSUE THREAD

**Issue by Koushien** [cmcaine/tridactyl#47]
Connected to freenode, it looks like I can only see the other users on IRC and can't communicate with any others; my last few messages don't appear in https://riot.im/app/#/room/#tridactyl:matrix.org. Users using a Matrix account appear unaffected as from the Riot link I can see cgeier is online. Not sure if this is Matrix side or some bizarre accident.

**Comment by cmcaine** [comment]
Fixed.
