### ISSUE TITLE
# Error: Error processing focusinput(-l) InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable 

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#471]
Happens on https://accounts.google.com/signin/v2/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin when not logged in and pressing `gi`.
The input element is briefly focused and then unfocused.
Maybe related to https://github.com/cmcaine/tridactyl/pull/326 , https://github.com/cmcaine/tridactyl/issues/449 or https://github.com/cmcaine/tridactyl/pull/463 ?

**Comment by Sinderella** [comment]
I am experiencing the same issue on https://gophercises.com

`gi` gives me

```
# Error processing focusinput(-l) InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
```

`ff` for the email input gives me

```
# Error processing pushKey([object Object]) InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable 
```

**Comment by glacambre** [comment]
The `gi` bug will be fixed by https://github.com/cmcaine/tridactyl/pull/649 and the `ff` bug will probably be fixed by https://github.com/cmcaine/tridactyl/pull/648 . It might take a little while for these PR to be merged though, the maintainers are pretty busy at the moment :)
