### ISSUE TITLE
latest update breaks hit a hint feature for firefox dev edition on mac os X

### ISSUE THREAD

**Issue by aoh83** [cmcaine/tridactyl#475]
pressing f on a window shows all letters for link selection as expected, but the tab bar steals key stroke events such that hitting a link starting with u will trigger the undo function

**Comment by bovine3dom** [comment]
We've had quite a few issues pop up and then disappear with the Firefox Dev Edition (which is more bleeding edge than Firefox Beta). I think we'll just wait and see if this issue persists.

Thanks for reporting it.

**Comment by bovine3dom** [comment]
@aoh83 does this still happen?

**Comment by aoh83** [comment]
I removed the addon after it had the issue, I'll reinstall and see.

**Comment by bovine3dom** [comment]
>  Do you know why this happens?

Firefox is complicated and so its developers break things unexpectedly when they add new features or fix other things. Luckily they have enough users testing things that they usually spot regressions before they get into stable.

I'd recommend against using the dev edition - stable is much more stable :)
