### ISSUE TITLE
Support for building on Windows

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#48]
- [ ] change all shell scripts to pure JS

- [ ] make all paths OS independent

- [ ] fix git commit hooks

Building in Cygwin used to work until recently, but it would be good if pure Windows would work too.

**Comment by cmcaine** [comment]
Relative paths with forward slashes will work fine, I think.

Cygwin will probably work except for the symlinks?

**Comment by bovine3dom** [comment]
There's no Node for Cygwin so I was using the Windows binary, meaning that it can't find some things such as bash... but some stuff did work.

**Comment by bovine3dom** [comment]
Nobody has asked for this for a while, so I'm going to close this issue.

**Comment by bovine3dom** [comment]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse                                                               vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                               1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                               )
```

These aren't errors - they're warnings. You can safely ignore them : )

```
    - PowerShell major version >= '3' required, '2' found, quitting ...
```

is because the build process also installs the native messenger, which uses a PowerShell script on Windows. Please update your version of PowerShell (although it probably isn't technically needed for a local installation).


Could you open a new issue to discuss these poorly documented dependencies? I don't quite understand what you mean about Python.

**Comment by reversebreak** [comment]
I'm the kind of person that compiles with -Wall, y'know?  If those are ignorable, then that's OK.

I learned something today!  Apparently the version of the powershell shell and powershell engine are different and independent!  You can have the fancy newer shell installed and yet still be running on the old one internally...
I updated and that's fixed now.

I'm not sure I've got enough to open an issue on in regards to the Python dependency.  I didn't think to write down which package or run time thing required it, and now that it's fixed, I'm not sure I can easily find it again.  
All I can say is that it was looking by default for a specific sub-version of 3.6 Python exe in a default Program Files location, then when that failed looked for the PYTHON env variable.  
I might try removing the PYTHON environment variable and see what happens then, once I'm done with #711

**Comment by gsbabil** [comment]
@reversebreak @bovine3dom

Off the top of my head, the building Tridactyl on Windows seems to
require the following:

1. [PowerShell][0]
    - Recommended version >= `3`

2. [NodeJS][1]
    - Recommended version >= `8 (LTS)`

3. [Python][2]
    - Recommended version >= `3.5`

4. [Git][3]
    - Recommended version >= `2.7.4`
    - As the build shell, I have only used MinTTY/MSYS2 aka "Git
      Bash", which tends to come bundled with ["Git for Windows"][3].

After getting the right version of [PowerShell Core][0], the
quickest way to install NodeJS, Python and Git on the Windows system
(I'm using Windows 10) is via [Chocolatey][4].

Consider Chocolatey as the NPM/PIP/APT/PACMAN/PKG/BREW of Windows.
Follow the instructions [here][5] to get Chocolatey on your system.
Once Chocolatey is installed, the following PowerShell commands
should get you sorted regarding the dependencies mentioned above:

```PowerShell
choco install powershell
choco install nodejs
choco install python3
choco install git
```

At this point, you should be able to open _"Git Bash"_, clone
Tridactyl repository, and start following the usual build instructions.


Hope this helps. Thanks.


[0]: https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6
[1]: https://nodejs.org/en/download
[2]: https://www.python.org/downloads
[3]: https://git-scm.com/download/win
[4]: https://chocolatey.org
[5]: https://chocolatey.org/install
