### ISSUE TITLE
disable 'mode' hint

### ISSUE THREAD

**Issue by calmarc** [cmcaine/tridactyl#482]
is it possible to disable the mode hints there in the bottom right corner.
(like insert, normal etc).

Not only cover they some content I need to see, but are additionally incredible ... well. No rocket-science to know/figure out what mode you are .. no need for a retarded-hint.

else everything nice, thanks!

**Comment by calmarc** [comment]
set modeindicator false

ok, that helped. thx.

**Comment by bovine3dom** [comment]
Documentation of configuration options is bad, sorry it took so long to find it.

`viewconfig` is probably the easiest way to find out what's possible.
