### ISSUE TITLE
RFE: Provide url hint in temporary filename when using an external editor

### ISSUE THREAD

**Issue by larsks** [cmcaine/tridactyl#495]
Please include at least the hostname of the current site in the generated filename when opening text fields in an external editor.

When opening a text field in an external editor via `C-i`, the name of the temporary file used for editing is something like `/tmp/tmpc7afl0vh`. This makes it impossible to implement site-specific settings in an editor.

In comparison, Vimperator would include the hostname in the generated temporary filename, so that editing a text field on GitHub might end up with a file named `/tmp/tmp-github.com-7af10vh` (that's an approximation; it's been a while since I was able to install vimperator so I don't recall the exact pattern).  This was convenient because many editors allow settings to be attached to specific filename patterns, so for example I have the following floating around in my `.vimrc`:

```
au BufRead *stackoverflow.com* setlocal ft=markdown
au BufRead *github.com* setlocal ft=markdown
```

When editing text fields on github and stackoverflow, this would set
the filetype of the resulting buffer to markdown, so I would get
appropriate syntax highlighting, text margin and wrap settings, etc.

**Comment by bovine3dom** [comment]
Probably quite easy if anyone wants to give it ago.

1. native/native_main.py needs mkstemp to accept a prefix: https://docs.python.org/3/library/tempfile.html
2. src/native_background.ts and/or src/excmds.ts needs to tell the native script the host name of the site when you run editor.
