### ISSUE TITLE
Mapping bind to leave ignore mode

### ISSUE THREAD

**Issue by robertgzr** [cmcaine/tridactyl#505]
After introducing the new default map of the ignore mode to `Shift-Insert` I wanted to remap it to something else since I don't have the Insert key on my Macbook... Binding a key combination to trigger `mode ignore` works fine but it doesn't get me out of ignore mode.

I don't know what the best approach would be... Probably allowing the user to bind another excmd that would take them out of ignore mode. Alternatively it would also work if the combination that activates ignore mode also deactivates it.

**Comment by bovine3dom** [comment]
A special case of #304.

Which bind would you like? I'm happy to put one in as it will be a while before we fix #304. Which physical keys do MacBooks have left these days? :P

**Comment by robertgzr** [comment]
> Which physical keys do MacBooks have left these days?

true that 😢

I guess something involving `esc` would make sense, since it's about going back to normal mode...

**Comment by bovine3dom** [comment]
> I guess something involving esc would make sense since it's about going back to normal mode...

I thought they didn't have Escape? How does `<FunnySplatKey-Esc>` sound?

**Comment by robertgzr** [comment]
> I thought they didn't have Escape? 

Mine still has

You mean `<Super-Esc>`? FunnySplatKey being ⌘ I guess^^

**Comment by bovine3dom** [comment]
How does `<Super-\`>` sound? It's in roughly the same place as escape and would then work on the new fangled touch screen ones that only have escape sometimes.

**Comment by bovine3dom** [comment]
`<C-A-Esc>`?

**Comment by lehasb** [comment]
That would work for me, at least until custom binds are available.

**Comment by hdhoang** [comment]
unfortunately Windows (10 in my case) interprets `CA-Esc` to be `Alt+Escape` and then buries Firefox's window too... It's ["switch window without dialog" here](https://en.m.wikipedia.org/wiki/Table_of_keyboard_shortcuts). Can we come up with something else?

**Comment by bovine3dom** [comment]
Ctrl Z seems like the kind of thing people might want to press in ignore mode anyway. What's wrong with S-Insert for you?

**Comment by hdhoang** [comment]
my netbook doesn't have Insert 🤷‍♂️ (japanese thinkpad twist) 

I feel your point about C-z being common too.

**Comment by bovine3dom** [comment]
Does it have a backtick key? \`
I could bind it to CA backtick too...

**Comment by hdhoang** [comment]
yes it does, that would be an excellent choice! I haven't found any conflict in my environments, and it looks uncommon (microsoft japanese IME uses Alt+backtick for toggling, but thankfully it doesn't mis-activate like Alt+Escape above)

**Comment by ELLIOTTCABLE** [comment]
I went searching for this for the same reason as above posters; I can't make any of the available options work on my Mac:

1. Supposedly Fn+Return is ‘Insert’, but Shift+Fn+Return doesn't get me out of ignore mode …
2. No physical escape key exists, and control-option-‘esc’-touchkey (unsurprisingly) doesn't work either …
3. Control-Option-Backtick doesn't work either …

I've verified with Karabiner's EventViewer that the keys are, in fact, reporting … so I dunno what else to try?

<img src="http://ell.io/icQutlz+">

**Comment by ELLIOTTCABLE** [comment]
Completely incomprehensibly, given that I've looked at the source-code and have *no idea* how this could be the case …

**⇧⌃⌥\`** (i.e. **⌃⌥~**) works, but without Shift, it definitely does not. WTF.

**Comment by bovine3dom** [comment]
Could you file another issue? Yours seems to be with our key sequence parser; it doesn't have much to do with ignore mode.

Do `viewconfig logging`, set the one that looks most like it is to do with keys to DEBUG, and then open the web and browser console, press your weird key combination and tell us what it logs.

**Comment by bovine3dom** [comment]
@ELLIOTTCABLE progress on #304 means you can now do

`bind [the few keys on your keyboard that you haven't broken] mode ignore`
`set ignoremaps.[the few keys on your keyboard that you haven't broken] mode normal`

**Comment by seren** [comment]
I know this is long closed, but I thought I'd let @ELLIOTTCABLE know I can reproduce this. Ctrl-Alt-Backtick on my MacBook has no effect, but adding Shift toggles ignore mode (as does Ctrl-Alt-Esc).

**Comment by bovine3dom** [comment]
🤷‍♂️

**Comment by Ding-Fan** [comment]
For me, <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Esc</kbd> works.

**Comment by lockejan** [comment]
Can you add this note for OSX to the ReadMe, please? I spent the last hour trying to map this properly until I stumbled upon this issue here.

**Comment by bovine3dom** [comment]
Which note, @lockejan? That CA-Esc is a default bind?

**Comment by lockejan** [comment]
> Which note, @lockejan? That CA-Esc is a default bind?

Yes, please. ✌️ 😃
