### ISSUE TITLE
Open in editor is broken on master

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#511]
`# Error: Error: input is null `

Probably an easy fix.

**Comment by bovine3dom** [comment]
Somehow, 7ff1e590d63c6ce337d491f1988e73ba28f04ae4 seems to have broken DOM.getLastUsedInput() :S

**Comment by glacambre** [comment]
Bisect says 7ff1e590d63c6ce337d491f1988e73ba28f04ae4 is the culprit

**Comment by bovine3dom** [comment]
https://github.com/cmcaine/tridactyl/commit/7ff1e590d63c6ce337d491f1988e73ba28f04ae4#diff-9ddd9172e4a54cdd30d56e5f10d5facaR7 <-- problem is this line.

Can solve it pretty easily by just throwing errors rather than filling the command line.

**Comment by gerroon** [comment]
This is still broken in beta from 7/3

**Comment by bovine3dom** [comment]
@gerroon what's the output of `version`? It works fine for me on Linux and Windows on version `1.13.1-45-gcf39a9a` and has been working for a long time.

What operating system are you using? What's the output of `native`?
