### ISSUE TITLE
# Error: Error in retrieving config: undefined 

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#518]
This happens on 1.11.0-94-gd648ef4 when you don't have a Tridactylrc.

**Comment by bovine3dom** [comment]
Can't reproduce :S

**Comment by glacambre** [comment]
Weird, I can't reproduce it either now, but it happened to me on two different computers... Maybe it only happens when upgrading Tridactyl?
Closing for now, will reopen if I manage to find a way to reproduce it.

**Comment by bovine3dom** [comment]
Well, it's happening on my other PC. Guess this is a real issue. :S 

Somehow the errors are not being caught.
