### ISSUE TITLE
Support :set! command from Pentadactyl

### ISSUE THREAD

**Issue by maln0ir** [cmcaine/tridactyl#526]
In Pentadactyl `:set!` command allowed to change browser settings (about:config). I used that command in my `.pentadactylrc` to set my own configuration and also store it in vcs-friendly way.

It would be nice to get this _back_ :)

**Comment by bovine3dom** [comment]
Easy in theory: we just need to make/edit user.js http://kb.mozillazine.org/User.js_file

The tricky part would be if we want to have any kind of checking that values are supported and their types, etc.

**Comment by bovine3dom** [comment]
Duplicate of #468 :)
