### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by wavexx** [cmcaine/tridactyl#528]
The following is displayed on FF just after starting firefox itself without the native extension:

``# Error: Error sending native message: Error: Attempt to postMessage on disconnected port``

The fact that the native extension is not available shouldn't be an error and/or notified at each startup.

**Comment by bovine3dom** [comment]
This sounds like it might be related to #518. Could you update (about:addons, click "Check for updates", restart the browser) and see if it persists?

Thanks.

**Comment by wavexx** [comment]
I'm following the beta channel already and updating almost daily.

**Comment by bovine3dom** [comment]
What is the output of `version`? #518 has only been fixed since `1.11.2-1.11.2`.

**Comment by wavexx** [comment]
This is "1.11.2-1.11.2".

**Comment by bovine3dom** [comment]
Can't reproduce on my system. I see an error in the browser console but it doesn't reach the command line.

**Comment by bovine3dom** [comment]
I can reproduce it on another system. Thanks for reporting it, @wavexx.

**Comment by wavexx** [comment]
For me it is. But like I said, only when starting FF (using --new-instance, for example).
It wouldn't be problematic if the command line wasn't focused on start, eating all keybindings.

**Comment by bovine3dom** [comment]
@wavexx would you mind updating to `version` `1.11.2-6-gea99627` and confirming whether it is fixed?

**Comment by wavexx** [comment]
On Sun, May 13 2018, Oliver Blanthorn wrote:
> @wavexx would you mind updating to version 1.11.2-6-gea99627 and confirming whether it is fixed?

Fixed, thanks!
