### ISSUE TITLE
Bind fillcmdline without a trailing space

### ISSUE THREAD

**Issue by rbsec** [cmcaine/tridactyl#529]
On Pentadactyl I had some shortcut keys setup to (for example), quickly browse to a GitHub repo with

```
nnoremap G :open https://github.com/
```
So I could just press G and then type the username/repo.

Doing this kind of binding in Tridactyl just takes me to `https://github.com/`, so I tried doing it with `fillcmdline` instead:
```
bind G fillcmdline open https://github.com/
```
This almost does what I'm looking for, but it adds a trailing space after `https://github.com/`, so if I try a repo name the URL will be broken because of the space.

Is there a way to use `fillcmdline` without a space, or another way I can do this?

Thanks,

~rbsec

**Comment by bovine3dom** [comment]
Yeah, `fillcmdline_notrail`. Our `help` is reasonably good - searching for "trailing" gets me to it pretty quickly :)

**Comment by rbsec** [comment]
Thanks - I should have searched better - my bad.

~rbsec
