### ISSUE TITLE
Private mode support

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#53]
`winopen -private google emacs-style browser extensions` is currently stored in command history, if entered in a non-private window.

We should work out how we're going to deal with sensitive commands; potentially involving a blacklist of commands to never store.

Additionally, it is currently very hard to tell if the window you are in is private if you are using our userChrome. We could solve it with our own modeline or by figuring out how to disable it in the userChrome.

**Comment by cmcaine** [comment]
I think modeline is a nicer solution.

**Comment by bovine3dom** [comment]
Fixed in 7429f8c.
