### ISSUE TITLE
ignore mode for mac keyboards

### ISSUE THREAD

**Issue by nicholasachow** [cmcaine/tridactyl#531]
hey everyone, the newest change to toggle ignore mode on and off doesn't work for mac keyboards (and binding insert keys on a mac, while not impossible, is quite annoying). ignore mode used to be toggled with "I", but now requires "shift+insert". i realize that macs might be a small subset of users for  the extension, but still something to think about

**Comment by bovine3dom** [comment]
See #505 :)

**Comment by nicholasachow** [comment]
Ah, for some reason I did not see this when I looked through. Thanks!
