### ISSUE TITLE
Error processing fillcmdline in 1.9.8pre932-an+fx.xpi

### ISSUE THREAD

**Issue by mrjovanovic** [cmcaine/tridactyl#547]
Using this build from the beta channel, I am getting an `Error: fillcmdline` message when I hit `:`. Using Firefox 60.0 on Ubuntu 18.04.

No issue with the stable branch. Would be happy to provide more info if it's not easily reproduced.

**Comment by mrjovanovic** [comment]
OK, I feel like an idiot. It doesn't happen in a clean profile, if I'm not using firejail.

**Comment by glacambre** [comment]
Still, this is a weird bug. Also you're probably using a very old beta, the current betas are version 1.12+
