### ISSUE TITLE
`set allowautofocus false` breaks js editors (ace & probably others)

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#550]
I'm sure we had an issue but I couldn't find one when searching for the keywords "conflict" and "editor".
Here's an Ace demo to reproduce the issue: https://ace.c9.io/build/kitchen-sink.html

**Comment by bovine3dom** [comment]
What's the conflict?

Ctrl-I doesn't work.

**Comment by antonva** [comment]
If you use the vim mode in the ace editor you're bound to get conflicts. 'u' was the first one I hit. Putting the page on ignore seemed to work just fine though.

**Comment by glacambre** [comment]
Even when pressing <S-Insert>, I can type anything. And I can't paste anything either, be it in normal mode or in ignore mode.

**Comment by cmcaine** [comment]
When I click in the textarea I enter insert mode and everything just works (TM).

Ignore mode also just works for me. `:version` `1.12.0-55-g7429f8c`

**Comment by cmcaine** [comment]
`<C-i>` doesn't work and is unlikely to ever work unless we can work out how to talk to the js controlling the element.

**Comment by glacambre** [comment]
Tridactyl correctly enters insert mode on another computer running debian's build of Firefox 59.0.2 and Tridactyl 1.12.0-275-g268301c.
Pressing <kbd>Shift-Insert</kbd> seems to work too.
Pasting doesn't work though.

**Comment by glacambre** [comment]
I realized that I was once again responsible for the bugs I was experiencing. Using `set allowautofocus true` fixes this bug, both for typing things and pasting things.
I don't understand why typing worked while pasting didn't on my other computer, I'll have to investigate.

**Comment by bovine3dom** [comment]
"BYOB" should be Tridactyl's motto.

**Comment by glacambre** [comment]
After thinking about this for a while I don't really know how this could be fixed since `set allowautofocus false` is working as intended. Having page-specific settings is the best solution I can think of and there's already an issue for this: https://github.com/cmcaine/tridactyl/issues/434

**Comment by bovine3dom** [comment]
Jupyter notebooks with vim bindings are also broken by `set allowautofocus false`.

**Comment by ELLIOTTCABLE** [comment]
Happens over here too!

Maybe I'm missing something — how is this broken-as-intended? Preventing *grabbing* focus, shouldn't prevent me from *giving* me focus!

Technical limitations?

**Comment by glacambre** [comment]
Basically what we're doing is replacing the page's `.focus()` function with ours, which will decide whether the true `.focus()` function should be called or not.

When you click on a JS editor, you're actually most of the time clicking on a dumb `<div>` or `<span>` element and the editor then calls `.focus()` on the right `<input>` element. We have no way to know if the `.focus()` call originated from a click event or not, hence why Tridactyl will prevent elements to be focused even if the focusing originates from a user action.

I'll look into how other projects prevent autofocus when I have the time (https://github.com/cmcaine/tridactyl/issues/791) but this won't be soon.

**Comment by ELLIOTTCABLE** [comment]
Sounds good! Glad to hear it's on the roadmap.

**Comment by glacambre** [comment]
For those who might find this issue while looking for a solution to `set allowautofocus false` breaking js editors, know that you can use `seturl` (see `:h seturl`) in order to set a setting on a specific domain and/or page, e.g. `seturl onlineeditor.org allowautofocus true`.
