### ISSUE TITLE
Check `fixamo` works on OSX and Windows

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#557]
I suspect the hardcoded `/` style paths might break stuff.

**Comment by glacambre** [comment]
If `getProfileDir()` works I think `writePref()` should work for OSX.
I doubt `getProfileDir()` works on windows so `fixamo` probably doesn't either.

**Comment by sirn** [comment]
Want to help confirm that `:fixamo` does work on macOS. Tridactyl 1.12.0pre1145, native 0.1.5, Firefox 60.0. Here's the content of `user.js` after running `fixamo`:

```

user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);

user_pref("extensions.webextensions.restrictedDomains", "");
```

**Comment by vinceau** [comment]
I'm running macOS with Firefox 60.0 with Tridactyl 1.12.0 but whenever I run :fixamo it gives me an "# Error: Not an excmd: fixamo" error.

**Comment by bovine3dom** [comment]
@vinceau it's only available in our betas at the moment, https://tridactyl.cmcaine.co.uk/betas

We'll do a proper release soon-ish, but I'd recommend you use the betas as the AMO only gets released when we can be bothered (which is usually infrequently).

**Comment by xiangsheng** [comment]
I have two profiles on macOS. Everytime I run `:fixamo`, I'm asked to set the profiledir. But I does set it! The output is something like the following,
`profiledir = /Users/xiangsheng/Library/Application\ Support/Firefox/Profiles/5xlxtm7b.default`
I hope that I've escaped the space correctly.

**Comment by bovine3dom** [comment]
@xiangsheng could you file another issue? No-one who develops Tridactyl has a macintosh so we'll have to debug through you : )

I'm closing this issue as I'm pretty sure `fixamo` works on Windows and OSX (most of the time).
