### ISSUE TITLE
Work out how to let `js` and friends accept arguments

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#563]
It would let users do things in a much less hacky way than #562.

**Comment by bovine3dom** [comment]
So #562 becomes:
```
command hackybmarktitlebind !jsb tri.excmds.get_current_url().then(x => tri.excmds.fillcmdline_notrail("bmark " + x + " " + str[str.length - 1]))//
```
We should probably give str[str.length -1] a nice name like "TRI_ARGS" and document it, and perhaps add the // on by default.

**Comment by bovine3dom** [comment]
An obvious solution to this is probably `js [code goes here] -- args`, and we can just split on -- and give the rest to an TRI_ARGV variable.

**Comment by bovine3dom** [comment]
Nope, I meant the first one. The real solution is a parser that allows grouping with quotes etc.

If we split on ` -- ` instead of just `--` that should solve most of your problems, right?

**Comment by glacambre** [comment]
I know it's weird but, to me, it feels even more fragile than just appending "//" at the end of the line. I don't know why but I'm very against adding this kind of syntactic constraint to the command line, it feels wrong. I'd much prefer having to quote my js strings (which should be done by a real parser, I remember using acorn 3 or 4 years ago and it was quite good).

I can't pinpoint exactly why I dislike this idea. I think it has to do with the pattern being able to appear anywhere in the string and thus being a PITA to work around (I'm not sure I'll ever need to `js Native.run("grep pattern -- " + TRI_ARGS)` but I don't want this possibility to be taken away from me, even if `js Native.run("grep pattern -" + "-" + TRI_ARGS)` isn't that much longer to type).

I realize that my arguments aren't very convincing, that they don't go much farther than "waah I don't want this" and that the workaround to the issue I pointed out isn't that inconvenient to implement so if you believe your proposal is the right way to implement arguments for `js`, feel free to ignore me and go forward with implementing your suggestion :)

**Comment by bovine3dom** [comment]
My main problem with your way is that it gets really verbose if you need multiple arguments.

**Comment by glacambre** [comment]
How so ? From what I understand you could access each argument with its index within TRI_ARGS:
```
composite get_array_of_things | js do_something(TRI_ARGS[0], TRI_ARGS[1], TRI_ARGS[2])
// or even
composite get_array_of_things | js do_something.apply({}, TRI_ARGS)
```

**Comment by bovine3dom** [comment]
Sketch of my way:
```js

function js(...str){
[jsstr,TRIARGS] = str.join(" ").split(" -- ")
eval(jsstr)(TRIARGS)
}

```
`js alert(TRIARGS[0] + TRIARGS[1] + TRIARGS[2]) -- this is sensible`
Sketch of your way:
```js

function js(...str){
jsstr = str.join(" ")
TRIARGS = str.reverse()
eval(jsstr)(TRIARGS)
}

```

`js alert(TRIARGS[0] + TRIARGS[1] + TRIARGS[2])// sensible is this`

Or am I missing something? I think the latter one is weirder.

**Comment by glacambre** [comment]
I think our misunderstanding comes from how arguments are passed to `js`.
In my previous example, I assumed that `get_array_of_things` returned an array and this array was passed "as is" as `js`'s last argument. I thought [composite](https://github.com/cmcaine/tridactyl/blob/a8995d5f6292c7f38e45def94a99d6a3a4cf5ed7/src/excmds.ts#L1658) did something like this:
```ts
// split on pipes
cmds = cmds.join(" ").split("|")
// For each piped command
cmds.reduce((piped_value, pipe_cmds) => {
    // Split on semicolons
    let semicolon_cmds = pipe_cmds.split(";")
    // Parse the first command
    let [semi_cmd, semi_args] = exmode_parser.parse(semicolon_cmds[0])
    // Execute it with its arguments + the one that it receives from the pipe
    let returned = semi_cmd.apply(semi_args.concat([piped_value]))
    // Execute all other commands without piping
    for (let i = 1; i < semicolon_cmds.length; ++i) {
        [semi_cmd, semi_args] = exmode_parser.parse(semicolon_cmds[i])
        returned = other_cmds[i].apply(semi_args)
    }
    // Return the result of the last executed command so that it may be piped to the next one
    return returned
}, null)
```
Hence, the following code:
```ts
alias one_two_three js [1, 2, 3]
composite one_two_three | js console.log(TRI_ARGS[0], TRI_ARGS[1], TRI_ARGS[2])
```
Would have given the following output:
```ts
1 2 3
```

But I was wrong and composite instead concatenates the excmd and the piped value and then calls controller.acceptCmds(). I think this approach has unnecessary limitations: this prevents functions from returning arrays or objects because these are destroyed when doing string concatenation. With the way composite currently behaves and your suggestion being implemented, this:
```ts
alias one_two_three js [1, 2, 3]
composite one_two_three | js console.log(TRI_ARGS[0], TRI_ARGS[1], TRI_ARGS[2])
```
Would have output this:
```
[object Object] undefined
```

**Comment by bovine3dom** [comment]
Honestly, I don't know. I made it the way it is because that's easier to reason about - everything's an ex command. It could be fine.

Feel free to make a PR and have a play; `js` and proper pipes aren't in the release yet so I'm happy to accept reasonably breaking changes.

**Comment by glacambre** [comment]
Can this be closed?

**Comment by bovine3dom** [comment]
I was going to leave it open for a bit to remind me to test it more thoroughly :)
