### ISSUE TITLE
Commandline ':' breaking layout

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#572]
I don't know if it because of [7add357](https://github.com/cmcaine/tridactyl/commit/7add35714d68c58ee3a0ae5be303ac8868bc87f4), probably:

![screenshot_20180519_123439](https://user-images.githubusercontent.com/8964036/40270336-b6209e0c-5b61-11e8-9d22-2397b11143a3.png)

**Comment by bovine3dom** [comment]
What `version`? Is this your own branch or one of our beta builds?

**Comment by bovine3dom** [comment]
I can only reproduce this if I make the Firefox window as small width-wise as it will go and zoom in a huge amount. :/

**Comment by caputchinefrobles** [comment]
It is my own branch based on version 1.12.0-697-gcd87389 

I'm using with FF-dev 61.0b4 in a 15" wide laptop. I dont know this information helps much

**Comment by caputchinefrobles** [comment]
I  got what happened. Since Im working on *.css in a different folder than it is at master branch, commandline.html got merged without the changes on css/commandline.css, which were at static/commandline.css.

**Comment by bovine3dom** [comment]
@caputchinefrobles you don't need to worry about keeping up to date with Tridactyl - just make your changes on your own branch, and we'll sort out all the merging later :)
