### ISSUE TITLE
disable tridactyl on some sites

### ISSUE THREAD

**Issue by GianniGi** [cmcaine/tridactyl#587]
Hello, I would like to ask the option to disable tridactyl on some sites. For example in gmail I find much more useful to be able to use the google defined shortcuts. Thanks.

Furthermore.... In the addon menu I can't find anymore the tridactyl options.... where have they gone?

**Comment by glacambre** [comment]
Hi, we've already talked about disabling Tridactyl here: https://github.com/cmcaine/tridactyl/issues/57 and here: https://github.com/cmcaine/tridactyl/issues/158 , if there's anything not covered in these two issues, feel free to ask more specific questions :)

I'm not sure I understand what the "addon menu" you're talking about is and what its options were though, could you give me more details? How did you access the addon menu and what options aren't available anymore?

**Comment by GianniGi** [comment]
Where are the options to configure tridactyl?

**Comment by bovine3dom** [comment]
@GianniGi use `:set option value`. You can view possible options and their current values with `viewconfig`. You can try searching the `help` page for the configuration options if you want more information about them.

The `:tutor` explains most of this :)

**Comment by GianniGi** [comment]
thanks, not very user friendly, but surely vimesque

**Comment by vikeri** [comment]
For anyone looking, it's now in the main README:
>How do I disable Tridactyl on certain sites?
>You can use blacklistadd, like this: blacklistadd mail.google.com/mail. See :help blacklistadd. Also note that if you want something like the passkeys or ignorekeys features vimperator/pentadactyl had, you can use bindurl. See :help bindurl.

**Comment by mike1808** [comment]
As this issue shows in Google when searching "tridactyl ignore domain", here is the command to disable Tridactyl on all domain not only specific URL:

```
autocmd DocStart YOUR_DOMAIN mode ignore
```

And to enable it back:

```
autocmddelete DocStart YOUR_DOMAIN mode ignore
```

**Comment by Davenchy** [comment]
Using the `autocmd` or `blacklist` methods isn't stopping Tridactyl from injecting its code into the page. I need a way to completely block Tridactyl from injecting anything on `localhost`. 

I'm working with Next.js in development mode, and the injection is causing an error message to appear, so I’m looking for a solution to prevent this.

![image](https://github.com/user-attachments/assets/29a4160c-c57c-424c-b5d8-3451cddde6b1)

**Comment by bovine3dom** [comment]
1) I'd recommend against using that kind of bloated framework because it breaks all sorts of extensions (as you've just found out), see #5050. The error claiming that a "browser extension ... _messes_ with the HTML" tells you all you need to know about whether they are good citizens of the internet. Better to use stuff that renders quickly on the client like a web component based library such as Lit :)

2) you can disable Tridactyl with `:seturl http://localhost superignore true`

**Comment by Davenchy** [comment]
Honestly, I completely agree—Next.js can be a real headache.
