### ISSUE TITLE
Mention that hint characters should be typed in lowercase everywhere hinting is mentioned

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#588]
Spurred on by https://github.com/cmcaine/tridactyl/pull/130#issuecomment-390550106.

**Comment by sumnerevans** [comment]
Is this just a documentation change?

**Comment by bovine3dom** [comment]
@sumnerevans yeah.

```fish
[I] ~/p/t/src (master|✔) $ rg -l hint **.md **.ts
static/clippy/tutor.md
static/clippy/settings.md
static/newtab.md
background.ts
config.ts
content.ts
controller.ts
dom.ts
excmds.ts
static/clippy/hint_mode.md
hinting.ts
hinting_background.ts
keydown_content.ts
messaging.ts
requests.ts
static/clippy/normal_mode.md
state.ts
finding.ts
```

Most of those files are internal, but docstrings on excmds.ts become help, so it should be mentioned there, somewhere on newtab.md, and probably just once in the tutorial.

Do you feel like doing it?

**Comment by sumnerevans** [comment]
Yes. I'd like to do this.
