### ISSUE TITLE
Default page for a new window is Google

### ISSUE THREAD

**Issue by hppavilion1** [cmcaine/tridactyl#59]
While google is the most common homepage, not everyone uses it; however, it is the default return value for `forceURI` in [`excmds.ts`](https://github.com/cmcaine/tridactyl/blob/bf6ac3e618026e81a7a6ef0e059f4ada1504452b/src/excmds.ts). When `forceURI` is called and it has to fall back on a default, the default should be the user's default new tab page or- if that is not feasible- at least a configuration option.

**Comment by bovine3dom** [comment]
The configuration option for default new tab is blocked by our general configuration system, so that will have to wait a short while.

**Comment by hppavilion1** [comment]
Oh, I was wondering about that. I downloaded to check the code, but couldn't see the issue. That explains it; perhaps the default page should be for the published release, with a separate branch for revisions that are not yet in the official release??

**Comment by bovine3dom** [comment]
The beta versions on the AMO are built from master a few times a day (it does say this in the readme). As the project matures, I suspect versions will get their own branches.

Do you think master being the current released version would be much clearer?

**Comment by cmcaine** [comment]
Moving forward, non-beta releases will be tagged. We'll keep with the "one-main-branch" approach until development slows down a bit.
