### ISSUE TITLE
Windows canary / build bot

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#590]
https://www.appveyor.com/ offer free Windows build bots. It's probably worth setting one up so that we get told when we break the build process for people developing on Windows.

It might be a minor faff to figure out how to set it up to use MSYS2.

**Comment by bovine3dom** [comment]
As I understand it AppVeyor can be totally configured by a YAML file in the repo, so it's quite well suited to a PR if you just make an account and set it up on your own Tridactyl repo.

I had a look at it myself but there were a lot of settings...

As for what we want - it just wants to build Tridactyl and see if the build gives any errors, i.e. `npm run build`.

We haven't bothered with much testing yet. Eventually it would be cool to set up geckodriver but I suspect that that is a big job.

**Comment by gsbabil** [comment]
Alright, I think you are just after the `appveyor.yml`. I'll send a separate PR for this. Thanks.

**Comment by gsbabil** [comment]
@bovine3dom 

Just submitted PR #620. Let me know once you have had a chance to try it Things look good on my end so far. We may need to extend it a bit to get the "artifacts" out and properly distribute/deploy.

Thanks.

**Comment by bovine3dom** [comment]
> We may need to extend it a bit to get the "artifacts" out and properly distribute/deploy.

I don't think we need this at the moment - our own build bot is ticking along merrily. If we ever lose access to that then we can play with this.

Leaving this issue open as I need @cmcaine to give me access to this repo's settings before I can make the results of the builds public on each PR, etc.
