### ISSUE TITLE
Smooth scroll (Issue #54 and PR #467) alternative

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#600]
I know this topic has been of much discussion, specially with @glacambre #467, but I'd like to make a suggestion, kind of, based on @glacambre PR but addressing the problems with page loading and tab changing with the smoothscroll config.

The only problem I see with this approach is that we don't have much control over css scroll-behavior, then some might think its too slow or unresponsive. 

For now, I think that could work as an alternative to the lack of this feature. Here it is: [diff](https://github.com/cmcaine/tridactyl/compare/master...caputchinefrobles:smoothscroll_idea?expand=1)

We could use a possible static/css/scroll-behavior.css to include more things about it instead of {code: "css code here"}.

Could we make it a PR, or is it far from the real deal?

**Comment by glacambre** [comment]
This is actually very close to what I attempted here: https://github.com/cmcaine/tridactyl/pull/467/commits/fbc8262124ba59783a813bd934c452f7a14af12e
I also tried using insertCSS after bovine3dom mentioned it but it didn't improve the situation.

Just like mine, your patch doesn't seem to work on http://www.angelfire.com/super/badwebs/ or https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html . Implementing smooth-scrolling ourselves should fix that though.

**Comment by caputchinefrobles** [comment]
Testing through these I got the following error on main.html:4 SyntaxError: expected expression, got '<' (on badwebs)

Inspecting that element there was: 

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
  
  <script><head>
```
Could that be the reason why it's ununderstandably broken? 

The nvidia programming guide simply freezes my pc with a page with over 18000 lines of html code and has some mixed content errors. 

But just for the sake of curiosity why does it have to work on those? Just because if it does there'll be no match to break smooth scroll, I guess...

**Comment by glacambre** [comment]
>Could that be the reason why it's ununderstandably broken?

Nope, it's because it's using frame(sets). The (horribly disgusting) code I tried in https://github.com/cmcaine/tridactyl/commit/6b44f862fab651e6b10f5fed0c9ba86b44eced03 made it work but broke everything everywhere else.

>The nvidia programming guide simply freezes my pc
Does this also happen when using a "normal" Tridactyl (without your or my patches)?

>But just for the sake of curiosity why does it have to work on those?
I've talked a bit about Tridactyl with different users and a lot of them said that they felt Tridactyl was buggy (this was probably before we disabled updates). In my opinion, having a feature work on some sites and not on others would probably contribute to the feeling of bugginess, and I'd rather avoid that. But really, @bovine3dom and @cmcaine are the bosses and they're probably the one who should make this kind of decision.

I started implementing re-implementing smooth scrolling btw. I should be done this evening/tomorrow I think.

**Comment by bovine3dom** [comment]
> But just for the sake of curiosity why does it have to work on those? Just because if it does there'll be no match to break smooth scroll, I guess...

I tried out @glacambre's PR a while ago and it made the browser feel very slow in general. I think the CSS smooth scroll is quite different to what Firefox does.

So, yeah, if it just didn't work on those two sites, that would be kind of ok - but it just felt a bit bad in general from what I can recall, which is less OK.

(FWIW: smooth scrolling always feels a bit bad and you shouldn't use it :) )

**Comment by glacambre** [comment]
@bovine3dom: I think what you tried was the commit that attempted to make scrolling work everywhere, even on frames. I don't remember https://github.com/cmcaine/tridactyl/pull/467/commits/de0d3fd64fad0a4fa0df47b699f08d82ceab5ced and https://github.com/cmcaine/tridactyl/pull/467/commits/fbc8262124ba59783a813bd934c452f7a14af12e making the browser slow (I could be wrong though).

**Comment by bovine3dom** [comment]
I guess I can try it again. I thought I was waiting on you rolling your own...
