### ISSUE TITLE
Help reference missing/wrong in newtab

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#602]
There a reference to help page in newtab but it's missing or wrong: 
help: moz-extension://abcd.../static/docs/modules/_excmds_.html

I think it should be:
static/docs/modules/_src_excmds_.html

I thought I've seen a commit fixing this but I'm not finding it, sooo Issue filed.

**Comment by bovine3dom** [comment]
Thanks!

**Comment by bovine3dom** [comment]
Fixed in 00eced4.
