### ISSUE TITLE
Clear urlbar on page enter

### ISSUE THREAD

**Issue by mustaqimM** [cmcaine/tridactyl#605]
I have tridactyl set to open `New Tab Tools` when opening a newtab, but it doesn't clear the urlbar so I still see `moz-extension://1d317fe7-fdd9-4a74-9b2c-73bfd09a314d/newTab.xhtml` and have to manually each time press `C-u` before I can search for something, is there a way to run a command automatically when opening a page?

**Comment by glacambre** [comment]
I think I can't reproduce this issue.
This is what I did:
- First install Tridactyl
- Then install New Tab Tools
- Then run `:tabopen` in any tab where Tridactyl works
This opened a new tabwith an empty URL bar selected.

Is this what you did? Also, I don't think we're responsible for the URL you're seeing, Tridactyl's newtab url is `moz-extension://long-random-id/static/newtab.html`.

**Comment by mustaqimM** [comment]
@glacambre I mean I set a `newtab` with `set newtab moz-extension://1d317fe7-fdd9-4a74-9b2c-73bfd09a314d/newTab.xhtml `. Which does open the extension New Tab Tools, but it has the url like [this](https://i.imgur.com/aQY4r7C.png)

**Comment by bovine3dom** [comment]
I'm surprised that that works at all.

We can't hide URLs from the URL bar by design.

We could just shove everything in an iframe but I think that would be a bad idea in general.

**Comment by glacambre** [comment]
Yeah, this is surprising. I think we tried explicitly setting the new tab url to moz-extension://something before and it didn't work. Also, it might break on updates since a new UUID is generated on each extension installation.

I'd recommend uninstalling New Tab Tools and reinstalling it so that it sets itself as new tab page using Firefox's mechanism. I think this would solve your issue.

**Comment by mustaqimM** [comment]
@glacambre This does solve the issue but doesn't Tridactyl show a message saying it needs to be set as the home page until Firefox api are released? That is why I did it this way

**Comment by bovine3dom** [comment]
@mustaqimM that's only so that you get access to Tridactyl on that page. If you set it to any `moz-extension` that isn't our own, we don't have access anyway.

**Comment by mustaqimM** [comment]
@bovine3dom I see, I was under the impression Tridactyl needed to be set as the home page so it can apply something and then it switches to whatever home page you set with the `set newtab` command. Anyway thanks for a great extension, please close this issue if you wish
