### ISSUE TITLE
Link hinting on elements with target _blank triggers pop-up blocker

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#61]
Example - the link "bundle" on this page http://www.pcgamer.com/get-cities-skylines-and-six-other-simulators-for-10-in-new-humble-bundle/

The solution is probably to just rewrite any target _blank to open in the current tab.

**Comment by cmcaine** [comment]
Fixed in: 1469d4dc8547252854d8726f443370bc315a1c10
