### ISSUE TITLE
 The version of Tridactyl you are using was made by nobody

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#612]
At least that's what `:credit` claims on beta builds.

I'm not sure where the problem might come from (is the git directory cloned on your build server?). Also, I think the two seds here:
https://github.com/cmcaine/tridactyl/blob/a8995d5f6292c7f38e45def94a99d6a3a4cf5ed7/scripts/authors.sh#L7
Could be replaced with `sed 's@\(.*\)@<p>\1</p>@'`

**Comment by bovine3dom** [comment]
There's something strange going on with the build server, yeah. It works fine if I do `npm run build` on the build server. I haven't had time to investigate it further.

Regarding your second remark: I've always been told that two seds are better than one.

**Comment by glacambre** [comment]
Fixed by https://github.com/cmcaine/tridactyl/commit/e710296d7003c1fa2d9b13fa7cd427e90ca5c0f2
