### ISSUE TITLE
# Error: Error processing pushKey([object Object]) TypeError: modeState is undefined

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#613]
I can reliably reproduce this issue. First `bind v hint -W exclaim_quiet mpv --ontop --keepaspect-window --profile=protocol.http`. Then, navigate to http://example.org. Then, rapidly press <kbd>v</kbd><kbd>s</kbd>. Close the mpv window, close the commandline by pressing <kbd>Esc</kbd> and try to press any key (e.g. <kbd>d</kbd>), you should see the error message popup.
I don't know if it makes much of a difference but I'm using i3 with this rule: `for_window [class="mpv"]                    floating enable`. This means that firefox isn't resized when mpv is started.

**Comment by bovine3dom** [comment]
Is this the same as #449?

**Comment by glacambre** [comment]
I don't think so, here the problem is that modeState is undefined, in #449 it seems that some object was GC'd while still being referenced somewhere and in #584 I think closing the tab probably kills the native messenger in some way. The good news is, all of these are reproducible so if we fix one of these we'll be able to check whether the others are fixed too :D

**Comment by fortytw2** [comment]
This happens to me, too - nothing special just firefox 60 on arch.

Don't have a good/reliable reproduction though, will comment again if I can get it to keep happening
