### ISSUE TITLE
disable on some websites

### ISSUE THREAD

**Issue by GianniGi** [cmcaine/tridactyl#631]
How do I disable tridactyl on certain websites?

It is very important, for my sanity, to disable it on the more important websites, like gmail. Sometimes I get an erratic behaviour, that opens and closes tabs, and that sends an email while I'm still writing. Please kindly add this option.

**Comment by glacambre** [comment]
Hi, you've already opened an issue about this: https://github.com/cmcaine/tridactyl/issues/587 .

**Comment by GianniGi** [comment]
sorry, the notification didn't show up
