### ISSUE TITLE
Support FF 58

### ISSUE THREAD

**Issue by ypaq** [cmcaine/tridactyl#65]
Just tried out the developer edition of Firefox 58.0b4 (64-bit) on OS X which didn't work at all.

**Comment by ypaq** [comment]
NVM.. it does work 👯

**Comment by bovine3dom** [comment]
What was wrong? Is there anything special you needed to do to get it to work on a Mac?

**Comment by ypaq** [comment]
It would only work on a new tab. For example, after I installed the beta via the add-ons manager I could not hit `b` to see the open tabs. Once I created a new tab instructions for tridactyl came up and I could use it. Not sure if this is Mac or FF dev edition specific.

**Comment by bovine3dom** [comment]
Ah, no, that's a universal issue with all web extensions - they are not allowed to run on addons.mozilla.org.

Unfortunately the description we are allowed on the AMO is so short that there isn't really room to explain that.
