### ISSUE TITLE
Release 1.13

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#653]
I'm going away for a week soon and won't have much time for Tridactyl. I'd like to get a release out today or tomorrow. I would appreciate it if someone could help with the following:

- Changelog needs updating
- Help / new tab etc. probably needs updating to document new features
- I'd appreciate it if someone with a slow computer would check if scrolling has got much slower since the last stable release.

**Comment by glacambre** [comment]
I slowed my CPU down by running `for i in 0 1 2 3 ; do _ cpufreq-set -c $i -u 810MHz ; done`. Scrolling is a bit choppy but now slow.

**Comment by bovine3dom** [comment]
Blocked by #656.

Thanks for changelog, glacambre : )

**Comment by glacambre** [comment]
I think this can be closed :)
