### ISSUE TITLE
Website specific bindings

### ISSUE THREAD

**Issue by akiross** [cmcaine/tridactyl#660]
Hello and thanks for tridactyl!
I was wondering if there is a possibility to configure per-site bindings. For example, GMail has great keybindings, but I would like to keep **some** functionalities of tridactyl active, without having to switch continuously in and out ignore-mode (Shift+Ins). Github has bindings as well, therefore I would use a different key mapping from it, etc.
Thanks

**Comment by bovine3dom** [comment]
This is planned as part of #434; there's another issue that talks about it at length where it is called `passkeys`.

Thanks for the feedback : )
