### ISSUE TITLE
Better font for hints

### ISSUE THREAD

**Issue by OliverUv** [cmcaine/tridactyl#661]
It'd be a big usability improvement if the default font for hints (`f`/`F` hints, I mean) had disambiguated `l` and `I` characters. Currently they look the same.

**Comment by bovine3dom** [comment]
I replied on Riot, but maybe you didn't see it:

```
07:29:09 | Github [@cmcaine:matrix.org] | [cmcaine/tridactyl] OliverUv opened issue #661: Better font for hints [open] - https://github.com/cmcaine/tridactyl/issues/661
-- | -- | --
07:29:36 | OliverUv (IRC) | ^^
07:31:06 | bovine3dom | OliverUv: they should be all caps
07:31:26 | bovine3dom | So you shouldn't see any lowercase L's
07:32:19 | bovine3dom | If you're playing with the hint CSS to display lowercase characters then you can just change the font in the same place
```
https://view.matrix.org/room/!xmubtggllUtLrQiGyn:matrix.org/?anchor=$15284431395176953mWyFs:matrix.org&highlight

Where are you seeing `l`s?

**Comment by OliverUv** [comment]
@bovine3dom oh damn, that's just me being confused. I'm just not used to fonts that represent I as a simple line, so it always confused me, even though I should have figured out that the hints were all caps.
