### ISSUE TITLE
f key and Youtube

### ISSUE THREAD

**Issue by nuto-github** [cmcaine/tridactyl#664]
(sorry for my english !)
Hi, I'm used to hit "f" to switch fullscreen/windowed video with Youtube.
Is it possible to modify the hint mode key (f) or at least deactivate tridactyl on the Youtube page ?

Thanks for this wonderful tool anyway !

**Comment by bovine3dom** [comment]
Kinda - `blacklistadd youtube.com` to disable Tridactyl totally.

Just disabling `f` isn't possible yet. See https://github.com/cmcaine/tridactyl/issues/57#issuecomment-346710840, #660 and #434.

Glad you like Tridactyl : )

Closing as duplicate of #57.
