### ISSUE TITLE
Inconsistent functionality depending on where you click in gitter.im

### ISSUE THREAD

**Issue by jamesblau** [cmcaine/tridactyl#67]
Some panes seem to block tridactyl if they have focus. (Other than the input box, of course.)

If you click non-active parts of the *left* side of the screen, tridactyl seems to stay active -- for example, if you click on the word "GITTER" in the upper-left, or if you click the whitespace to the left of "YOUR SUGGESTIONS." (I.e., upper-left or lower-left works.)

If you click some parts of the *right* side of the screen, tridactyl shortcuts don't work. This includes clicking the empty space around one's user icon or the whitespace below the "PEOPLE" icons -- in other words, the upper-right or the lower-right. Text is not being entered, so it's not that the input box has focus.

So left works, right doesn't. Weird! Persists through reloading firefox.

Using Firefox 57.0 in Ubuntu 17.10.

**Comment by cmcaine** [comment]
This is an iframe issue: tridactyl currently loads into only the top level frame.

We're aware of the cause and expect to fix it Soon TM. :)
