### ISSUE TITLE
yanktitle is broken

### ISSUE THREAD

**Issue by tjim** [cmcaine/tridactyl#673]
Looks like it is missing

    content = (await activeTab()).title

in excmds.ts

**Comment by glacambre** [comment]
It'll be fixed as part of #666 (see https://github.com/cmcaine/tridactyl/pull/666/files#diff-541faaaa3b5d3979be7ea476ef8a1cf2R1994).

**Comment by bovine3dom** [comment]
Fixed in e2986ecc4db67d680829c136df58d5e98c5b48c1. Sorry @glacambre.

**Comment by glacambre** [comment]
You shouldn't apologize for fixing bugs :p

**Comment by tjim** [comment]
Thanks!

**Comment by bovine3dom** [comment]
I also added `yt` and `ym` binds for yanktitle and yankmd (Markdown formatted link) :)
