### ISSUE TITLE
Is it possible to make JK scrolling as smooth as Safari?

### ISSUE THREAD

**Issue by nikitavoloboev** [cmcaine/tridactyl#679]
I was using [sVim](https://github.com/flipxfx/sVim) vim extension in Safari and in there using `h/j` keys to scroll the same as scrolling with a trackpad (very smooth).

However with triactyl trying to use hj keys to scroll through the page is very janky (it jumps in chunks). Is it possible to somehow make tridactyl scrolling as smooth as [sVim](https://github.com/flipxfx/sVim) and Safari or its a limitation of Firefox?

**Comment by glacambre** [comment]
We already have an issue about scrolling not being smooth: https://github.com/cmcaine/tridactyl/issues/627

**Comment by bovine3dom** [comment]
Closed in favour of #627.

**Comment by mustaqimM** [comment]
@bovine3dom I think this issue is slightly different.
> it jumps in chunks  

Using `j` jumps about ~10 lines whereas using the `down` key jumps ~3 lines. #627 is about smooth scrolling

**Comment by glacambre** [comment]
@mustaqimM If you want `j` to scroll less you need to rebind it, e.g. `bind j scrollline 1` to jump from line to line.

**Comment by Qu4tro** [comment]
If you've ended up here and you're guessing if you can `bind k scrollline -1`, the answer is yes.

**Comment by ahungry** [comment]
Thanks for the comments, I found what I wanted (scroll in smaller intervals).
