### ISSUE TITLE
Refreshing the page jumps to the top of the page

### ISSUE THREAD

**Issue by oscarfv** [cmcaine/tridactyl#680]
On some pages such as this:

https://stackoverflow.com/questions/16888339/what-is-the-simplest-way-to-write-to-stdout-in-binary-mode

if the user scrolls down and then refreshes the page (Ctrl-R, `r` or clicking the button) the position jumps to the top. This didn't happen until recently, possibly the latest stable release introduced the problem.

**Comment by glacambre** [comment]
This is most likely caused by the jumplist (I was going to tell you to take a look at `:h jumpprev` but I didn't document it enough, sorry about that :/). If you scroll down, wait for a few seconds and then reload the page, you should be brought back to where you were.

**Comment by oscarfv** [comment]
Scrolling down and refreshing the page several hours later still jumps to the top.

Can't you reproduce with the page I mentioned?

FWIW, the only extensions I have apart from Tridactyl are uBlock Origin, uMatrix and "Dark background and light text". If I disable them all except tridactyl the problem persists. It only goes away if I disable tridactyl.

**Comment by glacambre** [comment]
Nope, I can't reproduce this bug even on the page you mentioned :/
I'm using Tridactyl v1.13 and Firefox 60.0.1 on linux. Does this bug also happen with a clean profile?

**Comment by davidsierradz** [comment]
I can reproduce on [https://liquipedia.net](https://liquipedia.net/dota2/The_International/2018/Main_Qualifiers/North_America), Tridactyl v1.13.1pre1455 and Firefox 61.0b12, if I disable Tridactyl the refresh don't scroll to top.

**Comment by glacambre** [comment]
@davidsierradz : Can reproduce, thank you for posting this link! I'll investigate. If I can't find a fix, a good workaround is to use <C-i><C-o>, it'll bring you back to the last position stored in the jumplist.

**Comment by oscarfv** [comment]
I just updated to 1.13.1 and the problem persists.

**Comment by oscarfv** [comment]
BTW, the `<C-i><C-o>` workaround mentioned above doesn't work either, so maybe the bug reproduced by @davidsierradz and fixed in #730 was a different one.

**Comment by oscarfv** [comment]
@glacambre : the bug happens with a clean profile, but in a weird way: successive refreshes either all show the problem or don't. Almost all the time the problem shows.

I experimented with this page:

http://www.aemet.es/es/portada

**Comment by oscarfv** [comment]
@glacambre : just installed tridactyl-1.13.1pre1686-an+fx.xpi. The problem persists.

It is weird, though, as it may work on some tabs for several attempts while failing on other tabs (with different sites).

Right now it is working on

http://www.aemet.es/es/portada

and failing on

http://www.meteogalicia.gal/web/index.action

On the tridactyl beta download page it works if I move the focus out of the Filter edit box. Then on successive attempts the edit box gets the focus again and the vertical position jumps to the top. Or not. It is quite erratic.

I think that you fixed a real bug, but some other persists. The behaviour previous to this update was the sum of the bug you fixed and the bug(s) that remains. Now things improved a bit.
