### ISSUE TITLE
The default highlight colors are gross

### ISSUE THREAD

**Issue by sumnerevans** [cmcaine/tridactyl#69]
![2017-11-17-15 42 09](https://user-images.githubusercontent.com/16734772/32972130-dce95aae-cbad-11e7-85ec-07198ba05703.png)

These colors are very sub-optimal.

**Comment by bovine3dom** [comment]
We just copied Vimperator, with minor changes to padding and font. I quite like them, but then I have been using Vimperator for ~4 years.IMO, the grossness ensures that it will always clash with every website ever (with perhaps the exception of ww.reddit.com/r/ooer ) and therefore be readable. Ultimately, we'd like to make it user configurable.Do you have any suggestions? We could potentially include a number of default themes.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 17 November 2017 10:42 pmTo: tridactyl@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [cmcaine/tridactyl] The default highlight colors are gross (#69)  
These colors are very sub-optimal.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mrlinuxfish** [comment]
I started using this plugin because my favorite plugn vimfx is no longer supported. If possible I would like to have the option to use hint styling like vimfx used where all the hints are in yellow boxes (no link highlighting) and the active option is green. I haven't seen another plugin do this, but it is really useful.

**Comment by cmcaine** [comment]
@mrlinuxfish, @sumnerevans: You can try out different styles by going to the new tab page, hinting it, opening the dev panel (F12 or Ctrl-k), and finally editing hint.css in the *style editor* panel.

Once you have something you like, save it and post it here and we'll work out how to make it configurable for you.

**Comment by azuwis** [comment]
Hint style css of VimFx is [here](https://github.com/akhodakivskiy/VimFx/blob/master/extension/skin/style.css#L77-L93).

Did a bit modification of hint.css, and got similar result:

![2017-11-21-21 10 41](https://user-images.githubusercontent.com/9315/33074266-821fe75e-cf00-11e7-9c2f-e480a904532c.png)


    span.TridactylHint {
        position: absolute;
        font-family: sans-serif;
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
        color: black;
        background-color: #ffd76e;
        border-color: rgba(0, 0, 0, 0.4);
        border-width: 1px;
        min-width: .75em;
        border-style: solid;
        padding: 0 1pt;
        text-align: center;
        z-index: 2147483647;
    }

    /* .TridactylHintElem { background-color: yellow;  color: black; } */
    .TridactylHintActive { background-color: #88FF00; color: black; }

**Comment by McSinyx** [comment]
I'd suggest picking from the [Tango color palette](http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines#Color_Palette):

> The Tango icon theme's goal is to make applications not seem alien on any desktop.

![](http://tango.freedesktop.org/static/cvs/tango-art-tools/palettes/Tango-Palette.png)

**Comment by mrlinuxfish** [comment]
The style @azuwis posted is very close to the vimperator style. The only difference is in vimperator, the active link has a green background. This green highlighted option is usually the option which is most useful which makes finding it really easy. Most other vim control extensions don't have this feature, but I think it is quite beneficial to quickly following links.

**Comment by bovine3dom** [comment]
@mrlinuxfish the non-Vimperator extensions have uniform hint lengths so the highlight isn't needed, as you never press enter.

Thanks @azuwis, I'll add it as an option once we finish/start user configuration.

**Comment by bovine3dom** [comment]
I think the hints are less objectionable now. Feel free to disagree with me and I'll reopen this.

**Comment by nilsbecker** [comment]
I really dislike the highlighting of page elements and would much rather have only the hint letters displayed. (like vimium etc) is there any way to do that currently? I really feel the element highlighting adds nothing to usability but yellow flashiness.

**Comment by bovine3dom** [comment]
`:colours shydactyl`. If you want a less extreme makeover, the easiest thing to do is to use userContent.css to override our CSS.

**Comment by nilsbecker** [comment]
hi, thanks for the response! i tried `:colors shydactyl` and for me this made the highlighted rectangles that cover the full clickable areas slightly paler. but it did not completely get rid of them as i had hoped. i will try to create a userContent.css file.

**Comment by nilsbecker** [comment]
actually, can i just copy and paste the css from https://github.com/tridactyl/tridactyl/issues/69#issuecomment-346022177 into `<profile_folder>/chrome/userContent.css` ? or would i have to modify some hint.css that is part of the tridactyl distribution?

**Comment by nilsbecker** [comment]
or, after reading the `:colourscheme` help, should i create a new theme .css and put it in the config folder with these contents?

**Comment by bovine3dom** [comment]
You can do it either way. `userContent.css` is easier.

That comment will probably get you some of the way there but you'll need to have something like `.TridactylHintElem{background-color: unset}` to remove the outlines.

**Comment by nilsbecker** [comment]
hmm. i created a `userContent.css` file but these lines in it:
```
span.TridactylHint {
    position: absolute;
    font-family: sans-serif;
    font-size: 32px;
    font-weight: bold;
    text-transform: uppercase;
    color: black;
    background-color: #ffd76e;
    border-color: rgba(0, 0, 0, 0.4);
    border-width: 1px;
    min-width: .75em;
    border-style: solid;
    padding: 0 1pt;
    text-align: center;
    z-index: 2147483647;
}

.TridactylHintElem { background-color: unset;  color: black; } 
.TridactylHintActive { background-color: #88FF00; color: black; }
```
don't seem to do anything at all. i tried to increase the hint font size to see if this is picked up at all and is does not seem to be. i did enable the "legacy stylesheets" option in the global config, and i have checked that `* { font-family: serif ! important; }` in the same file does change the global font. so the .css seems to be picked up by ff.

**Comment by glacambre** [comment]
Could you try adding `!important` at the end of your css statements, 
e.g. "background-color: unset !important"? This might be required if 
Tridactyl's CSS rules take precedence.

**Comment by nilsbecker** [comment]
yes! that did it. for the background color. is there a way to globally say "everything here is important"?

**Comment by glacambre** [comment]
I don't think so but I could be wrong, I'm far from being a CSS expert :).

**Comment by nilsbecker** [comment]
it's getting better. however putting `unset !important` as background color does not have the desired effect of removing any background changes in the element. instead, formerly background-colored elements become uncolored. is there a way to say "don't change the background"? -- clearly also not a css expert

**Comment by bovine3dom** [comment]
You could try inherit rather than unset, but I'm just guessing : )

**Comment by nilsbecker** [comment]
thanks, i tried that but then the elements seem to inherit from some other element higher up on the webpage. so they also change colors sometimes in nonsensical/unreadable ways.
