### ISSUE TITLE
Hint mode also makes firefox fullscreen on youtube.com

### ISSUE THREAD

**Issue by mrlinuxfish** [cmcaine/tridactyl#70]
When using hint mode to select a video on youtube if there are already hints showing, firefox goes into fullscreen mode. Pressing `f` again will make firefox not fullscreen, but the hints will not go away after firefox goes fullscreen.

**Comment by johnbeard** [comment]
You can press `I` to disable Tridactyl key listening, and `Shift-Esc` to re-enable. This was an issue with Vimperator too, IIRC.

But it seems strange that the `f` key makes it though Tridactyl to the YouTube key event handler. I'd expect hint mode, or YT fullscreen, but not both.

**Comment by cmcaine** [comment]
The event suppression logic was very leaky because it was waiting for the key sequence parser that I keep meaning to finish.

I've made the suppression much more strict and that fixes the issue.
