### ISSUE TITLE
No hotkey works in addons.mozilla.org

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [cmcaine/tridactyl#71]
All the default key binds and custom binds won't work in any page of addons.mozilla.org

**Comment by johnbeard** [comment]
No WebExtension plugin will work on addons.mozilla.org in FIrefox, it's a built-in security limitation.

**Comment by robehickman** [comment]
I'm inclined to block access to these pages because it breaks flipping between tabs.

**Comment by bovine3dom** [comment]
Our main effort towards mitigating that is https://bugzilla.mozilla.org/show_bug.cgi?id=1215061.

**Comment by bovine3dom** [comment]
Closing in favour of https://github.com/cmcaine/keyboard-api.
