### ISSUE TITLE
How should :bufferall handle private windows?

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#712]
I see three options:

- Treat them like any other window (current behaviour)
- Only display windows of the same kind in bufferall (private sees private, normal sees normal)
- Give them some accent so that you can tell them apart (e.g. slight purple tint)

I don't think we need to worry about not storing the commands in history, as they are only ever of the form `bufferall windowid.tabid`, and any successful command is transformed into this form before execution (so e.g. `bufferall emacs` could be turned into `bufferall 2.1`). I guess unsuccessful commands could be an issue, but that seems like an edge case.

Thoughts?

**Comment by glacambre** [comment]
I think 3) is the best option, although I'm not sure it'd actually be useful. Adding a class and a bit of CSS is not very hard.

**Comment by antonva** [comment]
I think you should be able to switch between the second and third option. While I'd be more likely to use the third option myself I can see why some people would want to keep them entirely separate.

**Comment by bovine3dom** [comment]
If people strongly feel that option 2 should be an option, then please comment here.
