### ISSUE TITLE
`viewcontainers` only works on Tridactyl's own pages

### ISSUE THREAD

**Issue by Bzly** [cmcaine/tridactyl#717]
I get the following error when I run `viewcontainers` on Windows on any page that isn't :help, :tutor etc:

`# Error: browser.contextualIdentities is undefined`

Any ideas, @antonva?

**Comment by antonva** [comment]
I can reproduce this. Give me a sec and I'll figure out what's up.

**Comment by antonva** [comment]
@Bzly I've figured it out. Pushing a PR that fixes this in the next minutes.
`viewcontainers` runs in the content script and doesn't have access to the function I was trying to call in that context.
