### ISSUE TITLE
Scrolling doesn't work everywhere

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#723]
Can't scroll on this website: http://elizagen.org/index.html

Most likely happening because the document doesn't have a body but [we need one to compute the height of a line](https://github.com/cmcaine/tridactyl/blob/8c49d26340cdc0db3c5a8011958339ac49051d03/src/excmds.ts#L736).
I thought I already fixed this by using document.documentElement instead of document.body.

**Comment by bovine3dom** [comment]
There's something very strange about that page - the mode indicator doesn't show up, and if you give the page focus, you can't send any commands to Tridactyl (e.g. `b`).

**Comment by glacambre** [comment]
That's because the body of the page isn't actually a body, it's an iframe. We should probably inject the mode indicator in the documentElement rather than the body and Tridactyl not receiving keystrokes will be fixed once https://github.com/cmcaine/tridactyl/issues/412#issuecomment-397516991 is implemented I believe.

**Comment by glacambre** [comment]
Closing this as it's entirely caused by Tridactyl not being able to handle frames.

**Comment by bovine3dom** [comment]
http://www.warringtoncyclecampaign.co.uk/facility-of-the-month/ potentially the same issue? No input to Tridactyl at all once focus is given to the page.
