### ISSUE TITLE
Installing native messenger misbehaves - Non-ASCII Windows User Path

### ISSUE THREAD

**Issue by vlamacko** [cmcaine/tridactyl#731]
Regarding [win_install.ps1](https://github.com/cmcaine/tridactyl/blob/master/native/win_install.ps1).

Installation of the native messenger unsuccessful on Windows probably due to  non-ASCII character in the user folder path. So far I have noticed that the batch file is wrong, i.e. `C:\Users\Vladimír\.tridactyl\native_main.bat`:
```@echo off
call py -3 -u C:\Users\Vladim?r\.tridactyl\native_main.py
```
Manually correcting the path and then testing using `:native` does not remedy the problem. 

I am considering two ways to fix this: 

1. Make sure every bit of code is able to handle non-ASCII paths.
2. Detect non-ASCII user path and prompt the user to choose different install directory.

**Comment by vlamacko** [comment]
It seems to be a problem purely with batch files. If I copy paste the fixed command (`py -3 -u C:\Users\Vladimír\.tridactyl\native_main.py`) to cmd it works. Running the batch file breaks the encoding. Easiest fix would be to use relative path `.\native_main.py`. Any issues with that?

**Comment by bovine3dom** [comment]
Relative looks fine to me, but @gsbabil will know more as he wrote most of this code :)

**Comment by gsbabil** [comment]
Hi @vlamacko, @bovine3dom,

Thanks for reporting. I just submitted #733 which should fix this problem.

Thanks a lot.

**Comment by bovine3dom** [comment]
Please let me know if the issue persists.

Thanks gsbabil.

**Comment by vlamacko** [comment]
Hi @gsbabil. This fixes the issue but introduces a new bug, see #734 . 

Thank you.
