### ISSUE TITLE
Beta updates hang on FF 61

### ISSUE THREAD

**Issue by wavexx** [cmcaine/tridactyl#735]
I'm following the beta branch and update quite regularly. I'm also using FF 61.0b8 on debian.
Whenever an update is installed, the update process hangs after the download (with the download progress being stuck at 100%, which is weird).

If I restart FF, or simply disable/enable the extension, the extension shows up as updated.

**Comment by wavexx** [comment]
Now that you mention, on the main release I did get the "restart required", but I was probably on FF 60.

**Comment by bovine3dom** [comment]
Closing as I believe this to be a Firefox bug.

**Comment by wavexx** [comment]
On Tue, Jul 03 2018, Oliver Blanthorn wrote:
> Closing as I believe this to be a Firefox bug.

Do you have an upstream bug that I can monitor?

I didn't find anything analogous in any other extension.

**Comment by bovine3dom** [comment]
No, I don't. We've been quite lazy with reporting things on the BMO recently.

**Comment by glacambre** [comment]
Possibly related: I found this message, repeated multiple times in my background console.
```
1531887987543 addons.update-checker WARN onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property." nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120" data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120 parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130 onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309 UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
```

There also was a second message:
```
1531887990148 addons.xpi WARN Please specify whether you want browser_style or not in your options_ui options.
```

We might not be responsible for these since it seems that every other addon also triggers this message.

**Comment by wavexx** [comment]
I'm on FF70, and a restart is still required to actually update tridacyl.

However, there's no feedback about it: as reported originally, the update simply gets stuck after download.

I couldn't find anything relevant in the list of upstream FF bugs.

**Comment by bovine3dom** [comment]
We probably need (someone) to file one :)

**Comment by wavexx** [comment]
I have no idea what's causing this. I assumed (from earlier discussions) that it was done intentionally? I could be wrong.

**Comment by bovine3dom** [comment]
Refusing to update until a restart is on purpose. We just listen to this event https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onUpdateAvailable which stops updates (which is desired). The bad FF UX is a Firefox bug, IMO.

**Comment by wavexx** [comment]
Ok thanks for clarifying.

Well, the UI of the "addon pane" got significantly worse in the new FF releases.

If you update manually, like I do, the ability to update a single extension is now buried inside a submenu (however, the width of the panel is unchanged, so 50%+ of the page is blank where we used to have the update button).

After checking for updates you need to switch over to a different pane and come back to actually see which updates are available (clicking "view available updates" is now broken).

Sooo many UI regressions... :(
