### ISSUE TITLE
:tabopen should open no container instead of current container (so it's consistent with Firefox's default ctrl+T)

### ISSUE THREAD

**Issue by WorldCodeCentral** [cmcaine/tridactyl#738]
Since I was asked to report this here:
So I've now tested after disabling the facebook container extension, `t enter` still opened in the current container. Restarted Firefox, same thing. Disabled the container extension as well, same behavior. Restartet Firefox, same behavior. Can someone else reproduce that ctrl+T opens in no container even when you're currently on a tab in a container but :tabopen enter doesn't?

**Comment by antonva** [comment]
Hi,

I cannot reproduce this on  `1.13.1-22-gc704c51`, nor could I reproduce it the first time you asked.
Could you please provide your tridactyl version number?


PS: What is the output of  `get tabopencontaineraware` ?

**Comment by glacambre** [comment]
Can't reproduce this issue either with Tridactyl `1.13.1-23-gad148d1` (this is a Tridactyl from the future), firefox 62.0a1 and `tabopencontaineraware` set to `false`.

Can you reproduce this issue when using a clean firefox profile?

**Comment by WorldCodeCentral** [comment]
Hello! :version 1.13.1-22-gc704c51
# tabopencontaineraware = false
Firefox Beta 62.0b3 (64-bit) (the problem existed on beta 61 too though)
Can't reproduce for a different profile on :version 1.13.1-1.13.1
Seems like the problem is tied to my profile. Any idea what to do? If this issue is to rare for you to care I understand though.

**Comment by glacambre** [comment]
>Or maybe it's because I'm using a container that's not been created by tridactyl?

Probably not, I've never used a container that was created by Tridactyl. There's probably a setting somewhere in about:config that you need to reset to its default value. I'd recommend just using a new profile and importing your old data by following this tutorial: https://support.mozilla.org/en-US/kb/recovering-important-data-from-an-old-profile .

**Comment by WorldCodeCentral** [comment]
Yeah I should probably do that, I have at least one other bug that happens only with this profile (Tridactyl unrelated though). Thanks, I suppose this can be closed then.
