### ISSUE TITLE
add default to commandline

### ISSUE THREAD

**Issue by lericah** [cmcaine/tridactyl#74]
in Vimperator I either started in command mode or I had to hit esc to go to command mode. In Tridactyl you have to tab twice

**Comment by cmcaine** [comment]
I don't understand what you mean by that.

**Comment by lericah** [comment]
In Vimperator it was often the case that the focus of input would not be on anything(ie. vim command mode) so if you typed "t g foo" it would search "foo" on google without any extra keystrokes, occasionally something might have focus and you would need to hit escape to switch back to command mode.

In Tridactyl  most of the time the URL bar will have focus and the only way to fix this is to hit tab until nothing that accepts text is selected. At this point you can then type a command like "tabopen foo"

**Comment by cmcaine** [comment]
There is currently no way for us to unfocus the location bar. We've asked for an API to do so.

`t g foo` would require an enter on vimperator, right? The same keys will work with the same effect in tridactyl, AFAIK.

In pages, you should be able to press escape to unfocus an input, but it's not perfect yet. I'm also thinking of adding a config option to prevent page JS from focusing an input on page load, but, low priority.

PRs and further comments welcome.

**Comment by cmcaine** [comment]
Did my previous comment answer your question?

I'm still not sure what you're asking for.

**Comment by lericah** [comment]
Yes that answers it,  thank you
