### ISSUE TITLE
:hint -w probably should open a private window when called in a private one

### ISSUE THREAD

**Issue by rouanth** [cmcaine/tridactyl#740]
Or maybe it makes sense to add a separate option for "hint" with the semantics "open a new window with the same level of privacy".

I'm trying to get rid of tabs altogether and instead use native tabbing of my window manager. With the `:guiset gui none`, I'm able to avoid seeing them. Unchecking `Open links in tabs instead of new windows` in preferences allows me to avoid creating new tabs by clicking on links. The final step would be `:bind F hint -w`, but this way, the configuration has a glaring flaw: if I'm on a private window and open a link in a new window, the window isn't a private one.

P.S. Great work with tridactyl! I was severely saddened when `vimperator` stopped working, but `tridactyl` is already a sufficient replacement for it in all of my use cases, and in some ways it even surpasses `vimperator`. Just so you know that your work is much appreciated.

**Comment by bovine3dom** [comment]
I'm not sure I agree with this. Ctrl N always opens a non-private window, right? I think the context sensitivity would be confusing.

You can make this yourself with `jsb browser.extension.inIncognitoContext ? tri.excmds.hint("-w") : tri.excmds.hint("-wp")` probably. Untested.

**Comment by rouanth** [comment]
Ctrl+N does open a non-private window, however, in my opinion, when we're hinting a link, it's more akin to right-clicking it and selecting some action than it is to opening a new window (which more directly corresponds to the `:w` command). And if you right-click a link in private mode, there is no option to open the link in a new non-private window.

**Comment by glacambre** [comment]
inIncognitoContext can only be true in content scripts (so when using `js` instead of `jsb`). So `js browser.extension.inIncognitoContext ? tri.excmds.js("alert(1)") : tri.excmds.js("alert(0)")` should work :)

**Comment by rouanth** [comment]
@glacambre it does, but `tri.excmds.hint` can't be run from the content scripts.

Anyway, I managed to make it work with the following command:
`composite js browser.extension.inIncognitoContext | jsb -p JS_ARG ? hint("-wp") : hint("-w")`

Thank you all for your advice! The issue is solved.
