### ISSUE TITLE
#736/#728 broke shydactyl

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#748]
Other themes are fine.

**Comment by bovine3dom** [comment]
Heh, I mostly forgot about Shydactyl. Presumably #742 would be really obnoxious with it...

Perhaps we can give the commandline a tag when it's being used to display a temporary message.

**Comment by bovine3dom** [comment]
What does "broke" mean?

For me, it seems to work on the whole. There is a slight snag in that the containers are only displayed on B and not b, and the private indicators are not shown on B.

**Comment by glacambre** [comment]
>Perhaps we can give the commandline a tag when it's being used to display a temporary message.

I think we should stop adding hacks on top of hacks. I already went too far with the `fillcmdline_tmp` stuff, we should work on having a real statusline instead.

>What does "broke" mean?

I don't see buffer titles anymore when using `:bufferall`. Doesn't it happen for you?

**Comment by bovine3dom** [comment]
> I don't see buffer titles anymore when using :bufferall. Doesn't it happen for you?

Yes, and I thought I had mentioned it but apparently I forgot.

I do agree in general with hacks on top of hacks being not fantastic, but I think giving messages their own class that they can be styled by is something that would be retained by a non-hacky solution.

**Comment by glacambre** [comment]
Fixed by #756.
