### ISSUE TITLE
new tab page headline Tridactyl REPLACE_ME_WITH_THE_VERSION_USING_SED

### ISSUE THREAD

**Issue by holtzermann17** [cmcaine/tridactyl#751]
It looks like someone forgot to update the version number using `sed`.

Consulting the changelog, this is in the following version:

Tridactyl changelog
Release 1.13.1 / 2018-06-20

**Comment by bovine3dom** [comment]
Could you update Tridactyl and restart? It's probably a symptom of #747 which is fixed.

**Comment by holtzermann17** [comment]
Yes, it works now.
