### ISSUE TITLE
Breaks graphiql

### ISSUE THREAD

**Issue by robertgzr** [cmcaine/tridactyl#757]
Sites like https://graphql.github.io/swapi-graphql that are often deployed along graphql APIs become basically unusable. It seems to not switch into `insert` mode when selecting the text area on the left. Sometimes it works and then everything works as expected but I can't seem to force tridactyl into insert mode using `:mode insert`

Using `ignore` mode doesn't help - as I can't interact with the text fields at all when it is turned on.

**Comment by glacambre** [comment]
You probably have `allowautofocus` set to false and you need to set it to true to use fancy JS editors.
I'd recommend using an autocmd to set `allowautofocus` to true when switching to a tab that has this site and another to set it to false when leaving :)

**Comment by bovine3dom** [comment]
Closing in favour of #550.
