### ISSUE TITLE
support * clipboard as well

### ISSUE THREAD

**Issue by orangenschalen** [cmcaine/tridactyl#76]
Right now tridactyl's 'yy' and clipboard commands work with the C-c clipboard (the + register in vim-speak). If tridactyl would yank and paste as well to and from the X-Window, "middle-mouse-button" clipboard (the * register in vim-speak) as vimperator and pentadactyl did, that would be great.

**Comment by cmcaine** [comment]
From `:help clipboard`

> Unfortunately, javascript can only give us the clipboard clipboard, not e.g. the X selection clipboard.

It is annoying. If we write a nativeMessenger, then people who install that will be able to get selection copy and paste.

**Comment by bovine3dom** [comment]
This is probably pretty trivial to implement if anyone's interested.

1. Look at the code for how we choose an editorcmd in src/native_background.ts and replicate that for `xsel` or `xclip` (and others if they exist).

2. Add that to a clipboard function which lets you get/set the various selections

3. Make the `clipboard` excmd accept a flag (look at how `winopen` handles `-private`) specifying a selection.

4. Spend the most time trying to work out what to bind the new commands to. Maybe `g{p,P,yy}`?

**Comment by caputchinefrobles** [comment]
Should this be closed by now? I've tried yy, ;p, p and P and the clipboard integration is working with nativemessenger installed.

**Comment by bovine3dom** [comment]
No, this is for the other X selections, like "middle click" paste.
