### ISSUE TITLE
bandcamp.com doesn't work as expected

### ISSUE THREAD

**Issue by doncatnip** [cmcaine/tridactyl#768]
The dropdown for selecting the audio format for downloads doesn't open on click.

**Comment by glacambre** [comment]
Can reproduce. This is caused by the event listener hijacking code.
I'm getting tired of all the bug I've introduced.

**Comment by bovine3dom** [comment]
How prevalent is this bug? Do we need to do a proper release?

**Comment by glacambre** [comment]
This bug has been introduced 4 months ago and nobody complained until now. In my opinion there's no reason for it to impact the release schedule.
