### ISSUE TITLE
Scrolling pages with "Space" hotkey does not work

### ISSUE THREAD

**Issue by Taomach** [cmcaine/tridactyl#77]
In vanilla firefox, as well as vimperator, Space and Shift+Space scroll the page one screen forward and backward respectively. In tridactyl, however, those hotkeys don't work, and I can't find the ones that do.

**Comment by Bzly** [comment]
`J` and `K` (capital) are probably what you're after.

**Comment by Bzly** [comment]
Oops, I may have spoken too soon - for me at least, those don't appear to be implemented yet. However, also for me, Space and Shift+Space do work correctly (FF 57.0, Windows client).

**Comment by cmcaine** [comment]
Thanks, Taomach.

**Comment by larsks** [comment]
Thanks for the fix!
