### ISSUE TITLE
Looking for ideas for setting completions

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#774]
So I've been working on settings completions and I have something usable but I'd like to hear feedback about how it should look and what features are expected from it.

### What exists
Settings completions are triggered for `set`, `unset` and `get`.
By default, it looks like this:
![screenshot_2018-07-08-09 12 40](https://user-images.githubusercontent.com/11534587/42417752-232d919c-8292-11e8-9a33-9d1d141479e4.png)
The first column is the name of the setting, the second one its current value and the third one a short description of what the setting does. I plan on inserting another column between the first and second one that would display the allowed values (e.g. `next|related|last` for `tabopenpos`).

Once the name of a setting has been completely typed, its possible values are shown with a description of what the value does, or, if there's no description of what the value does, the more general description of what the setting does:
![screenshot_2018-07-08-09 15 25](https://user-images.githubusercontent.com/11534587/42417789-12f32ab6-8293-11e8-9b69-5e6c595937f3.png)

For "complex", nested settings, the full stringified object is shown like this:
![screenshot_2018-07-08-09 18 28](https://user-images.githubusercontent.com/11534587/42417807-79382330-8293-11e8-8da3-678428f162d2.png)

Once the name of the parent object has been completely typed, the name of the child settings are displayed with their current values:
![screenshot_2018-07-08-09 18 56](https://user-images.githubusercontent.com/11534587/42417834-a1b650c0-8293-11e8-8870-4628916f611a.png)
Note that when commands expect you to type a specific string rather than the actual value, the setting will be shown with the specific string (e.g. in the config, `logging.messaging = WARNING` is stored as `logging = { messaging : 2 }` but the only thing you're shown and are expected to type is `WARNING`).

#### User-facing questions
I'm very dissatisfied with how it looks but I have no idea how to improve it. Should columns have a different width? Should different columns have different colors? Should some columns be hidden on small screens and shown on large screens? Is information missing? Any help is welcome.

#### Implementation details
The config has been turned into a class and the metadata is added using the following decorators:
```ts
class Config {
    @hidden // Hides the setting in the `set` and `unset` completions but not in `get`
    configversion = "0.1"


    @shortDescription("Your default search engine.") // Description string of the completion
    @settingOptions(() => Object.keys(get("searchurls"))) // Possible completion values that can't be determined at compile time
    searchengine = "google"


    @shortDescription({ // When you want to specify a description for each possible setting
        global: "How hints are selected.",
        options: {
            simple: "Type the characters of the hint",
            vimperator:
                "Type the characters of the element being hinted, hints do not disappear.",
            "vimperator-reflow":
                "Type the characters of the element being hinted, hints disappear.",
        },
    })
    hintfiltermode: "simple" | "vimperator" | "vimperator-reflow" = "simple"


    @displayFilter(v => ["NEVER", "ERROR", "WARNING", "INFO", "DEBUG"][v]) // This is used to turn the actual values stored in the configuration into something readable
    logging = o({
        messaging: 2,
        excmd: 1,
        ...
    })
}
```
Do these decorators seem reasonable? Are some missing? Should the names be changed?
I haven't implemented this yet but I planned on using a custom compiler pass in order to generate actual possible values by using types. So for example, you could remove the "options" object from `hintfiltermode`'s shortDescription and still know that its three possible values are `simple`, `vimperator` and `vimperator-reflow` because the compiler will have generated that info in a specific file.
The more I think about it, the more I'm starting to think that this might be overkill for just completions, but perhaps it could be useful for other things, e.g. runtime type-checking of config/excmds?

### Slightly unrelated thought
Having nested objects in the config is a pain in the ass. What would be the disadvantages of replacing everything with settings with a dot in their names (e.g. `nmaps = {a: "bmark"}` would become `"nmaps.a" = "bmark"`)? I can only think of advantages: this would simplify a great deal my completion source, provide a closer mapping between excmds and the config and even make setting/unsetting config values that contain dots easier (https://github.com/cmcaine/tridactyl/issues/303).

**Comment by bovine3dom** [comment]
I'll come back to this with more detailed comments later, but for now:

- Description column should be a lighter colour (Pentadactyl did it reasonably well)
- Consider experimenting with multi-line completions (indentation can make it clear that a completion is continuing rather than a new one)
- Is there any way to use docstrings instead of decorators so that #524 would still work?

Thanks for doing this : )

**Comment by glacambre** [comment]
>Consider experimenting with multi-line completion

I tried to hack something using CSS but I couldn't get it to work. This would probably require a rewrite of the command line.

>Is there any way to use docstrings instead of decorators so that #524 would still work?

As far as I know, TypeScript doesn't support docstrings. I'm fairly certain we could emulate them using regular comments and a custom compiler pass though. But in my opinion, decorators and docstrings aren't incompatible. What I thought was that the decorators would be used to provide short descriptions for completions while actual comments would be used in the documentation, where we would be free to write as much as we want.

>Using the VIM folds concept for multiline would be interesting, not sure how useful, but people should be comfortable with expanding/closing folds with zo and zc

This is a pretty good idea, I didn't really like the idea of multiline completion options but if we can toggle that using keyboard shortcuts it'd probably be pretty cool.

**Comment by kimat** [comment]
Have a look at qutebrowser if u want some inspiration: they for instance highlight what is currently typed in the in the filtered results

**Comment by glacambre** [comment]
Setting completions have landed, thanks @bovine3dom !

We'll still need to add documentation and possibly value completion, which shouldn't be hard to do using the TS compiler API. I'll do that once https://github.com/cmcaine/tridactyl/pull/524 is merged.

**Comment by bovine3dom** [comment]
Oh, woops, I totally forgot about this issue... The time from me thinking it was a good idea to merging it was about 10 minutes.

Sorry, glacambre!

**Comment by glacambre** [comment]
No problem, my code was slightly more complicated than yours because I tried to handle nested settings and I would have had to rewrite much of it to use the typescript API instead of decorators so all in all, nothing of value was lost :)
