### ISSUE TITLE
Editor keybind not documented

### ISSUE THREAD

**Issue by rootkit-ty** [cmcaine/tridactyl#782]
Just noticed that the editor keybind isn't well documented. I found it out by digging through the comments in the source code, but there's no mention in the `:help` or `:get nmap` or any other list of keybinds.

**Comment by bovine3dom** [comment]
This is mostly an artefact of #304.

It is listed in `tutor` which is where we communicate our binds that live outside of normal mode, and on the new tab page.

Happy to add it to the top of the help page.
