### ISSUE TITLE
Pressing Shift+d sometimes closes the tab left to the current one

### ISSUE THREAD

**Issue by mist** [cmcaine/tridactyl#783]
I use Shift+d a lot to close the current tab and go to the left of the current one. Sadly it happens quiet often that instead of the current tab the destination tab is closed.

I have no way to cleanly reproduce this behaviour.

**Comment by bovine3dom** [comment]
Could you try increasing the sleep time?

`:bind D`, copy and paste the current bind into `:bind D ... sleep [bigger number] ...`.

**Comment by mist** [comment]
I increased it to 200 and now I can reproduce the faulty behaviour almost constantly.
Currentyl it is set to `# D = composite tabprev; sleep 100; tabclose`. Shouldn't `tabprev` and `tabclose` be the other way around?
Hmm, tried it, didn't work...
I tried it without `sleep` and now it seems to work.

Also I couldn't find the keybinding in the FAQ/manual and am no wondering how I got it.

**Comment by bovine3dom** [comment]
It should be bound to `composite tabprev; sleep 100; tabclose #` by default. The # is important, but I can see how it looked like it might have been part of the "comment" decoration. # is magic and means "the previous tab".

I cannot reproduce your issue. It works fine for me. `composite tabprev; tabclose` does work but probably relies on a race condition and I would not recommend it.

**Comment by bovine3dom** [comment]
> Also I couldn't find the keybinding in the FAQ/manual and am no wondering how I got it.

I believe the command existed in Vimperator, so you probably just remembered it from there :)

**Comment by mist** [comment]
Ahh, yes, with the magic `#` it is working again... It was also there before me messing with it today just thought it was a comment (especially because after entering `:bind D` there was a `#` visible directly after the `:`.
Trying it with `sleep 200` now and will see if it happens again. I'll tell you later if it is still happening.

Yepp, I knew it from Vimperator and later Pentadactyl.

**Comment by mist** [comment]
`sleep 200` still doesn't reliably work. `sleep 400` now...

**Comment by mist** [comment]
<3

**Comment by mist** [comment]
If tabprev is now synchronous couldn't the `sleep` be removed from the default config?
I understand it that `tabprev` now doesn't return until the previous tab is really selected, so as soon as `tabprev` returns `tabclose #` will close the right tab. Correct me if I'm wrong.

**Comment by bovine3dom** [comment]
Yes, probably.

I'd like to see confirmation from someone that it does indeed work without `sleep` on a slow PC. It works fine on my reasonably quick one.
