### ISSUE TITLE
<C-i> binding opens a different editor to the one I want

### ISSUE THREAD

**Issue by NikosEfthias** [cmcaine/tridactyl#795]
when i use <C-i> i want it to open vimr but instead i get textmate and even in that case i cannot get the etxt contents back to input when i save and close text mate
Is tehere any way around setting editor to vimr and auto paste on close?

**Comment by antonva** [comment]
You could try the solution found in #684

**Comment by bovine3dom** [comment]
Closing as a likely duplicate of #684.

You probably just need to do `set editorcmd /usr/local/bin/vimr --wait`.
