### ISSUE TITLE
search doesnt work properly

### ISSUE THREAD

**Issue by NikosEfthias** [cmcaine/tridactyl#801]
when i hit `/` it starts the search as usual but then it gets stuck there `n` or `N` doesnt work and also i cannot go back to normal mode or ex mode or anything literally tridactyl stops working

**Comment by bovine3dom** [comment]
You're using Firefox's own quick find mode. Our find mode is a work in progress #623.

Escape or just waiting will close the bar, and Ctrl-G / Ctrl-Shift-G or F3/shift F3 will cycle results.
