### ISSUE TITLE
`tabopen -c` ignore first parameter for search

### ISSUE THREAD

**Issue by sjug** [cmcaine/tridactyl#805]
Despite having the additional flag `-c` the next word is still treated as a query in the history. Would it be possible to ignore that first parameter and not filter the history against the container tab name?

**Comment by bovine3dom** [comment]
This should have been fixed in #758. Use a beta build (instructions on our GitHub readme.md), or wait for us to get around to putting a proper release out : )

**Comment by sjug** [comment]
@bovine3dom sorry for the spam, I thought I was using a beta build.

**Comment by bovine3dom** [comment]
It's not spam. Thanks for reporting it!

What's the output of `version`? Beta builds usually end in g[commit hash].

If you are on a beta build you can update by opening about:addons and clicking the cog in the top right, then clicking check for updates.
