### ISSUE TITLE
Shortcut for pinning and muting tabs

### ISSUE THREAD

**Issue by Susexe** [cmcaine/tridactyl#812]
I miss these two shortcuts from Vimium-FF, especially the first one. Key combos are right on; it would probably be the best not to change them in case you implement this.

> **<a–p>** Pin or unpin current tab (_togglePinTab_)
> **<a–m>** Mute or unmute current tab (_toggleMuteTab_)

**Comment by kimat** [comment]
`:pin` already toggles pin state of current tab https://github.com/cmcaine/tridactyl/blob/master/src/excmds.ts#L1797

**Comment by bovine3dom** [comment]
@Susexe just add `"<a-p>": "pin",` to src/config.ts in the place with all the other binds. Nice easy first PR :)

**Comment by bovine3dom** [comment]
Adding it to our config.ts would make it be the default for everyone like you asked.

**Comment by Susexe** [comment]
Oh, PR is a pull request, LOL. I'll try it out tonight.

**Comment by kimat** [comment]
#818
