### ISSUE TITLE
Ignore-mode breaks ReasonML's ‘try‘ page

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cmcaine/tridactyl#815]
### Visit: https://reasonml.github.io/en/try

When in `normal`, I can type into the text-fields, to some extent, but things break in obvious ways due to Tridactyl. This I expected.

However, when I `:mode ignore`, very *unexpectedly* I am no longer able to type into any of the text-boxes on the page — at all!

Odd bug. I've resorted to disabling Tridactyl in the Addons interface, temporarily, to use that tool.

**Comment by antonva** [comment]
I cannot reproduce this on the link provided with either `Shift-Instert` toggling into ignore mode from insert mode or normal mode nor from entering ignore mode via `:mode ignore`.

tridactyl version `1.13.1-91-g4beccba`

**Comment by ELLIOTTCABLE** [comment]
Wow. Yeah, I just tried this on my partner's machine, on her FireFox. Works fine.

I have no idea what could be causing this. Gonna close then, unless someone else can ever reproduce it …

**Comment by bovine3dom** [comment]
@ELLIOTTCABLE almost certainly due to `set allowautofocus false`. #550.

**Comment by ELLIOTTCABLE** [comment]
@bovine3dom that's it exactly! `<3`
