### ISSUE TITLE
Count arguments not functioning?

### ISSUE THREAD

**Issue by wmorrell** [cmcaine/tridactyl#820]
I'm running:
Firefox Quantum 61.0.1
MacOS 10.12.6
Tridactyl 1.13.1pre1546

It looks like count arguments are not working. I have tried:

- `4j`: scroll down behaves the same as `j`, instead of scrolling 4x as far
- `2gt`: skips to next tab/buffer as with `gt`, instead of moving two tabs/buffers
- `2<c-o>`: goes back once in history, instead of twice
- `3gu`: goes up one directory path in URL, instead of three

**Comment by glacambre** [comment]
Hi, thank you for opening this issue! :)
I believe we already have one for this problem: https://github.com/cmcaine/tridactyl/issues/466.

**Comment by wmorrell** [comment]
Ah, yes that looks to be the same, I didn’t search back far enough!

I was getting worried about ESR moving to quantum eventually, glad to see this project is getting there with XUL going away. I am going to give it a few more days to get used to changes from Vimperator. This is a minor bump in a great transition experience so far, so thanks to all the contributors!
