### ISSUE TITLE
Regression: clipboard open/tabopen fail

### ISSUE THREAD

**Issue by bodograumann** [cmcaine/tridactyl#827]
After my latest update from 1.13.1pre1500 to 1.13.1pre1546 the shortcuts `p` and `P` which call `clipboard open` and `clipboard tabopen` respectively fail with:

> \# Error: Couldn't find an external clipboard executable 

I do indeed have neither `xclip` nor `xsel` installed, but that was no problem until now.
Curiously yanking (with `yy`) works still perfectly.

https://github.com/cmcaine/tridactyl/commit/2eea72e4297e8b72fc975dec5d418e23558e9a8a might be relevant.

Config:
```
# putfrom = clipboard
# yankto = clipboard
```

**Comment by bovine3dom** [comment]
I think this was just a typo. Please check in version `...-g9199938` which should appear soon.

**Comment by bodograumann** [comment]
Yes, it works again :-)
