### ISSUE TITLE
Scrolling through completion options with bindings other than TAB and S-TAB

### ISSUE THREAD

**Issue by Wagk** [cmcaine/tridactyl#837]
Currently when I'm in the completion menu I can only scroll through the candidates using TAB and S-TAB.

I'm wondering if there is a way to rebind it to <C-j> and <C-k>? Something similar to what Vimium currently does.

Cheers

**Comment by glacambre** [comment]
Unfortunately this isn't possible yet. We have an issue open for this though (https://github.com/cmcaine/tridactyl/issues/304) so it's definitively planned :)

**Comment by bovine3dom** [comment]
Closing as covered by #304 as mentioned. Thanks for the feedback :)
