### ISSUE TITLE
Pressing "space" to insert a completion also inserts a space

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#838]
```
tabopen <tab><space>
tabopen  https://www.google.com/search?q=how%20to%20tell%20my%20friends%20I%20sometimes%20use%20emacs 
```

I.e, there are two spaces before the URL, in addition to one after it.

**Comment by glacambre** [comment]
Caused by this line: https://github.com/cmcaine/tridactyl/blob/6ed83eacdbdd452f930e971993c7a7bbaccdfed2/src/completions/History.ts#L83
A pretty easy fix is to replace it with `(options ? options + " " : "") + page.url`
