### ISSUE TITLE
`guiset` fails

### ISSUE THREAD

**Issue by pengowen123** [cmcaine/tridactyl#844]
*   Brief description of the problem:

Running `guiset` gives me this error (which appears about 1 second after running the command):

>\# TypeError: potentialRules[rulename] is undefined 

*   Steps to reproduce:

    1. Launch Firefox
    2. Run `:guiset`

*   Tridactyl version (`:version`): 1.13.1-138-gdef998a

*   Firefox version (Top right menu > Help > About Firefox): Firefox Nightly 63.0a1

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/pengowen123/62bfe161048ade686944ab6804ff7890

*   Contents of tridactylrc

```
fixamo_quiet

" Settings
set theme dark
set searchengine duckduckgo
set hintchars 4327895610
set hintfiltermode vimperator-reflow
set allowautofocus false

" Binds
bind K tabnext
bind J tabprev
```

*   Operating system: Windows 10
*   Result of running `:! echo $PATH` in tridactyl:
```
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
```

After enabling logging for `styling` and `messaging`, here is a log after running `guiset`:
>TypeError: "potentialRules[rulename] is undefined"  
changeSingleCssmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:11422:11changeCssmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:11447:17guiset_quietmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:3886:73guisetmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:3928:11acceptExCmdmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:2764:31recvExStrmoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:6230:9handlermoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:672:49onMessagemoz-extension://af065d0f-d401-4e72-879a-f045907f3e90  /background.js:737:13 logging.ts:44:38

**Comment by glacambre** [comment]
Hi, thank you for opening this issue!

`guiset` requires two arguments: a "component" and the state it should have. For example, `guiset gui none` in order to hide all gui elements. You can know all of guiset's elements by running `:help guiset`.

We should probably display better error messages when guiset's arguments are missing.

**Comment by pengowen123** [comment]
@glacambre In that case I'll just close this issue. Do you think a tracking issue for better error messages would be useful?

**Comment by glacambre** [comment]
Thanks :). Don't bother opening a new issue, I've just opened https://github.com/cmcaine/tridactyl/issues/844 :).
