### ISSUE TITLE
Make rapid hinting less janky

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#848]
I implemented it almost by accident when I moved hinting across.

Problems:

- if there's only one link on the page, it opens it twice and exits (improved in 7c9e2b3)
- if you hold down a key to open a link loads of times, you get `# Error processing pushKey([object Object]) TypeError: modeState is undefined`
- You also sometimes get "Message manager disconnected" on the tabs that you open.

**Comment by antonva** [comment]
Wrapping the contents of `reset()` in an `if (modeState) {...}` resolves the undefined modeState issue but introduces a race condition between the hint mode and normal mode keybinds. 

Holding down `o` results in ~4-5 open tabs followed by `:open ooooooooooooooooooooooo` on the command line.

**Comment by bovine3dom** [comment]
#386 has made rapid hinting feel a bit worse, I think.

Now #855 is done, it's just the pushKey thing. If we can't figure it out soon, I'm happy to do a release.

**Comment by glacambre** [comment]
I think this can be closed.

**Comment by bovine3dom** [comment]
Holding down a key in rapid hinting with Vimperator filtering gets you stuck in hint mode without opening any hints, so I think there's still enough jank to leave this open : )

**Comment by glacambre** [comment]
>Holding down a key in rapid hinting with Vimperator filtering gets you stuck in hint mode without opening any hints

This is not a rapid-hinting problem, it's a vimperator filtering problem. Even without rapid hinting, if you're on a page that has two links named `ab` and `ac` and you press `fad`, you'll end up being stuck. The only way to get free is to press `<Esc>` or `<Backspace>` until you've removed all characters that prevent the filter from matching a link.

**Comment by bovine3dom** [comment]
I was trying it with labels that did exist (e.g. just `1`) but I'm happy to close this and blame the filtering : )

**Comment by glacambre** [comment]
Weird, keeping a number pressed to open its link repeatedly works for me (as long as there's a hint that that has this number as label). What hint-related settings are you using?
