### ISSUE TITLE
History missing on Android

### ISSUE THREAD

**Issue by robsmith11** [cmcaine/tridactyl#849]
I'm using 1.13.1 with Firefox Nightly on my Android tablet and bluetooth keyboard.  It works quite well, but there seems to be a bug with the website history.  When I press `o` to open a URL, the window where the history is usually shown is empty.  Pressing `b` to switch tabs does, however, work correctly and shows the full list of open tabs.

**Comment by bovine3dom** [comment]
Glad to hear Tridactyl works OK on Android.

History is not supported by Mozilla: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/search#Browser_compatibility

We could roll our own, but we only have about ~10 users on Android, so it won't be a priority, I'm afraid.

Feel free to find or create a relevant bug on https://bugzilla.mozilla.org/ and I'll add it to #760. I couldn't find anything with [a cursory search](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&short_desc=history%20search&resolution=---&query_format=advanced&product=Firefox%20for%20Android) so you may well need a file a new bug.

**Comment by bovine3dom** [comment]
Oh, I found the relevant bug. Closing in favour of that: https://bugzilla.mozilla.org/show_bug.cgi?id=1411651

Thanks for reporting!
