### ISSUE TITLE
Referring to the 'space' key (or other nonprintable keys) in :bind?

### ISSUE THREAD

**Issue by larsks** [cmcaine/tridactyl#85]
Tridactyl broke my brain.

I rely on using the 'space' key to scroll through pages.  After installing tridactyl, that suddenly stopped working. I figured I could just bind `space` to `scrollpage`, but I wasn't able to determine the syntax for referring to a non-printable key in the `bind` command.

What's a good way to get this working?

**Comment by Deimos** [comment]
It looks like they committed a fix for this earlier today: https://github.com/cmcaine/tridactyl/commit/d45d906865ecec903b0d72e8024592160984e669

**Comment by cmcaine** [comment]
Yep, sorry for missing it originally.

**Comment by larsks** [comment]
If anyone finds themselves here in the future, see also #77.
