### ISSUE TITLE
[Windows] :installnative wrong download link

### ISSUE THREAD

**Issue by walderich** [cmcaine/tridactyl#856]
When using ":installnative" on Windows I get the following code in the command line:

`Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))`

When pasting this to powershell I get a 404 error "File not found". Looking over the git repository, it seems that the file name changed from "win_install.ps1" to just "install.ps1". When removing the "win_" prefix manually, the download is successful.

*   Tridactyl version (`:version`): 1.13.1-1.13.1
*   Firefox version (Top right menu > Help > About Firefox): 61.0.1 (64-Bit)

**Comment by bovine3dom** [comment]
I'll rename the file after lunch. Thanks for reporting!

**Comment by bovine3dom** [comment]
Fixed in 47f9039.
