### ISSUE TITLE
some twit bound Ctrl-F to scroll down and now GitHub is even more annoying

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#859]
Related: #374, #623.

I'm grumpy enough with this now that I think we should just offer a `fixgithub` command, like `fixamo`.

I see three possible approaches:

- Listen for a keydown event being added (perhaps by rewriting addEventListener) and remove it it with https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener
- Rewrite preventDefault to a no-op https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault
- Actually make a find mode

Edit: https://superuser.com/questions/168087/how-to-forbid-keyboard-shortcut-stealing-by-websites-in-firefox#answer-670040 potentially useful

**Comment by glacambre** [comment]
>Listen for a keydown event being added (perhaps by rewriting addEventListener)

Most of the code is already there if we want to go down this route. I think it could be an interesting feature to have regardless of whether the actual find mode is implemented or not.

>Rewrite preventDefault to a no-op

This wouldn't prevent Github from detecting `/` has been pressed and to open its search prompt, which would still be annoying in my opinion.

**Comment by cmcaine** [comment]
`stopImmediatePropagation` should stop github seeing the event, iirc.

Which I now see Olie is using in the commit.

**Comment by filterfish** [comment]
@glacambre thank you very much for doing this. I was actually thinking that the only solution was to go on a killing rampage but now I don't have to ;)

**Comment by glacambre** [comment]
@filterfish I think @bovine3dom is the one who fixed it :)

**Comment by filterfish** [comment]
@glacambre Good point! I wonder if the notification system works with edits?

**Comment by bovine3dom** [comment]
I read everything anyway so 🤷‍♂️ 

You're welcome : )
