### ISSUE TITLE
Keep "standard" shortcuts working as well

### ISSUE THREAD

**Issue by sillyfrog** [cmcaine/tridactyl#86]
I have found that the standard shortcuts no longer work for me when tridactyl is installed. For example `Command-F` is the same as pressing just `F`, it would be great if the `Command` shortcuts still did what they used to do. (As you probably guessed, I'm on a Mac).

The ones *I* would like (others may also want something else) to have work (so far at least) are:

- F, stock find
- L, select the address bar

Many do still work, and some are a funky hybrid (`Command-B`, sort of does both `B` and bookmarks).

I have had a quick look at the other issues and couldn't see anyone with similar problems, so it may also be Mac specific. Or it maybe a new FF implementation limitation.

Also a big thank-you from me for this extension, it's great to have something with the new Firefox release, appreciate the effort!

**Comment by sunnypp** [comment]
`F`: As a user regarding this, this is now binded to `hint -b` which open tabs in background.  I don't know why `/` works for me as find -- this is consistent with the find function in vim too.  The "pain" is that `/` will jump and I'm not sure when I was and I need to use `<Cmd-g>` to find the next occurrence (which, most of the time the `<Cmd>` key is "escaped" from my mind when I am thinking in Vim). 

`L`: I am not sure about your use case -- if I want to open a page in this tab I'll do `o`pen, or open a new `t`ab.  If you want to edit the current url then `O` should be useful.  Also, I may do a `bind L fillcmdline open` (or `bind L current_url open`) to achieve something similar.  Some people wants the browser's UI to _disappear_ so it looks more like Vim...  Not sure if it is possible or desirable to interact with the address bar.

**Comment by sillyfrog** [comment]
Thanks for getting back to me so fast, great tips! I have been testing things further... and it looks like some pages are messing with the built in (eg: `/`, so it goes to the search on the page), I think that's why I used to like it previously. That said, it appears to work on some pages... 

As for `Command+L`, the browsers "smart bar" is very good, and I like it's auto complete when I'm messing with a URL (I used to use `gu` and `gU` a lot in vimperator). And this also appears to work on some pages...

It makes sense that some people want to hide the address bar (but I find it too useful, eg, doing `t`, and getting the Firefox suggestions is great)

Given I'm getting different behaviour on some pages vs others, I'm going to try and track down the combination that does and does not work - and I can't find a pattern looking quickly now! I think there maybe some quick with event bubbling (that may well sort itself out with later releases of Firefox).

Thanks again!

**Comment by bovine3dom** [comment]
Thanks for reporting this. None of us use Macs and so it didn't occur to us that the Meta key was important. It should be fixed in master now, and will appear on the betas on the AMO within a few minutes.

Please let us know if the issue persists (or if you come across any other macintosh specific issues).
