### ISSUE TITLE
Suggested default insert/input mode binds:

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#863]
- `<CA-backtick>`, `<CA-Esc>` for ignore mode - not shift insert coz some people use that as paste
- `<C{,S}-6>` for `buffer #`

Any others? I'm erring on the side of keeping it simple initially, although we could potentially have a helper / RC file that adds more readline / "emacs-style" binds.

**Comment by antonva** [comment]
`<C-[>` to map tp the same values as `<Esc>`
