### ISSUE TITLE
Youtube video controls aren't working with hinting

### ISSUE THREAD

**Issue by robsmith11** [cmcaine/tridactyl#87]
I can provide more info if this isn't immediately reproducible for others, but the youtube video controls aren't working with me using the tridactyl (latest release).  After typing `f`, the correct hints appear, but after typing the appropriate letter, the action isn't triggered (e.g., play/pause button).  These video controls had worked fine with vimfx hinting.

**Comment by bovine3dom** [comment]
I can't reproduce this.

Are you sure that it isn't because the hints are only single characters, in which case you need to press "Enter" to activate them? See #28.

**Comment by cmcaine** [comment]
Videos embedded in an iframe won't show the controls yet. Videos on youtube do show the controls fine for me.

**Comment by robsmith11** [comment]
@bovine3dom ah... yeah that must have been it.  I think what confused me is for some reason the hint for the "fullscreen" control disappears after hitting it once, so that no hints remain visible, but if I press enter, it then indeed goes fullscreen.

**Comment by cmcaine** [comment]
You can also press space to select the current hint.

I wrote code to show hints with always a uniform number of characters, which means you never need to press the un-obvious Enter or Space keys. Might make that the default for better discovery.
