### ISSUE TITLE
Circular tabmove broken by pinned tabs

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#877]
Steps to reproduce:

- Pin tab with A-p
- Make two new tabs
- Press `<<` repeatedly

Expected behaviour: tab moves to beginning and then to end, forever and ever

Actual behaviour: tab gets stuck at beginning next to pinned tab.

Related: #161.

**Comment by cmcaine** [comment]
Be sure to read the review comments in #161. The last ones were never incorporated into the PR but include a complete rewrite of the function by me that maybe fixed some bugs (don't remember).

Some bugs/missing features also mentioned in review.

**Comment by MoSal** [comment]
What if it's `tabmove` then `tabmove +2`, or just `tabmove 2`?

Do we want to pretend pinned tabs don't exist? Or do we want to just move to the first unpinned tab position?

**Comment by bovine3dom** [comment]
I don't use pinned tabs, but it struck me as strange that I couldn't loop tabs around if there were any pinned tabs.

So I think I'm on the side of ignoring them for relative movements. Absolute movements I am somewhat ambivalent about.
