### ISSUE TITLE
cannot search with `/` on youtube.com

### ISSUE THREAD

**Issue by wavexx** [cmcaine/tridactyl#880]
Tridactyl on FF 62.0b10 (debian unstable), trydacyl 1.13.1-210-ge958d97.

Navigate to youtube.com and try to press '/' to perform a text search into the page.
youtube is overriding '/' to focus the search field, but shouldn't be able to.
Webpages should never get binding privileges unless entering ignore mode.
Ctrl+F scrolls forward, so I cannot perform a text search except by going through the main menu.

**Comment by bovine3dom** [comment]
You can press `<F3>` to get to quick find, btw. Or maybe `<F2>`.

Websites can't override Tridactyl binds, but we do allow them to bind to keys which aren't bound.

I'll just special-case `/` on all sites, as in #374.

**Comment by bovine3dom** [comment]
Also, you can do `unbind <C-f>` if you don't use it very often.

**Comment by wavexx** [comment]
On Mon, Jul 30 2018, Oliver Blanthorn wrote:
> Websites can't override Tridactyl binds, but we do allow them to bind
> to keys which aren't bound.

Ok, but this means / "isn't" bound, it's a special case, or ...?

**Comment by bovine3dom** [comment]
Yeah, `/` is part of Firefox. `'` is too.

**Comment by wavexx** [comment]
On Mon, Jul 30 2018, Oliver Blanthorn wrote:
> Yeah, / is part of Firefox. ' is too.

Ha, I ran with vimperator-like addons for so long, I basically never
needed to know ;)

**Comment by galenhuntington** [comment]
Allow me to add `developer.android.com` to the list of sites that helps itself to `/`.  A means of overriding all of these would be helpful.

**Comment by bovine3dom** [comment]
@galenhuntington literally just need to delete this condition https://github.com/cmcaine/tridactyl/blob/d9258f7993c7894ff20b4af75277a6e93e0f74a3/src/content.ts#L204 and the one a few lines above it. I just haven't had time to do it and test it!

**Comment by bovine3dom** [comment]
Not fixed for developer.android.com in my testing - dunno why.
