### ISSUE TITLE
gg and G do not scroll

### ISSUE THREAD

**Issue by ahungry** [cmcaine/tridactyl#89]
Can this be added to emulate the pressing of HOME or END keys respectively?

**Comment by cmcaine** [comment]
They work for me.

Can you make sure you're not in ignore mode and post a URL that the problem occurs on?

**Comment by ahungry** [comment]
Thanks, I think this is a site specific issue (it was with an Atlassian Jira page) - perhaps the page itself was messing with keybinds in some way.
