### ISSUE TITLE
#890 added unnecessary element to the help page

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#899]
`:h bind_args`. It's an internal type so it shouldn't appear in the help pages.

**Comment by glacambre** [comment]
Note: this breaks displaying hints in the help page.

**Comment by glacambre** [comment]
This is weird, I don't see this on a Tridactyl built from master, I only get it when installing the betas

**Comment by bovine3dom** [comment]
Fixed in #901.
