### ISSUE TITLE
Hinting broken in FF Nightly 63.0 + Tridactyl 1.13.1-1.13.1

### ISSUE THREAD

**Issue by YggdrasiI** [cmcaine/tridactyl#905]
*   Brief description of the problem:

After pressing of 'f' the links will be numbered as expected, but keystrokes still act as normal mode. It is not possible to follow a link.
The logging information after `:logging.hinting DEBUG` doesn't show an useful hint.

*   Steps to reproduce:
Updating Nightly to 63.0 and try to use the hinting feature.

*   Tridactyl version (`:version`):
1.13.1-1.13.1 or earlier 

*   Firefox version (Top right menu > Help > About Firefox):
63.0 Nightly

*   URL of the website the bug happens on:
All

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/YggdrasiI/da55be0bdc898650deddd602aaf723fe

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
No config files created.

Are more people affected by this bug? How could I collect more debugging information?

Regards YggdrasiI

**Comment by rafpacut** [comment]
- Nightly
     63.0a1
- Tridactyl
     1.13.1-1.13.1
- :viewconfig
    https://gist.github.com/rafpacut/017d0c7d034ac365c5ce6d31c25e44a5

Exactly the same behaviour here.

**Comment by bovine3dom** [comment]
I'm hoping this bug will just go away. We should check again once 63 reaches Firefox Beta (at the start of September, I presume).

**Comment by hzzm** [comment]
This bug is already live for me on ff-stable, 61.0.2.

**Comment by davidsierradz** [comment]
I can reproduce on Firefox Developer Edition 62.0b14 (Manjaro), I am on Tridactyl 1.13.2pre1706.

**Comment by YggdrasiI** [comment]
I can confirm davidsierraz post. It works again with  63.0 + 1.13.2-1.13.2, but sometimes (no pattern spotted) not.

Thanks to the contributor, if there is anyone, who fix it.
