### ISSUE TITLE
CTRL_I does nothing

### ISSUE THREAD

**Issue by osleg** [cmcaine/tridactyl#907]
*   Brief description of the problem:
CTRL_I does nothing
*   Steps to reproduce:
1. Open input
2. Hit CTRL_I
3. Observe nothing

Expected:
Open's vim or at least throws an error

*   Tridactyl version (`:version`):
1.13.1-243-g312dfed

*   Firefox version (Top right menu > Help > About Firefox):
61.0.2
*   URL of the website the bug happens on:
https://github.com/cmcaine/tridactyl/issues/new

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/osleg/5271965bda310f789b891cc8e2d1fd0d

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
n/a

*   Operating system:
Archlinux

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
```
$ printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py
�{"cmd": "run", "content": "/home/alex/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/alex/.gem/ruby/2.3.0/bin:/home/alex/node_modules/.bin:/home/alex/.bin:/home/alex/Projects/go/bin\n", "code": 0}%       
```

**Comment by osleg** [comment]
running `:native` returns `# Native messenger is correctly installed, version 0.1.8`

**Comment by bovine3dom** [comment]
Has it ever worked for you?

Could you follow through docs/troubleshooting.md on this repo to turn logging on? Particularly native and message logs would be useful.

**Comment by osleg** [comment]
Issue found, there is a problem in my setup which prevents urxvt from loading, unrelated to tridactyl
