### ISSUE TITLE
Updating Too Fast

### ISSUE THREAD

**Issue by hppavilion1** [cmcaine/tridactyl#91]
(Note: This issue is a half-joke)
I've been trying to develop an improvement- mostly creating the settings page and wrapping up some TODOs- but this repo keeps updating while I'm doing it; git couldn't merge my first write, so I've been working on another one, but I'm already 5 commits behind (and my fork was earlier this afternoon)

**Comment by cmcaine** [comment]
We really appreciate PRs! Please feel free to fork off any commit (but "release" commits are probably best) and to submit a PR that won't automatically merge with master.

When we review your PR we'll rebase/merge and fix any merge conflicts.

**Comment by cmcaine** [comment]
You seemed to work that out on your own, but to answer your question, you should just pull down master, `git checkout -b better-config`, then work on your new branch.

Or, if you want to go off one of the release commits, find the latest with `git tag --list`, then `git checkout <tagname> && git checkout -b better-config`
