### ISSUE TITLE
Redirect loop is back

### ISSUE THREAD

**Issue by madduck** [cmcaine/tridactyl#910]
Seems like #316 is back (Tridactyl 1.13.1), at least on trademe.co.nz. As soon as I disable the extension, it loads fine.

**Comment by glacambre** [comment]
Hi, thank you for reporting this issue. This is caused by the iframe and will be fixed by https://github.com/cmcaine/tridactyl/issues/639 . In the meantime, you can use `:set noiframeon trademe.co.nz` in order to disable the command line on this website.

**Comment by madduck** [comment]
Ah, of course. I am sorry, I should have tried the settings. Anyway, confirmed.
