### ISSUE TITLE
;p pastes 'undefined' value

### ISSUE THREAD

**Issue by RNabla** [cmcaine/tridactyl#934]
*   Brief description of the problem:
Copy command (;p) returns undefined
*   Steps to reproduce:
1.open https://developer.mozilla.org/en-US/docs/Web/JavaScript
2. try to copy first paragraph using ;p
3. paste it somewhere it says ;undefined;
*   Tridactyl version (`:version`):
1.13.2-1.13.2
*   Firefox version (Top right menu > Help > About Firefox):
61.0.2 (64 bity)
*   URL of the website the bug happens on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript
*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/RNabla/b1fcf5cc7d69f7a3755ba8d4a1efe3e1

**Comment by bovine3dom** [comment]
Cannot reproduce on `1.13.2-49-gd5d3f11`... but I can on `1.13.2`. I guess we fixed it by accident?

I'll release 1.13.3 soon.

Thanks for reporting.

**Comment by RNabla** [comment]
My friend also confirmed this issue with his version of tridactyl. Also I could reproduce it on two independant devices: home PC and corporate laptop. I'll wait for 1.13.3 and tell if the problem remains.

**Comment by bovine3dom** [comment]
1.13.3 is out. You can ask Firefox to update sooner by going to `about:addons`, clicking the cog in the top right, clicking `Check for Updates` and then restarting the browser once Tridactyl's bar is full.

**Comment by RNabla** [comment]
Thanks. It resolved issue.

**Comment by bovine3dom** [comment]
I think @glacambre is probably the person who fixed it. Thanks again for reporting it!
