### ISSUE TITLE
How to bind "go" and "gn" to "e" and "E"

### ISSUE THREAD

**Issue by nnadd** [cmcaine/tridactyl#945]
Just a simple question, I could easily done this on the old XUL vimperator, I want the go and gn commands rebound to e and E, I did this previously with `nmap "e" go` and `nmap "E" gn` so I could have easy, one hand access to my quickmarks(which were 1-5), but tridactyl has a different syntax and I can't really find what do with the alias or bind commands no matter how much I look through the help pages.

So instead of a quickmark opening with go[1] or gn[1] I want to open it with e[1] and E[1]. 

Thanks.

**Comment by bovine3dom** [comment]
Hi,

You can't bind keys to keys currently, you can only bind keys to ex commands.

Luckily our `quickmark` is a really simple function, https://github.com/cmcaine/tridactyl/blob/9c68598/src/excmds.ts#L2805, so you just need to manually bind e and E with `bind e[key] open [site]`  and `bind E[key] tabopen [site]`.

If you want to avoid doing it manually, you can probably do what you want with a line at the start of your RC file which finds all the binds starting with go and gn and binds them to e/E instead: `jsb let nmaps = tri.config.get("nmaps"); // filter for go, filter for gn, then use tri.excmds.bind("e " + key + " " + site)` etc.  You can then unbind the go/gn keys with tri.excmds.unbind.

Hope this helps.

**Comment by nnadd** [comment]
Very helpful, you solved my problem, and with `composite` I can get multiple URL's open at once, fantastic.

I shall close this so it isn't cluttering up the issue page, thank you so much for this wonderful addon!
