### ISSUE TITLE
":set newtab about:home" does not work

### ISSUE THREAD

**Issue by leonixyz** [cmcaine/tridactyl#948]
# Reporting a bug / getting help

*   Brief description of the problem:
    I want to see "about:home" whenever I open a new tab. I run the command `:set newtab about:home`, but it does not have any effect

*   Steps to reproduce:
  1. run `:set newtab about:home`
  2. restart browser
  3. open new tab

*   Tridactyl version (`:version`): **1.9.8-3-g4d969e5**

*   Firefox version (Top right menu > Help > About Firefox): **61.0.2 (64-bit)** Mozilla Firefox for Arch Linux

*   URL of the website the bug happens on: **not applicable**

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/leonixyz/15a8ce1f4a8e1b5285cc67d59c401f57

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): **not existing**

**Comment by bovine3dom** [comment]
That's an impressively old version of Tridactyl, would you mind updating? You probably need to click the tiny yellow exclamation mark in the top right and accept some more permissions.

I can't remember where we got to with about:home. I don't think we're allowed to open it. We might be allowed to open about:blank. Could you try again once you have updated?

**Comment by glacambre** [comment]
We should probably remove `about:home` from ABOUT_WHITELIST: https://github.com/cmcaine/tridactyl/blob/4f779c7df25e15c80de3cc3b8f46c2e488d87e06/src/excmds.ts#L855

**Comment by leonixyz** [comment]
I updated to 1.13.3-1.13.3 and it still doesn't work... btw i can neither open it using the open command.

**Comment by bovine3dom** [comment]
Can reproduce - I think we put it on the whitelist at some point and then Mozilla stopped us from being able to open it.

**Comment by bovine3dom** [comment]
`set newtab about:home` now works as jankily as I was expecting it to:

- you need native messenger installed
- `tabopen` with no argument works fine
- new tabs opened any other way will open two new tabs, the visible one will use `about:home`.

One _could_ write some hacky workaround to close the tab after a new one is opened in src/content.ts:74 ish if the newtab URL contains `about:`, but I'll leave that as an exercise for the reader. Happy to answer queries on Riot as always.

**Comment by glacambre** [comment]
There is a beta build that comes without a newtab page (and thus lets you firefox's default newtab page): https://tridactyl.cmcaine.co.uk/betas/nonewtab/tridactyl_no_new_tab_beta-latest.xpi
