### ISSUE TITLE
No pageup/pagedown with recent betas?

### ISSUE THREAD

**Issue by larsks** [cmcaine/tridactyl#95]
With `1.4.1pre354`, while my space bar is working (yay!), it seems as if pageup/pagedown no longer work (nor do "home" or "end").

**Comment by cmcaine** [comment]
Fixed in 1.4.3, thanks: c84e8016c97d46519c8315b4532b227e3776c7d0

I made some late night changes to the key suppression logic and broke it. I don't think I'll push non-bugfixes to AMO at night again :)

**Comment by cmcaine** [comment]
I'll leave this open for the next 24h so that anyone who's unlucky enough to get 1.4.0-1.4.2 has a chance to see it and know to update.

**Comment by larsks** [comment]
> Fixed in 1.4.3, thanks: c84e801

No, thank *you*!
