### ISSUE TITLE
Search (`/`) still captured on google groups

### ISSUE THREAD

**Issue by timokau** [cmcaine/tridactyl#950]
Recently it was fixed for github and the `ctrl+f` default binding was overwritten. However google groups ([example](https://groups.google.com/forum/#!forum/sage-devel)) still captures `/`. Combined with the overwritten `ctrl+f`, that makes searching impossible (except through `unbind`ing `ctrl+f`).

**Comment by bovine3dom** [comment]
Probably a duplicate of #904.
