### ISSUE TITLE
Pass '/' in ignore mode

### ISSUE THREAD

**Issue by stevenbell** [cmcaine/tridactyl#954]
I'm *really* grateful that the "stealing /" thing is fixed on Github, but it looks like it doesn't get turned off when I go into ignore mode.  I run Gmail in ignore mode all the time, and now I have to click on the search bar...

To reproduce:
* Open Github or Gmail
* Go into ignore mode (`shift-insert`)
* Press `/`
I expect this to focus the search bar in Github or Gmail, but instead it brings up the firefox search bar.

I have Tridactyl 1.13.3, Firefox 61.0.1

**Comment by bovine3dom** [comment]
Yeah, it's probably because I did it in a slightly mad way. I'll see if `bind / echo` works.
