### ISSUE TITLE
crazy reloading on wikiwiki.jp/*/

### ISSUE THREAD

**Issue by lycsjm** [cmcaine/tridactyl#955]
*   Brief description of the problem:
Enable causing wikiwiki.jp/\*/ crazy refresh page, but wikiwiki.jp/ not.
Some case like cilck wikiwiki.jp/\* url from other site or from history will not cause that problem.

*   Steps to reproduce:

    1. Enable tridactyl
    2. Click something like wikiwiki.jp/kancolle or wikiwiki.jp/dolls-fl/

*   Tridactyl version (`:version`):
1.13.3-1.13.3

*   Firefox version (Top right menu > Help > About Firefox):
61.0.2

*   URL of the website the bug happens on:
    * https://wikiwiki.jp/kancolle2nd/
    * https://wikiwiki.jp/dolls-fl/
    * etc..

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/lycsjm/fe4d82c0a8a7d58979bef0c1e85673fa

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
Insert tridactylrc contents between the backticks
```

*   Operating system:
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

**Comment by glacambre** [comment]
Hi, thank you for reporting this issue. This seems to be the same issue as https://github.com/cmcaine/tridactyl/issues/910 and the problem can be alleviated by using `:set noiframeon wikiwiki.jp`, which will disable the command line on this website. Really fixing this issue will be done by implementing https://github.com/cmcaine/tridactyl/issues/639 .

**Comment by lycsjm** [comment]
OK, now it can works by  `:set noiframeon wikiwiki.jp/kancolle`.
thansk for replying.
