### ISSUE TITLE
open homepage(s) via Tridactyl

### ISSUE THREAD

**Issue by Kilian** [cmcaine/tridactyl#96]
In Vimperator, you could open your homepage(s) using `gh` top open in the current tab (first homepage) and new tabs (subsequent homepages), and open all of them in new tabs using `gH`. Is 'opening homepages' already an available command in Tridactyl?

**Comment by h2ero** [comment]
You can use quickmarks https://github.com/cmcaine/tridactyl/pull/78

**Comment by Kilian** [comment]
You're able to have multiple homepages by using a `|` between urls in the homepage field. From my understanding you can not bind multiple URLS to a quickmark, is that correct?

**Comment by h2ero** [comment]
Yes,  I ignore you have multiple homepages。 In Vimperator I used quickmarks open my often visited sites.

**Comment by bovine3dom** [comment]
This should be pretty easy with the bookmarks API. Good first issue if anyone wants it.

**Comment by scrummyin** [comment]
I wanted to let you all know that I started to work on this one, and had issues with current production firefox. The `browser.browserSettings.homepageOverride.get({})` call throws an exception for me from the version of Firefox in the Ubuntu default ppa. However, I just ran it against Firefox mainline (https://hg.mozilla.org/mozilla-central/) and it seems to work.

**Comment by bovine3dom** [comment]
Firefox should be version 57 on Ubuntu - https://packages.ubuntu.com/artful/web/firefox - which should support it. Are you sure you've updated recently?

Thanks for giving it a go!

**Comment by scrummyin** [comment]
Firefox does "support" the call, as in it is present in the API and I can call into it. However, it's throws an exception from inside mapSettings (sorry not at a machine currently so can't say where exactly). I would like to run an blame and bisect on Firefox to find when it was fixed.

**Comment by scrummyin** [comment]
Just got back home and screenshotted the error which I see on Firefox 57.0 (64-bit 57.0+build4-0ubuntu0.16.04.5).  Image is below and a link for easy copy & paste format is https://gist.github.com/scrummyin/b40dd583ab74072d90c673875adfb742 

I do have code that works on firefox mainline that I can hopefully commit later.

![selection_012](https://user-images.githubusercontent.com/158252/33246726-3881ed56-d2e6-11e7-8c31-620b1ef67a5b.png)

**Comment by bovine3dom** [comment]
@scrummyin I've made this an internal setting for now. I'm 100% happy to accept a PR that uses Firefox's settings as the default (but I think we can only get a single homepage, so our own setting will remain).

**Comment by SunflowerPKU** [comment]
> Firefox does "support" the call, as in it is present in the API and I can call into it. However, it's throws an exception from inside mapSettings (sorry not at a machine currently so can't say where exactly). I would like to run an blame and bisect on Firefox to find when it was fixed.

Hi @scrummyin ,

I am a Ph.D. student. I am doing research about helping newcomers participate in OSS projects. I noticed that many projects are using labels such as 'good first issue/bug, difficulty/newcomer' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

**1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?**

I am looking forward to hearing from you soon. Thank you very much!
