### ISSUE TITLE
I’m missing CTRL-a / CTRL-x

### ISSUE THREAD

**Issue by lartaud** [cmcaine/tridactyl#97]
Hello!
Coming from Vimperator, I find myself missing a way to increment/decrement the last number in the current URL and load the new page.
“O” then manually editing the URL works as a work-around, but is a bit tedious…
Do you plan to add this feature?

**Comment by bovine3dom** [comment]
Yes, see #75, but it will not be bound to ^a/^x, at least not until we support modifiers.

**Comment by bovine3dom** [comment]
`[c` and `]c` {in,de}crement URL as of eae9cd0dabc47129c73b81ac433c795fdf513f35. It will be in the latest beta on the AMO within a few minutes.

Leaving issue open to remind us to consider ^a / ^x once we support modifiers.

**Comment by gsbabil** [comment]
In the meantime, you may bind your own keys like the following:

```
:bind ,a urlincrement +1
:bind ,x urlincrement -1
```

**Comment by bovine3dom** [comment]
@lartaud `<C-a>` and `<C-x>` were added a short while ago (~ 1 week ago) :)
