### ISSUE TITLE
Strange behaviour with “bind D composite tabclose | tabprev”

### ISSUE THREAD

**Issue by lartaud** [cmcaine/tridactyl#99]
Hello!
Sometimes, the indicated binding goes back _two_ tabs instead of just one.
I’m using 1.4.3.
To reproduce the bug:
* Open three tabs
* In the second tab, go (for example) to “https://github.com/cmcaine/tridactyl/network”
* Click on a commit: it opens in a new tab just after the current one, activating it.
* Hit “D”: The commit’s tab closes, tab two activates, then immediately after that tab one activates.

However, should one activate any other tab, then go back to the commit’s tab, “D” works as expected.

**Comment by bovine3dom** [comment]
d448d10 introduces `tabclosethenprev` which should do what you want it to.

The build bot is currently undergoing maintenance (i.e, broken) so it will take a while before it appears on the AMO.

**Comment by bovine3dom** [comment]
@lartaud: Sorry, I was really tired when I wrote that last night. Your problem is actually very simple - you just want `composite tabclose | buffer #` rather than using `tabprev`, I think.

Please let me know if that solves the issue.

**Comment by lartaud** [comment]
It seems to work correctly.
You will want to change the “:help bind” examples though…

However, the problem might be something else (and I’m sorry I didn’t think of testing this yesterday…): with the exact same test condition, the factory “d” hint activates the left tab instead of the right one after deleting the tab…
